//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: active.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActiveInfoReq")]
  public partial class CmdActiveInfoReq : global::ProtoBuf.IExtensible
  {
    public CmdActiveInfoReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActiveInfoRes")]
  public partial class CmdActiveInfoRes : global::ProtoBuf.IExtensible
  {
    public CmdActiveInfoRes() {}
    
    private readonly global::System.Collections.Generic.List<uint> _id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> id
    {
      get { return _id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _activeData = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"activeData", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> activeData
    {
      get { return _activeData; }
    }
  
    private uint? _totalScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"totalScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint totalScore
    {
      get { return _totalScore?? default(uint); }
      set { _totalScore = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalScoreSpecified
    {
      get { return this._totalScore != null; }
      set { if (value == (this._totalScore== null)) this._totalScore = value ? this.totalScore : (uint?)null; }
    }
    private bool ShouldSerializetotalScore() { return totalScoreSpecified; }
    private void ResettotalScore() { totalScoreSpecified = false; }
    
    private uint? _takeData;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"takeData", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint takeData
    {
      get { return _takeData?? default(uint); }
      set { _takeData = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool takeDataSpecified
    {
      get { return this._takeData != null; }
      set { if (value == (this._takeData== null)) this._takeData = value ? this.takeData : (uint?)null; }
    }
    private bool ShouldSerializetakeData() { return takeDataSpecified; }
    private void ResettakeData() { takeDataSpecified = false; }
    
    private uint? _lastTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lastTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastTime
    {
      get { return _lastTime?? default(uint); }
      set { _lastTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastTimeSpecified
    {
      get { return this._lastTime != null; }
      set { if (value == (this._lastTime== null)) this._lastTime = value ? this.lastTime : (uint?)null; }
    }
    private bool ShouldSerializelastTime() { return lastTimeSpecified; }
    private void ResetlastTime() { lastTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActiveTakeAwardReq")]
  public partial class CmdActiveTakeAwardReq : global::ProtoBuf.IExtensible
  {
    public CmdActiveTakeAwardReq() {}
    
    private uint? _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint index
    {
      get { return _index?? default(uint); }
      set { _index = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool indexSpecified
    {
      get { return this._index != null; }
      set { if (value == (this._index== null)) this._index = value ? this.index : (uint?)null; }
    }
    private bool ShouldSerializeindex() { return indexSpecified; }
    private void Resetindex() { indexSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActiveTakeAwardRes")]
  public partial class CmdActiveTakeAwardRes : global::ProtoBuf.IExtensible
  {
    public CmdActiveTakeAwardRes() {}
    
    private uint? _takeData;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"takeData", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint takeData
    {
      get { return _takeData?? default(uint); }
      set { _takeData = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool takeDataSpecified
    {
      get { return this._takeData != null; }
      set { if (value == (this._takeData== null)) this._takeData = value ? this.takeData : (uint?)null; }
    }
    private bool ShouldSerializetakeData() { return takeDataSpecified; }
    private void ResettakeData() { takeDataSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActiveScoreUpdateNtf")]
  public partial class CmdActiveScoreUpdateNtf : global::ProtoBuf.IExtensible
  {
    public CmdActiveScoreUpdateNtf() {}
    
    private uint? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint id
    {
      get { return _id?? default(uint); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (uint?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private uint? _activeData;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"activeData", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint activeData
    {
      get { return _activeData?? default(uint); }
      set { _activeData = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool activeDataSpecified
    {
      get { return this._activeData != null; }
      set { if (value == (this._activeData== null)) this._activeData = value ? this.activeData : (uint?)null; }
    }
    private bool ShouldSerializeactiveData() { return activeDataSpecified; }
    private void ResetactiveData() { activeDataSpecified = false; }
    
    private uint? _totalScore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"totalScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint totalScore
    {
      get { return _totalScore?? default(uint); }
      set { _totalScore = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalScoreSpecified
    {
      get { return this._totalScore != null; }
      set { if (value == (this._totalScore== null)) this._totalScore = value ? this.totalScore : (uint?)null; }
    }
    private bool ShouldSerializetotalScore() { return totalScoreSpecified; }
    private void ResettotalScore() { totalScoreSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActiveScoreInfoNtf")]
  public partial class CmdActiveScoreInfoNtf : global::ProtoBuf.IExtensible
  {
    public CmdActiveScoreInfoNtf() {}
    
    private readonly global::System.Collections.Generic.List<uint> _id = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(4, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> id
    {
      get { return _id; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _activeData = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(3, Name=@"activeData", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> activeData
    {
      get { return _activeData; }
    }
  
    private uint? _totalScore;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"totalScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint totalScore
    {
      get { return _totalScore?? default(uint); }
      set { _totalScore = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalScoreSpecified
    {
      get { return this._totalScore != null; }
      set { if (value == (this._totalScore== null)) this._totalScore = value ? this.totalScore : (uint?)null; }
    }
    private bool ShouldSerializetotalScore() { return totalScoreSpecified; }
    private void ResettotalScore() { totalScoreSpecified = false; }
    
    private uint? _takeData;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"takeData", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint takeData
    {
      get { return _takeData?? default(uint); }
      set { _takeData = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool takeDataSpecified
    {
      get { return this._takeData != null; }
      set { if (value == (this._takeData== null)) this._takeData = value ? this.takeData : (uint?)null; }
    }
    private bool ShouldSerializetakeData() { return takeDataSpecified; }
    private void ResettakeData() { takeDataSpecified = false; }
    
    private uint? _lastTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lastTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastTime
    {
      get { return _lastTime?? default(uint); }
      set { _lastTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastTimeSpecified
    {
      get { return this._lastTime != null; }
      set { if (value == (this._lastTime== null)) this._lastTime = value ? this.lastTime : (uint?)null; }
    }
    private bool ShouldSerializelastTime() { return lastTimeSpecified; }
    private void ResetlastTime() { lastTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActiveCompleteShareReq")]
  public partial class CmdActiveCompleteShareReq : global::ProtoBuf.IExtensible
  {
    public CmdActiveCompleteShareReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActiveShareDataNtf")]
  public partial class CmdActiveShareDataNtf : global::ProtoBuf.IExtensible
  {
    public CmdActiveShareDataNtf() {}
    
    private uint? _lastShareTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"lastShareTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastShareTime
    {
      get { return _lastShareTime?? default(uint); }
      set { _lastShareTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastShareTimeSpecified
    {
      get { return this._lastShareTime != null; }
      set { if (value == (this._lastShareTime== null)) this._lastShareTime = value ? this.lastShareTime : (uint?)null; }
    }
    private bool ShouldSerializelastShareTime() { return lastShareTimeSpecified; }
    private void ResetlastShareTime() { lastShareTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdActive")]
    public enum CmdActive
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActive_InfoReq", Value=2801)]
      CmdActive_InfoReq = 2801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActive_InfoRes", Value=2802)]
      CmdActive_InfoRes = 2802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActive_TakeAwardReq", Value=2803)]
      CmdActive_TakeAwardReq = 2803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActive_TakeAwardRes", Value=2804)]
      CmdActive_TakeAwardRes = 2804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActive_ScoreUpdateNtf", Value=2805)]
      CmdActive_ScoreUpdateNtf = 2805,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActive_ScoreInfoNtf", Value=2806)]
      CmdActive_ScoreInfoNtf = 2806,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActive_CompleteShareReq", Value=2807)]
      CmdActive_CompleteShareReq = 2807,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActive_ShareDataNtf", Value=2808)]
      CmdActive_ShareDataNtf = 2808
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorActive")]
    public enum ErrorActive
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActive_HasTook", Value=2801)]
      ErrorActive_HasTook = 2801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActive_RewarInfoNotFound", Value=2802)]
      ErrorActive_RewarInfoNotFound = 2802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActive_ScoreNotEnough", Value=2803)]
      ErrorActive_ScoreNotEnough = 2803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActive_HasTake", Value=2804)]
      ErrorActive_HasTake = 2804
    }
  
}