//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: activityInstance.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityTarget")]
  public partial class ActivityTarget : global::ProtoBuf.IExtensible
  {
    public ActivityTarget() {}
    
    private int? _targetType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"targetType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int targetType
    {
      get { return _targetType?? default(int); }
      set { _targetType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool targetTypeSpecified
    {
      get { return this._targetType != null; }
      set { if (value == (this._targetType== null)) this._targetType = value ? this.targetType : (int?)null; }
    }
    private bool ShouldSerializetargetType() { return targetTypeSpecified; }
    private void ResettargetType() { targetTypeSpecified = false; }
    
    private int? _curProcess;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"curProcess", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curProcess
    {
      get { return _curProcess?? default(int); }
      set { _curProcess = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curProcessSpecified
    {
      get { return this._curProcess != null; }
      set { if (value == (this._curProcess== null)) this._curProcess = value ? this.curProcess : (int?)null; }
    }
    private bool ShouldSerializecurProcess() { return curProcessSpecified; }
    private void ResetcurProcess() { curProcessSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityInstance")]
  public partial class ActivityInstance : global::ProtoBuf.IExtensible
  {
    public ActivityInstance() {}
    
    private int? _insInfoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"insInfoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int insInfoId
    {
      get { return _insInfoId?? default(int); }
      set { _insInfoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool insInfoIdSpecified
    {
      get { return this._insInfoId != null; }
      set { if (value == (this._insInfoId== null)) this._insInfoId = value ? this.insInfoId : (int?)null; }
    }
    private bool ShouldSerializeinsInfoId() { return insInfoIdSpecified; }
    private void ResetinsInfoId() { insInfoIdSpecified = false; }
    
    private uint? _lastPassTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lastPassTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastPassTime
    {
      get { return _lastPassTime?? default(uint); }
      set { _lastPassTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastPassTimeSpecified
    {
      get { return this._lastPassTime != null; }
      set { if (value == (this._lastPassTime== null)) this._lastPassTime = value ? this.lastPassTime : (uint?)null; }
    }
    private bool ShouldSerializelastPassTime() { return lastPassTimeSpecified; }
    private void ResetlastPassTime() { lastPassTimeSpecified = false; }
    
    private int? _passTimes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"passTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int passTimes
    {
      get { return _passTimes?? default(int); }
      set { _passTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool passTimesSpecified
    {
      get { return this._passTimes != null; }
      set { if (value == (this._passTimes== null)) this._passTimes = value ? this.passTimes : (int?)null; }
    }
    private bool ShouldSerializepassTimes() { return passTimesSpecified; }
    private void ResetpassTimes() { passTimesSpecified = false; }
    
    private int? _lastScore;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lastScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lastScore
    {
      get { return _lastScore?? default(int); }
      set { _lastScore = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastScoreSpecified
    {
      get { return this._lastScore != null; }
      set { if (value == (this._lastScore== null)) this._lastScore = value ? this.lastScore : (int?)null; }
    }
    private bool ShouldSerializelastScore() { return lastScoreSpecified; }
    private void ResetlastScore() { lastScoreSpecified = false; }
    
    private bool? _reward;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool reward
    {
      get { return _reward?? default(bool); }
      set { _reward = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rewardSpecified
    {
      get { return this._reward != null; }
      set { if (value == (this._reward== null)) this._reward = value ? this.reward : (bool?)null; }
    }
    private bool ShouldSerializereward() { return rewardSpecified; }
    private void Resetreward() { rewardSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.ActivityTarget> _target = new global::System.Collections.Generic.List<Proto.ActivityTarget>();
    [global::ProtoBuf.ProtoMember(6, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.ActivityTarget> target
    {
      get { return _target; }
    }
  
    private uint? _dmg;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"dmg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dmg
    {
      get { return _dmg?? default(uint); }
      set { _dmg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dmgSpecified
    {
      get { return this._dmg != null; }
      set { if (value == (this._dmg== null)) this._dmg = value ? this.dmg : (uint?)null; }
    }
    private bool ShouldSerializedmg() { return dmgSpecified; }
    private void Resetdmg() { dmgSpecified = false; }
    
    private uint? _dmgRank;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dmgRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dmgRank
    {
      get { return _dmgRank?? default(uint); }
      set { _dmgRank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dmgRankSpecified
    {
      get { return this._dmgRank != null; }
      set { if (value == (this._dmgRank== null)) this._dmgRank = value ? this.dmgRank : (uint?)null; }
    }
    private bool ShouldSerializedmgRank() { return dmgRankSpecified; }
    private void ResetdmgRank() { dmgRankSpecified = false; }
    
    private int? _totalExp;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"totalExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalExp
    {
      get { return _totalExp?? default(int); }
      set { _totalExp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalExpSpecified
    {
      get { return this._totalExp != null; }
      set { if (value == (this._totalExp== null)) this._totalExp = value ? this.totalExp : (int?)null; }
    }
    private bool ShouldSerializetotalExp() { return totalExpSpecified; }
    private void ResettotalExp() { totalExpSpecified = false; }
    
    private int? _wave;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"wave", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wave
    {
      get { return _wave?? default(int); }
      set { _wave = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool waveSpecified
    {
      get { return this._wave != null; }
      set { if (value == (this._wave== null)) this._wave = value ? this.wave : (int?)null; }
    }
    private bool ShouldSerializewave() { return waveSpecified; }
    private void Resetwave() { waveSpecified = false; }
    
    private int? _evaluation;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"evaluation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int evaluation
    {
      get { return _evaluation?? default(int); }
      set { _evaluation = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool evaluationSpecified
    {
      get { return this._evaluation != null; }
      set { if (value == (this._evaluation== null)) this._evaluation = value ? this.evaluation : (int?)null; }
    }
    private bool ShouldSerializeevaluation() { return evaluationSpecified; }
    private void Resetevaluation() { evaluationSpecified = false; }
    
    private bool? _vipDouble;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"vipDouble", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool vipDouble
    {
      get { return _vipDouble?? default(bool); }
      set { _vipDouble = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool vipDoubleSpecified
    {
      get { return this._vipDouble != null; }
      set { if (value == (this._vipDouble== null)) this._vipDouble = value ? this.vipDouble : (bool?)null; }
    }
    private bool ShouldSerializevipDouble() { return vipDoubleSpecified; }
    private void ResetvipDouble() { vipDoubleSpecified = false; }
    
    private uint? _buyTimes;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"buyTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint buyTimes
    {
      get { return _buyTimes?? default(uint); }
      set { _buyTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buyTimesSpecified
    {
      get { return this._buyTimes != null; }
      set { if (value == (this._buyTimes== null)) this._buyTimes = value ? this.buyTimes : (uint?)null; }
    }
    private bool ShouldSerializebuyTimes() { return buyTimesSpecified; }
    private void ResetbuyTimes() { buyTimesSpecified = false; }
    
    private uint? _lastBuyTime;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"lastBuyTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastBuyTime
    {
      get { return _lastBuyTime?? default(uint); }
      set { _lastBuyTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastBuyTimeSpecified
    {
      get { return this._lastBuyTime != null; }
      set { if (value == (this._lastBuyTime== null)) this._lastBuyTime = value ? this.lastBuyTime : (uint?)null; }
    }
    private bool ShouldSerializelastBuyTime() { return lastBuyTimeSpecified; }
    private void ResetlastBuyTime() { lastBuyTimeSpecified = false; }
    
    private uint? _canReliveTimes;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"canReliveTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint canReliveTimes
    {
      get { return _canReliveTimes?? default(uint); }
      set { _canReliveTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool canReliveTimesSpecified
    {
      get { return this._canReliveTimes != null; }
      set { if (value == (this._canReliveTimes== null)) this._canReliveTimes = value ? this.canReliveTimes : (uint?)null; }
    }
    private bool ShouldSerializecanReliveTimes() { return canReliveTimesSpecified; }
    private void ResetcanReliveTimes() { canReliveTimesSpecified = false; }
    
    private int? _totalCoin;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"totalCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalCoin
    {
      get { return _totalCoin?? default(int); }
      set { _totalCoin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalCoinSpecified
    {
      get { return this._totalCoin != null; }
      set { if (value == (this._totalCoin== null)) this._totalCoin = value ? this.totalCoin : (int?)null; }
    }
    private bool ShouldSerializetotalCoin() { return totalCoinSpecified; }
    private void ResettotalCoin() { totalCoinSpecified = false; }
    
    private uint? _itemAddTimes;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"itemAddTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemAddTimes
    {
      get { return _itemAddTimes?? default(uint); }
      set { _itemAddTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemAddTimesSpecified
    {
      get { return this._itemAddTimes != null; }
      set { if (value == (this._itemAddTimes== null)) this._itemAddTimes = value ? this.itemAddTimes : (uint?)null; }
    }
    private bool ShouldSerializeitemAddTimes() { return itemAddTimesSpecified; }
    private void ResetitemAddTimes() { itemAddTimesSpecified = false; }
    
    private uint? _lastItemAddTime;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"lastItemAddTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastItemAddTime
    {
      get { return _lastItemAddTime?? default(uint); }
      set { _lastItemAddTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastItemAddTimeSpecified
    {
      get { return this._lastItemAddTime != null; }
      set { if (value == (this._lastItemAddTime== null)) this._lastItemAddTime = value ? this.lastItemAddTime : (uint?)null; }
    }
    private bool ShouldSerializelastItemAddTime() { return lastItemAddTimeSpecified; }
    private void ResetlastItemAddTime() { lastItemAddTimeSpecified = false; }
    
    private uint? _maxlayer;
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"maxlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxlayer
    {
      get { return _maxlayer?? default(uint); }
      set { _maxlayer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool maxlayerSpecified
    {
      get { return this._maxlayer != null; }
      set { if (value == (this._maxlayer== null)) this._maxlayer = value ? this.maxlayer : (uint?)null; }
    }
    private bool ShouldSerializemaxlayer() { return maxlayerSpecified; }
    private void Resetmaxlayer() { maxlayerSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.ActivityRewardItem> _rewarditem = new global::System.Collections.Generic.List<Proto.ActivityRewardItem>();
    [global::ProtoBuf.ProtoMember(20, Name=@"rewarditem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.ActivityRewardItem> rewarditem
    {
      get { return _rewarditem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceDataNtf")]
  public partial class CmdActivityInstanceDataNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceDataNtf() {}
    
    private readonly global::System.Collections.Generic.List<Proto.ActivityInstance> _activity = new global::System.Collections.Generic.List<Proto.ActivityInstance>();
    [global::ProtoBuf.ProtoMember(1, Name=@"activity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.ActivityInstance> activity
    {
      get { return _activity; }
    }
  
    private uint? _serverlayer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"serverlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint serverlayer
    {
      get { return _serverlayer?? default(uint); }
      set { _serverlayer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool serverlayerSpecified
    {
      get { return this._serverlayer != null; }
      set { if (value == (this._serverlayer== null)) this._serverlayer = value ? this.serverlayer : (uint?)null; }
    }
    private bool ShouldSerializeserverlayer() { return serverlayerSpecified; }
    private void Resetserverlayer() { serverlayerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceEnterReq")]
  public partial class CmdActivityInstanceEnterReq : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceEnterReq() {}
    
    private int? _insInfoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"insInfoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int insInfoId
    {
      get { return _insInfoId?? default(int); }
      set { _insInfoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool insInfoIdSpecified
    {
      get { return this._insInfoId != null; }
      set { if (value == (this._insInfoId== null)) this._insInfoId = value ? this.insInfoId : (int?)null; }
    }
    private bool ShouldSerializeinsInfoId() { return insInfoIdSpecified; }
    private void ResetinsInfoId() { insInfoIdSpecified = false; }
    
    private int? _layer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"layer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int layer
    {
      get { return _layer?? default(int); }
      set { _layer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool layerSpecified
    {
      get { return this._layer != null; }
      set { if (value == (this._layer== null)) this._layer = value ? this.layer : (int?)null; }
    }
    private bool ShouldSerializelayer() { return layerSpecified; }
    private void Resetlayer() { layerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceEnterRes")]
  public partial class CmdActivityInstanceEnterRes : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceEnterRes() {}
    
    private Proto.ActivityInstance _activity = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"activity", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.ActivityInstance activity
    {
      get { return _activity; }
      set { _activity = value; }
    }
    private uint? _createTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint createTime
    {
      get { return _createTime?? default(uint); }
      set { _createTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool createTimeSpecified
    {
      get { return this._createTime != null; }
      set { if (value == (this._createTime== null)) this._createTime = value ? this.createTime : (uint?)null; }
    }
    private bool ShouldSerializecreateTime() { return createTimeSpecified; }
    private void ResetcreateTime() { createTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceScoreNtf")]
  public partial class CmdActivityInstanceScoreNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceScoreNtf() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private int? _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score?? default(int); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (int?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityRoleInfo")]
  public partial class ActivityRoleInfo : global::ProtoBuf.IExtensible
  {
    public ActivityRoleInfo() {}
    
    private ulong? _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId?? default(ulong); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return this._roleId != null; }
      set { if (value == (this._roleId== null)) this._roleId = value ? this.roleId : (ulong?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private uint? _occupation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"occupation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint occupation
    {
      get { return _occupation?? default(uint); }
      set { _occupation = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupationSpecified
    {
      get { return this._occupation != null; }
      set { if (value == (this._occupation== null)) this._occupation = value ? this.occupation : (uint?)null; }
    }
    private bool ShouldSerializeoccupation() { return occupationSpecified; }
    private void Resetoccupation() { occupationSpecified = false; }
    
    private byte[] _roleName;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] roleName
    {
      get { return _roleName?? null; }
      set { _roleName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleNameSpecified
    {
      get { return this._roleName != null; }
      set { if (value == (this._roleName== null)) this._roleName = value ? this.roleName : (byte[])null; }
    }
    private bool ShouldSerializeroleName() { return roleNameSpecified; }
    private void ResetroleName() { roleNameSpecified = false; }
    
    private int? _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score?? default(int); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (int?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private uint? _scoreTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"scoreTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scoreTime
    {
      get { return _scoreTime?? default(uint); }
      set { _scoreTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreTimeSpecified
    {
      get { return this._scoreTime != null; }
      set { if (value == (this._scoreTime== null)) this._scoreTime = value ? this.scoreTime : (uint?)null; }
    }
    private bool ShouldSerializescoreTime() { return scoreTimeSpecified; }
    private void ResetscoreTime() { scoreTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceRoleInfoNtf")]
  public partial class CmdActivityInstanceRoleInfoNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceRoleInfoNtf() {}
    
    private readonly global::System.Collections.Generic.List<Proto.ActivityRoleInfo> _info = new global::System.Collections.Generic.List<Proto.ActivityRoleInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.ActivityRoleInfo> info
    {
      get { return _info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceRoleInfoRemoveNtf")]
  public partial class CmdActivityInstanceRoleInfoRemoveNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceRoleInfoRemoveNtf() {}
    
    private ulong? _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId?? default(ulong); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return this._roleId != null; }
      set { if (value == (this._roleId== null)) this._roleId = value ? this.roleId : (ulong?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceMaxScoreNtf")]
  public partial class CmdActivityInstanceMaxScoreNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceMaxScoreNtf() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private int? _maxScore;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"maxScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxScore
    {
      get { return _maxScore?? default(int); }
      set { _maxScore = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool maxScoreSpecified
    {
      get { return this._maxScore != null; }
      set { if (value == (this._maxScore== null)) this._maxScore = value ? this.maxScore : (int?)null; }
    }
    private bool ShouldSerializemaxScore() { return maxScoreSpecified; }
    private void ResetmaxScore() { maxScoreSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceWaveNtf")]
  public partial class CmdActivityInstanceWaveNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceWaveNtf() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private int? _wave;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"wave", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wave
    {
      get { return _wave?? default(int); }
      set { _wave = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool waveSpecified
    {
      get { return this._wave != null; }
      set { if (value == (this._wave== null)) this._wave = value ? this.wave : (int?)null; }
    }
    private bool ShouldSerializewave() { return waveSpecified; }
    private void Resetwave() { waveSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceTotalExpNtf")]
  public partial class CmdActivityInstanceTotalExpNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceTotalExpNtf() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private int? _totalExp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"totalExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalExp
    {
      get { return _totalExp?? default(int); }
      set { _totalExp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalExpSpecified
    {
      get { return this._totalExp != null; }
      set { if (value == (this._totalExp== null)) this._totalExp = value ? this.totalExp : (int?)null; }
    }
    private bool ShouldSerializetotalExp() { return totalExpSpecified; }
    private void ResettotalExp() { totalExpSpecified = false; }
    
    private int? _totalCoin;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"totalCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalCoin
    {
      get { return _totalCoin?? default(int); }
      set { _totalCoin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalCoinSpecified
    {
      get { return this._totalCoin != null; }
      set { if (value == (this._totalCoin== null)) this._totalCoin = value ? this.totalCoin : (int?)null; }
    }
    private bool ShouldSerializetotalCoin() { return totalCoinSpecified; }
    private void ResettotalCoin() { totalCoinSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceEvaluationNtf")]
  public partial class CmdActivityInstanceEvaluationNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceEvaluationNtf() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private int? _evaluation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"evaluation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int evaluation
    {
      get { return _evaluation?? default(int); }
      set { _evaluation = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool evaluationSpecified
    {
      get { return this._evaluation != null; }
      set { if (value == (this._evaluation== null)) this._evaluation = value ? this.evaluation : (int?)null; }
    }
    private bool ShouldSerializeevaluation() { return evaluationSpecified; }
    private void Resetevaluation() { evaluationSpecified = false; }
    
    private int? _processPer;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"processPer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int processPer
    {
      get { return _processPer?? default(int); }
      set { _processPer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool processPerSpecified
    {
      get { return this._processPer != null; }
      set { if (value == (this._processPer== null)) this._processPer = value ? this.processPer : (int?)null; }
    }
    private bool ShouldSerializeprocessPer() { return processPerSpecified; }
    private void ResetprocessPer() { processPerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceCanReliveTimesNtf")]
  public partial class CmdActivityInstanceCanReliveTimesNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceCanReliveTimesNtf() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private uint? _canReliveTimes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"canReliveTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint canReliveTimes
    {
      get { return _canReliveTimes?? default(uint); }
      set { _canReliveTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool canReliveTimesSpecified
    {
      get { return this._canReliveTimes != null; }
      set { if (value == (this._canReliveTimes== null)) this._canReliveTimes = value ? this.canReliveTimes : (uint?)null; }
    }
    private bool ShouldSerializecanReliveTimes() { return canReliveTimesSpecified; }
    private void ResetcanReliveTimes() { canReliveTimesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityRewardItem")]
  public partial class ActivityRewardItem : global::ProtoBuf.IExtensible
  {
    public ActivityRewardItem() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private uint? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count?? default(uint); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (uint?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceEndNtf")]
  public partial class CmdActivityInstanceEndNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceEndNtf() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private int? _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score?? default(int); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (int?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private uint? _dmg;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dmg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dmg
    {
      get { return _dmg?? default(uint); }
      set { _dmg = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dmgSpecified
    {
      get { return this._dmg != null; }
      set { if (value == (this._dmg== null)) this._dmg = value ? this.dmg : (uint?)null; }
    }
    private bool ShouldSerializedmg() { return dmgSpecified; }
    private void Resetdmg() { dmgSpecified = false; }
    
    private uint? _dmgRank;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"dmgRank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dmgRank
    {
      get { return _dmgRank?? default(uint); }
      set { _dmgRank = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dmgRankSpecified
    {
      get { return this._dmgRank != null; }
      set { if (value == (this._dmgRank== null)) this._dmgRank = value ? this.dmgRank : (uint?)null; }
    }
    private bool ShouldSerializedmgRank() { return dmgRankSpecified; }
    private void ResetdmgRank() { dmgRankSpecified = false; }
    
    private int? _totalExp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"totalExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalExp
    {
      get { return _totalExp?? default(int); }
      set { _totalExp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalExpSpecified
    {
      get { return this._totalExp != null; }
      set { if (value == (this._totalExp== null)) this._totalExp = value ? this.totalExp : (int?)null; }
    }
    private bool ShouldSerializetotalExp() { return totalExpSpecified; }
    private void ResettotalExp() { totalExpSpecified = false; }
    
    private int? _wave;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"wave", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wave
    {
      get { return _wave?? default(int); }
      set { _wave = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool waveSpecified
    {
      get { return this._wave != null; }
      set { if (value == (this._wave== null)) this._wave = value ? this.wave : (int?)null; }
    }
    private bool ShouldSerializewave() { return waveSpecified; }
    private void Resetwave() { waveSpecified = false; }
    
    private int? _evaluation;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"evaluation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int evaluation
    {
      get { return _evaluation?? default(int); }
      set { _evaluation = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool evaluationSpecified
    {
      get { return this._evaluation != null; }
      set { if (value == (this._evaluation== null)) this._evaluation = value ? this.evaluation : (int?)null; }
    }
    private bool ShouldSerializeevaluation() { return evaluationSpecified; }
    private void Resetevaluation() { evaluationSpecified = false; }
    
    private uint? _canReliveTimes;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"canReliveTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint canReliveTimes
    {
      get { return _canReliveTimes?? default(uint); }
      set { _canReliveTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool canReliveTimesSpecified
    {
      get { return this._canReliveTimes != null; }
      set { if (value == (this._canReliveTimes== null)) this._canReliveTimes = value ? this.canReliveTimes : (uint?)null; }
    }
    private bool ShouldSerializecanReliveTimes() { return canReliveTimesSpecified; }
    private void ResetcanReliveTimes() { canReliveTimesSpecified = false; }
    
    private uint? _winflag;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"winflag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint winflag
    {
      get { return _winflag?? default(uint); }
      set { _winflag = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool winflagSpecified
    {
      get { return this._winflag != null; }
      set { if (value == (this._winflag== null)) this._winflag = value ? this.winflag : (uint?)null; }
    }
    private bool ShouldSerializewinflag() { return winflagSpecified; }
    private void Resetwinflag() { winflagSpecified = false; }
    
    private int? _totalCoin;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"totalCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalCoin
    {
      get { return _totalCoin?? default(int); }
      set { _totalCoin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalCoinSpecified
    {
      get { return this._totalCoin != null; }
      set { if (value == (this._totalCoin== null)) this._totalCoin = value ? this.totalCoin : (int?)null; }
    }
    private bool ShouldSerializetotalCoin() { return totalCoinSpecified; }
    private void ResettotalCoin() { totalCoinSpecified = false; }
    
    private int? _pannelShowCoin;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"pannelShowCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pannelShowCoin
    {
      get { return _pannelShowCoin?? default(int); }
      set { _pannelShowCoin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pannelShowCoinSpecified
    {
      get { return this._pannelShowCoin != null; }
      set { if (value == (this._pannelShowCoin== null)) this._pannelShowCoin = value ? this.pannelShowCoin : (int?)null; }
    }
    private bool ShouldSerializepannelShowCoin() { return pannelShowCoinSpecified; }
    private void ResetpannelShowCoin() { pannelShowCoinSpecified = false; }
    
    private int? _pannelShowExp;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"pannelShowExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pannelShowExp
    {
      get { return _pannelShowExp?? default(int); }
      set { _pannelShowExp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pannelShowExpSpecified
    {
      get { return this._pannelShowExp != null; }
      set { if (value == (this._pannelShowExp== null)) this._pannelShowExp = value ? this.pannelShowExp : (int?)null; }
    }
    private bool ShouldSerializepannelShowExp() { return pannelShowExpSpecified; }
    private void ResetpannelShowExp() { pannelShowExpSpecified = false; }
    
    private int? _pannelShowStar;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"pannelShowStar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pannelShowStar
    {
      get { return _pannelShowStar?? default(int); }
      set { _pannelShowStar = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool pannelShowStarSpecified
    {
      get { return this._pannelShowStar != null; }
      set { if (value == (this._pannelShowStar== null)) this._pannelShowStar = value ? this.pannelShowStar : (int?)null; }
    }
    private bool ShouldSerializepannelShowStar() { return pannelShowStarSpecified; }
    private void ResetpannelShowStar() { pannelShowStarSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.ActivityRewardItem> _panelShowItem = new global::System.Collections.Generic.List<Proto.ActivityRewardItem>();
    [global::ProtoBuf.ProtoMember(14, Name=@"panelShowItem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.ActivityRewardItem> panelShowItem
    {
      get { return _panelShowItem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceRewardReq")]
  public partial class CmdActivityInstanceRewardReq : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceRewardReq() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private int? _param;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"param", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int param
    {
      get { return _param?? default(int); }
      set { _param = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool paramSpecified
    {
      get { return this._param != null; }
      set { if (value == (this._param== null)) this._param = value ? this.param : (int?)null; }
    }
    private bool ShouldSerializeparam() { return paramSpecified; }
    private void Resetparam() { paramSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceRewardRes")]
  public partial class CmdActivityInstanceRewardRes : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceRewardRes() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private bool? _reward;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool reward
    {
      get { return _reward?? default(bool); }
      set { _reward = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rewardSpecified
    {
      get { return this._reward != null; }
      set { if (value == (this._reward== null)) this._reward = value ? this.reward : (bool?)null; }
    }
    private bool ShouldSerializereward() { return rewardSpecified; }
    private void Resetreward() { rewardSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.ActivityRewardItem> _rewarditem = new global::System.Collections.Generic.List<Proto.ActivityRewardItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rewarditem", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.ActivityRewardItem> rewarditem
    {
      get { return _rewarditem; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceRoleDeadByCaveReq")]
  public partial class CmdActivityInstanceRoleDeadByCaveReq : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceRoleDeadByCaveReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceSceneCaveInNtf")]
  public partial class CmdActivityInstanceSceneCaveInNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceSceneCaveInNtf() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private int? _caveCircle;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"caveCircle", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int caveCircle
    {
      get { return _caveCircle?? default(int); }
      set { _caveCircle = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool caveCircleSpecified
    {
      get { return this._caveCircle != null; }
      set { if (value == (this._caveCircle== null)) this._caveCircle = value ? this.caveCircle : (int?)null; }
    }
    private bool ShouldSerializecaveCircle() { return caveCircleSpecified; }
    private void ResetcaveCircle() { caveCircleSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceBuyTimesReq")]
  public partial class CmdActivityInstanceBuyTimesReq : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceBuyTimesReq() {}
    
    private uint? _activityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"activityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint activityId
    {
      get { return _activityId?? default(uint); }
      set { _activityId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool activityIdSpecified
    {
      get { return this._activityId != null; }
      set { if (value == (this._activityId== null)) this._activityId = value ? this.activityId : (uint?)null; }
    }
    private bool ShouldSerializeactivityId() { return activityIdSpecified; }
    private void ResetactivityId() { activityIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceBuyTimesRes")]
  public partial class CmdActivityInstanceBuyTimesRes : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceBuyTimesRes() {}
    
    private uint? _activityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"activityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint activityId
    {
      get { return _activityId?? default(uint); }
      set { _activityId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool activityIdSpecified
    {
      get { return this._activityId != null; }
      set { if (value == (this._activityId== null)) this._activityId = value ? this.activityId : (uint?)null; }
    }
    private bool ShouldSerializeactivityId() { return activityIdSpecified; }
    private void ResetactivityId() { activityIdSpecified = false; }
    
    private uint? _buyTimes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"buyTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint buyTimes
    {
      get { return _buyTimes?? default(uint); }
      set { _buyTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buyTimesSpecified
    {
      get { return this._buyTimes != null; }
      set { if (value == (this._buyTimes== null)) this._buyTimes = value ? this.buyTimes : (uint?)null; }
    }
    private bool ShouldSerializebuyTimes() { return buyTimesSpecified; }
    private void ResetbuyTimes() { buyTimesSpecified = false; }
    
    private uint? _lastBuyTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lastBuyTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastBuyTime
    {
      get { return _lastBuyTime?? default(uint); }
      set { _lastBuyTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastBuyTimeSpecified
    {
      get { return this._lastBuyTime != null; }
      set { if (value == (this._lastBuyTime== null)) this._lastBuyTime = value ? this.lastBuyTime : (uint?)null; }
    }
    private bool ShouldSerializelastBuyTime() { return lastBuyTimeSpecified; }
    private void ResetlastBuyTime() { lastBuyTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceDayTimesNtf")]
  public partial class CmdActivityInstanceDayTimesNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceDayTimesNtf() {}
    
    private int? _activityId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"activityId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int activityId
    {
      get { return _activityId?? default(int); }
      set { _activityId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool activityIdSpecified
    {
      get { return this._activityId != null; }
      set { if (value == (this._activityId== null)) this._activityId = value ? this.activityId : (int?)null; }
    }
    private bool ShouldSerializeactivityId() { return activityIdSpecified; }
    private void ResetactivityId() { activityIdSpecified = false; }
    
    private uint? _passTimes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"passTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint passTimes
    {
      get { return _passTimes?? default(uint); }
      set { _passTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool passTimesSpecified
    {
      get { return this._passTimes != null; }
      set { if (value == (this._passTimes== null)) this._passTimes = value ? this.passTimes : (uint?)null; }
    }
    private bool ShouldSerializepassTimes() { return passTimesSpecified; }
    private void ResetpassTimes() { passTimesSpecified = false; }
    
    private uint? _lastTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lastTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastTime
    {
      get { return _lastTime?? default(uint); }
      set { _lastTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastTimeSpecified
    {
      get { return this._lastTime != null; }
      set { if (value == (this._lastTime== null)) this._lastTime = value ? this.lastTime : (uint?)null; }
    }
    private bool ShouldSerializelastTime() { return lastTimeSpecified; }
    private void ResetlastTime() { lastTimeSpecified = false; }
    
    private uint? _buyTimes;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"buyTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint buyTimes
    {
      get { return _buyTimes?? default(uint); }
      set { _buyTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool buyTimesSpecified
    {
      get { return this._buyTimes != null; }
      set { if (value == (this._buyTimes== null)) this._buyTimes = value ? this.buyTimes : (uint?)null; }
    }
    private bool ShouldSerializebuyTimes() { return buyTimesSpecified; }
    private void ResetbuyTimes() { buyTimesSpecified = false; }
    
    private uint? _lastBuyTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"lastBuyTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastBuyTime
    {
      get { return _lastBuyTime?? default(uint); }
      set { _lastBuyTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastBuyTimeSpecified
    {
      get { return this._lastBuyTime != null; }
      set { if (value == (this._lastBuyTime== null)) this._lastBuyTime = value ? this.lastBuyTime : (uint?)null; }
    }
    private bool ShouldSerializelastBuyTime() { return lastBuyTimeSpecified; }
    private void ResetlastBuyTime() { lastBuyTimeSpecified = false; }
    
    private uint? _itemAddTimes;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"itemAddTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemAddTimes
    {
      get { return _itemAddTimes?? default(uint); }
      set { _itemAddTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemAddTimesSpecified
    {
      get { return this._itemAddTimes != null; }
      set { if (value == (this._itemAddTimes== null)) this._itemAddTimes = value ? this.itemAddTimes : (uint?)null; }
    }
    private bool ShouldSerializeitemAddTimes() { return itemAddTimesSpecified; }
    private void ResetitemAddTimes() { itemAddTimesSpecified = false; }
    
    private uint? _lastItemAddTime;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"lastItemAddTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastItemAddTime
    {
      get { return _lastItemAddTime?? default(uint); }
      set { _lastItemAddTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastItemAddTimeSpecified
    {
      get { return this._lastItemAddTime != null; }
      set { if (value == (this._lastItemAddTime== null)) this._lastItemAddTime = value ? this.lastItemAddTime : (uint?)null; }
    }
    private bool ShouldSerializelastItemAddTime() { return lastItemAddTimeSpecified; }
    private void ResetlastItemAddTime() { lastItemAddTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceTrainShopBuyItemReq")]
  public partial class CmdActivityInstanceTrainShopBuyItemReq : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceTrainShopBuyItemReq() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceTrainShopBuyItemRes")]
  public partial class CmdActivityInstanceTrainShopBuyItemRes : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceTrainShopBuyItemRes() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActivityTrainShopInfo")]
  public partial class ActivityTrainShopInfo : global::ProtoBuf.IExtensible
  {
    public ActivityTrainShopInfo() {}
    
    private uint? _itemid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemid
    {
      get { return _itemid?? default(uint); }
      set { _itemid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemidSpecified
    {
      get { return this._itemid != null; }
      set { if (value == (this._itemid== null)) this._itemid = value ? this.itemid : (uint?)null; }
    }
    private bool ShouldSerializeitemid() { return itemidSpecified; }
    private void Resetitemid() { itemidSpecified = false; }
    
    private uint? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count?? default(uint); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (uint?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceTrainInstanceDataNtf")]
  public partial class CmdActivityInstanceTrainInstanceDataNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceTrainInstanceDataNtf() {}
    
    private uint? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint infoId
    {
      get { return _infoId?? default(uint); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (uint?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private uint? _layer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"layer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint layer
    {
      get { return _layer?? default(uint); }
      set { _layer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool layerSpecified
    {
      get { return this._layer != null; }
      set { if (value == (this._layer== null)) this._layer = value ? this.layer : (uint?)null; }
    }
    private bool ShouldSerializelayer() { return layerSpecified; }
    private void Resetlayer() { layerSpecified = false; }
    
    private uint? _trainscore;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"trainscore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint trainscore
    {
      get { return _trainscore?? default(uint); }
      set { _trainscore = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool trainscoreSpecified
    {
      get { return this._trainscore != null; }
      set { if (value == (this._trainscore== null)) this._trainscore = value ? this.trainscore : (uint?)null; }
    }
    private bool ShouldSerializetrainscore() { return trainscoreSpecified; }
    private void Resettrainscore() { trainscoreSpecified = false; }
    
    private uint? _monsternum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"monsternum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint monsternum
    {
      get { return _monsternum?? default(uint); }
      set { _monsternum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool monsternumSpecified
    {
      get { return this._monsternum != null; }
      set { if (value == (this._monsternum== null)) this._monsternum = value ? this.monsternum : (uint?)null; }
    }
    private bool ShouldSerializemonsternum() { return monsternumSpecified; }
    private void Resetmonsternum() { monsternumSpecified = false; }
    
    private uint? _maxmonsternum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"maxmonsternum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxmonsternum
    {
      get { return _maxmonsternum?? default(uint); }
      set { _maxmonsternum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool maxmonsternumSpecified
    {
      get { return this._maxmonsternum != null; }
      set { if (value == (this._maxmonsternum== null)) this._maxmonsternum = value ? this.maxmonsternum : (uint?)null; }
    }
    private bool ShouldSerializemaxmonsternum() { return maxmonsternumSpecified; }
    private void Resetmaxmonsternum() { maxmonsternumSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.ActivityTrainShopInfo> _shopinfo = new global::System.Collections.Generic.List<Proto.ActivityTrainShopInfo>();
    [global::ProtoBuf.ProtoMember(6, Name=@"shopinfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.ActivityTrainShopInfo> shopinfo
    {
      get { return _shopinfo; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceTrainInstanceServerLayerNtf")]
  public partial class CmdActivityInstanceTrainInstanceServerLayerNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceTrainInstanceServerLayerNtf() {}
    
    private uint? _serverlayer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"serverlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint serverlayer
    {
      get { return _serverlayer?? default(uint); }
      set { _serverlayer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool serverlayerSpecified
    {
      get { return this._serverlayer != null; }
      set { if (value == (this._serverlayer== null)) this._serverlayer = value ? this.serverlayer : (uint?)null; }
    }
    private bool ShouldSerializeserverlayer() { return serverlayerSpecified; }
    private void Resetserverlayer() { serverlayerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstanceTrainInstanceMaxLayerNtf")]
  public partial class CmdActivityInstanceTrainInstanceMaxLayerNtf : global::ProtoBuf.IExtensible
  {
    public CmdActivityInstanceTrainInstanceMaxLayerNtf() {}
    
    private uint? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint infoId
    {
      get { return _infoId?? default(uint); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (uint?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private uint? _maxlayer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"maxlayer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint maxlayer
    {
      get { return _maxlayer?? default(uint); }
      set { _maxlayer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool maxlayerSpecified
    {
      get { return this._maxlayer != null; }
      set { if (value == (this._maxlayer== null)) this._maxlayer = value ? this.maxlayer : (uint?)null; }
    }
    private bool ShouldSerializemaxlayer() { return maxlayerSpecified; }
    private void Resetmaxlayer() { maxlayerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdActivityInstance")]
    public enum CmdActivityInstance
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_DataNtf", Value=2301)]
      CmdActivityInstance_DataNtf = 2301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_EnterReq", Value=2302)]
      CmdActivityInstance_EnterReq = 2302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_EnterRes", Value=2303)]
      CmdActivityInstance_EnterRes = 2303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_TargetNtf", Value=2304)]
      CmdActivityInstance_TargetNtf = 2304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_ScoreNtf", Value=2305)]
      CmdActivityInstance_ScoreNtf = 2305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_EndNtf", Value=2306)]
      CmdActivityInstance_EndNtf = 2306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_RewardReq", Value=2307)]
      CmdActivityInstance_RewardReq = 2307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_RewardRes", Value=2308)]
      CmdActivityInstance_RewardRes = 2308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_RoleDeadByCaveReq", Value=2309)]
      CmdActivityInstance_RoleDeadByCaveReq = 2309,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_SceneCaveInNtf", Value=2310)]
      CmdActivityInstance_SceneCaveInNtf = 2310,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_TotalExpNtf", Value=2311)]
      CmdActivityInstance_TotalExpNtf = 2311,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_EvaluationNtf", Value=2312)]
      CmdActivityInstance_EvaluationNtf = 2312,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_WaveNtf", Value=2313)]
      CmdActivityInstance_WaveNtf = 2313,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_BuyTimesReq", Value=2314)]
      CmdActivityInstance_BuyTimesReq = 2314,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_BuyTimesRes", Value=2315)]
      CmdActivityInstance_BuyTimesRes = 2315,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_CanReliveTimesNtf", Value=2316)]
      CmdActivityInstance_CanReliveTimesNtf = 2316,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_RoleInfoNtf", Value=2317)]
      CmdActivityInstance_RoleInfoNtf = 2317,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_MaxScoreNtf", Value=2318)]
      CmdActivityInstance_MaxScoreNtf = 2318,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_DayTimesNtf", Value=2319)]
      CmdActivityInstance_DayTimesNtf = 2319,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_RoleInfoRemoveNtf", Value=2320)]
      CmdActivityInstance_RoleInfoRemoveNtf = 2320,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_TrainShopBuyItemReq", Value=2321)]
      CmdActivityInstance_TrainShopBuyItemReq = 2321,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_TrainShopBuyItemRes", Value=2322)]
      CmdActivityInstance_TrainShopBuyItemRes = 2322,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_TrainInstanceDataNtf", Value=2323)]
      CmdActivityInstance_TrainInstanceDataNtf = 2323,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_TrainInstanceServerLayerNtf", Value=2324)]
      CmdActivityInstance_TrainInstanceServerLayerNtf = 2324,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdActivityInstance_TrainInstanceMaxLayerNtf", Value=2325)]
      CmdActivityInstance_TrainInstanceMaxLayerNtf = 2325
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorActivityInstance")]
    public enum ErrorActivityInstance
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_InfoNotFound", Value=2301)]
      ErrorActivityInstance_InfoNotFound = 2301,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_InstanceNotFound", Value=2302)]
      ErrorActivityInstance_InstanceNotFound = 2302,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_OpenTimeFmtError", Value=2303)]
      ErrorActivityInstance_OpenTimeFmtError = 2303,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_CheckOpenTimeFailed", Value=2304)]
      ErrorActivityInstance_CheckOpenTimeFailed = 2304,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_CheckLevelFailed", Value=2305)]
      ErrorActivityInstance_CheckLevelFailed = 2305,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_CheckDayTimesFailed", Value=2306)]
      ErrorActivityInstance_CheckDayTimesFailed = 2306,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_RoleHasInInstance", Value=2307)]
      ErrorActivityInstance_RoleHasInInstance = 2307,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_TargetNotFound", Value=2308)]
      ErrorActivityInstance_TargetNotFound = 2308,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_NoReward", Value=2309)]
      ErrorActivityInstance_NoReward = 2309,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_CheckTicketFailed", Value=2310)]
      ErrorActivityInstance_CheckTicketFailed = 2310,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_MapNotFound", Value=2311)]
      ErrorActivityInstance_MapNotFound = 2311,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_InTeamCannotIn", Value=2312)]
      ErrorActivityInstance_InTeamCannotIn = 2312,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_RewardNotGet", Value=2313)]
      ErrorActivityInstance_RewardNotGet = 2313,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_RoleIsDead", Value=2314)]
      ErrorActivityInstance_RoleIsDead = 2314,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_HasEnded", Value=2315)]
      ErrorActivityInstance_HasEnded = 2315,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_CannotDeadByCave", Value=2316)]
      ErrorActivityInstance_CannotDeadByCave = 2316,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_CannotBuyTimes", Value=2317)]
      ErrorActivityInstance_CannotBuyTimes = 2317,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_BuyTimesCheckFailed", Value=2318)]
      ErrorActivityInstance_BuyTimesCheckFailed = 2318,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_WeekDayLimit", Value=2319)]
      ErrorActivityInstance_WeekDayLimit = 2319,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_RedFortressUseItemCountLimit", Value=2320)]
      ErrorActivityInstance_RedFortressUseItemCountLimit = 2320,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_CanJoinTimesNotZero", Value=2321)]
      ErrorActivityInstance_CanJoinTimesNotZero = 2321,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_TrainShopIdError", Value=2322)]
      ErrorActivityInstance_TrainShopIdError = 2322,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_TrainShopScoreNOtEnough", Value=2323)]
      ErrorActivityInstance_TrainShopScoreNOtEnough = 2323,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorActivityInstance_TrainShopNotCanBuy", Value=2324)]
      ErrorActivityInstance_TrainShopNotCanBuy = 2324
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ActivityRewardParam")]
    public enum ActivityRewardParam
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ActivityRewardParam_None", Value=0)]
      ActivityRewardParam_None = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ActivityRewardParam_Double", Value=1)]
      ActivityRewardParam_Double = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ActivityRewardParam_Trible", Value=2)]
      ActivityRewardParam_Trible = 2
    }
  
}