//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: compose.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdComposeComposeReq")]
  public partial class CmdComposeComposeReq : global::ProtoBuf.IExtensible
  {
    public CmdComposeComposeReq() {}
    
    private uint? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint infoId
    {
      get { return _infoId?? default(uint); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (uint?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private bool? _useUnBoundOnly;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"useUnBoundOnly", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool useUnBoundOnly
    {
      get { return _useUnBoundOnly?? default(bool); }
      set { _useUnBoundOnly = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool useUnBoundOnlySpecified
    {
      get { return this._useUnBoundOnly != null; }
      set { if (value == (this._useUnBoundOnly== null)) this._useUnBoundOnly = value ? this.useUnBoundOnly : (bool?)null; }
    }
    private bool ShouldSerializeuseUnBoundOnly() { return useUnBoundOnlySpecified; }
    private void ResetuseUnBoundOnly() { useUnBoundOnlySpecified = false; }
    
    private int? _times;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int times
    {
      get { return _times?? default(int); }
      set { _times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timesSpecified
    {
      get { return this._times != null; }
      set { if (value == (this._times== null)) this._times = value ? this.times : (int?)null; }
    }
    private bool ShouldSerializetimes() { return timesSpecified; }
    private void Resettimes() { timesSpecified = false; }
    
    private int? _composeType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"composeType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int composeType
    {
      get { return _composeType?? default(int); }
      set { _composeType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool composeTypeSpecified
    {
      get { return this._composeType != null; }
      set { if (value == (this._composeType== null)) this._composeType = value ? this.composeType : (int?)null; }
    }
    private bool ShouldSerializecomposeType() { return composeTypeSpecified; }
    private void ResetcomposeType() { composeTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ComposeItem")]
  public partial class ComposeItem : global::ProtoBuf.IExtensible
  {
    public ComposeItem() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private uint? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count?? default(uint); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (uint?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdComposeComposeRes")]
  public partial class CmdComposeComposeRes : global::ProtoBuf.IExtensible
  {
    public CmdComposeComposeRes() {}
    
    private bool? _result;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool result
    {
      get { return _result?? default(bool); }
      set { _result = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resultSpecified
    {
      get { return this._result != null; }
      set { if (value == (this._result== null)) this._result = value ? this.result : (bool?)null; }
    }
    private bool ShouldSerializeresult() { return resultSpecified; }
    private void Resetresult() { resultSpecified = false; }
    
    private uint? _succId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"succId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint succId
    {
      get { return _succId?? default(uint); }
      set { _succId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool succIdSpecified
    {
      get { return this._succId != null; }
      set { if (value == (this._succId== null)) this._succId = value ? this.succId : (uint?)null; }
    }
    private bool ShouldSerializesuccId() { return succIdSpecified; }
    private void ResetsuccId() { succIdSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.ComposeItem> _items = new global::System.Collections.Generic.List<Proto.ComposeItem>();
    [global::ProtoBuf.ProtoMember(3, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.ComposeItem> items
    {
      get { return _items; }
    }
  
    private uint? _times;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint times
    {
      get { return _times?? default(uint); }
      set { _times = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool timesSpecified
    {
      get { return this._times != null; }
      set { if (value == (this._times== null)) this._times = value ? this.times : (uint?)null; }
    }
    private bool ShouldSerializetimes() { return timesSpecified; }
    private void Resettimes() { timesSpecified = false; }
    
    private uint? _succTimes;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"succTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint succTimes
    {
      get { return _succTimes?? default(uint); }
      set { _succTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool succTimesSpecified
    {
      get { return this._succTimes != null; }
      set { if (value == (this._succTimes== null)) this._succTimes = value ? this.succTimes : (uint?)null; }
    }
    private bool ShouldSerializesuccTimes() { return succTimesSpecified; }
    private void ResetsuccTimes() { succTimesSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdCompose")]
    public enum CmdCompose
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdCompose_ComposeReq", Value=2701)]
      CmdCompose_ComposeReq = 2701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdCompose_ComposeRes", Value=2702)]
      CmdCompose_ComposeRes = 2702
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorCompose")]
    public enum ErrorCompose
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Compose_ComposeNotFound", Value=2701)]
      Error_Compose_ComposeNotFound = 2701,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Compose_MaterialNotEnough", Value=2702)]
      Error_Compose_MaterialNotEnough = 2702,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Compose_CoinNotEnough", Value=2703)]
      Error_Compose_CoinNotEnough = 2703,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Compose_ComposeTimesLimit", Value=2704)]
      Error_Compose_ComposeTimesLimit = 2704
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ComposeType")]
    public enum ComposeType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ComposeType_All", Value=1)]
      ComposeType_All = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ComposeType_OnlyBind", Value=2)]
      ComposeType_OnlyBind = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ComposeType_OnlyUnBind", Value=3)]
      ComposeType_OnlyUnBind = 3
    }
  
}