//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: elomatch.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdEloMatchInfoReq")]
  public partial class CmdEloMatchInfoReq : global::ProtoBuf.IExtensible
  {
    public CmdEloMatchInfoReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdEloMatchInfoRes")]
  public partial class CmdEloMatchInfoRes : global::ProtoBuf.IExtensible
  {
    public CmdEloMatchInfoRes() {}
    
    private uint? _elovalue;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"elovalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint elovalue
    {
      get { return _elovalue?? default(uint); }
      set { _elovalue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool elovalueSpecified
    {
      get { return this._elovalue != null; }
      set { if (value == (this._elovalue== null)) this._elovalue = value ? this.elovalue : (uint?)null; }
    }
    private bool ShouldSerializeelovalue() { return elovalueSpecified; }
    private void Resetelovalue() { elovalueSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<uint> _gradinginfo = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"gradinginfo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> gradinginfo
    {
      get { return _gradinginfo; }
    }
  
    private uint? _todayRewardInfo;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"todayRewardInfo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint todayRewardInfo
    {
      get { return _todayRewardInfo?? default(uint); }
      set { _todayRewardInfo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool todayRewardInfoSpecified
    {
      get { return this._todayRewardInfo != null; }
      set { if (value == (this._todayRewardInfo== null)) this._todayRewardInfo = value ? this.todayRewardInfo : (uint?)null; }
    }
    private bool ShouldSerializetodayRewardInfo() { return todayRewardInfoSpecified; }
    private void ResettodayRewardInfo() { todayRewardInfoSpecified = false; }
    
    private uint? _horseCoin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"horseCoin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint horseCoin
    {
      get { return _horseCoin?? default(uint); }
      set { _horseCoin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool horseCoinSpecified
    {
      get { return this._horseCoin != null; }
      set { if (value == (this._horseCoin== null)) this._horseCoin = value ? this.horseCoin : (uint?)null; }
    }
    private bool ShouldSerializehorseCoin() { return horseCoinSpecified; }
    private void ResethorseCoin() { horseCoinSpecified = false; }
    
    private uint? _todayJoinTime;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"todayJoinTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint todayJoinTime
    {
      get { return _todayJoinTime?? default(uint); }
      set { _todayJoinTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool todayJoinTimeSpecified
    {
      get { return this._todayJoinTime != null; }
      set { if (value == (this._todayJoinTime== null)) this._todayJoinTime = value ? this.todayJoinTime : (uint?)null; }
    }
    private bool ShouldSerializetodayJoinTime() { return todayJoinTimeSpecified; }
    private void ResettodayJoinTime() { todayJoinTimeSpecified = false; }
    
    private uint? _lastSeasonEloValue;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"lastSeasonEloValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastSeasonEloValue
    {
      get { return _lastSeasonEloValue?? default(uint); }
      set { _lastSeasonEloValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastSeasonEloValueSpecified
    {
      get { return this._lastSeasonEloValue != null; }
      set { if (value == (this._lastSeasonEloValue== null)) this._lastSeasonEloValue = value ? this.lastSeasonEloValue : (uint?)null; }
    }
    private bool ShouldSerializelastSeasonEloValue() { return lastSeasonEloValueSpecified; }
    private void ResetlastSeasonEloValue() { lastSeasonEloValueSpecified = false; }
    
    private bool? _bGetLastSeasonReward;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"bGetLastSeasonReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bGetLastSeasonReward
    {
      get { return _bGetLastSeasonReward?? (bool)true; }
      set { _bGetLastSeasonReward = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bGetLastSeasonRewardSpecified
    {
      get { return this._bGetLastSeasonReward != null; }
      set { if (value == (this._bGetLastSeasonReward== null)) this._bGetLastSeasonReward = value ? this.bGetLastSeasonReward : (bool?)null; }
    }
    private bool ShouldSerializebGetLastSeasonReward() { return bGetLastSeasonRewardSpecified; }
    private void ResetbGetLastSeasonReward() { bGetLastSeasonRewardSpecified = false; }
    
    private uint? _dataLastTime;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"dataLastTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint dataLastTime
    {
      get { return _dataLastTime?? default(uint); }
      set { _dataLastTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool dataLastTimeSpecified
    {
      get { return this._dataLastTime != null; }
      set { if (value == (this._dataLastTime== null)) this._dataLastTime = value ? this.dataLastTime : (uint?)null; }
    }
    private bool ShouldSerializedataLastTime() { return dataLastTimeSpecified; }
    private void ResetdataLastTime() { dataLastTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdEloMatchGetTodayRewardReq")]
  public partial class CmdEloMatchGetTodayRewardReq : global::ProtoBuf.IExtensible
  {
    public CmdEloMatchGetTodayRewardReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdEloMatchGetTodayRewardRes")]
  public partial class CmdEloMatchGetTodayRewardRes : global::ProtoBuf.IExtensible
  {
    public CmdEloMatchGetTodayRewardRes() {}
    
    private bool? _bOk;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bOk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bOk
    {
      get { return _bOk?? default(bool); }
      set { _bOk = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bOkSpecified
    {
      get { return this._bOk != null; }
      set { if (value == (this._bOk== null)) this._bOk = value ? this.bOk : (bool?)null; }
    }
    private bool ShouldSerializebOk() { return bOkSpecified; }
    private void ResetbOk() { bOkSpecified = false; }
    
    private uint? _todayRewardInfo;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"todayRewardInfo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint todayRewardInfo
    {
      get { return _todayRewardInfo?? default(uint); }
      set { _todayRewardInfo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool todayRewardInfoSpecified
    {
      get { return this._todayRewardInfo != null; }
      set { if (value == (this._todayRewardInfo== null)) this._todayRewardInfo = value ? this.todayRewardInfo : (uint?)null; }
    }
    private bool ShouldSerializetodayRewardInfo() { return todayRewardInfoSpecified; }
    private void ResettodayRewardInfo() { todayRewardInfoSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdEloMatchGetSeasonRewardReq")]
  public partial class CmdEloMatchGetSeasonRewardReq : global::ProtoBuf.IExtensible
  {
    public CmdEloMatchGetSeasonRewardReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdEloMatchGetSeasonRewardRes")]
  public partial class CmdEloMatchGetSeasonRewardRes : global::ProtoBuf.IExtensible
  {
    public CmdEloMatchGetSeasonRewardRes() {}
    
    private bool? _bOk;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bOk", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bOk
    {
      get { return _bOk?? default(bool); }
      set { _bOk = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bOkSpecified
    {
      get { return this._bOk != null; }
      set { if (value == (this._bOk== null)) this._bOk = value ? this.bOk : (bool?)null; }
    }
    private bool ShouldSerializebOk() { return bOkSpecified; }
    private void ResetbOk() { bOkSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdEloMatch")]
    public enum CmdEloMatch
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdEloMatch_InfoReq", Value=8500)]
      CmdEloMatch_InfoReq = 8500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdEloMatch_InfoRes", Value=8501)]
      CmdEloMatch_InfoRes = 8501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdEloMatch_GetTodayRewardReq", Value=8502)]
      CmdEloMatch_GetTodayRewardReq = 8502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdEloMatch_GetTodayRewardRes", Value=8503)]
      CmdEloMatch_GetTodayRewardRes = 8503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdEloMatch_GetSeasonRewardReq", Value=8504)]
      CmdEloMatch_GetSeasonRewardReq = 8504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdEloMatch_GetSeasonRewardRes", Value=8505)]
      CmdEloMatch_GetSeasonRewardRes = 8505
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorEloMatch")]
    public enum ErrorEloMatch
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorEloMatch_AlreadyGet", Value=8500)]
      ErrorEloMatch_AlreadyGet = 8500,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorEloMatch_CannotGet", Value=8501)]
      ErrorEloMatch_CannotGet = 8501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorEloMatch_RankInfoError", Value=8502)]
      ErrorEloMatch_RankInfoError = 8502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorEloMatch_ConstInfoError", Value=8503)]
      ErrorEloMatch_ConstInfoError = 8503
    }
  
}