//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: medicine.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMedicineDataNtf")]
  public partial class CmdMedicineDataNtf : global::ProtoBuf.IExtensible
  {
    public CmdMedicineDataNtf() {}
    
    private int? _hpPool;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hpPool", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hpPool
    {
      get { return _hpPool?? default(int); }
      set { _hpPool = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hpPoolSpecified
    {
      get { return this._hpPool != null; }
      set { if (value == (this._hpPool== null)) this._hpPool = value ? this.hpPool : (int?)null; }
    }
    private bool ShouldSerializehpPool() { return hpPoolSpecified; }
    private void ResethpPool() { hpPoolSpecified = false; }
    
    private int? _mpPool;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mpPool", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mpPool
    {
      get { return _mpPool?? default(int); }
      set { _mpPool = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mpPoolSpecified
    {
      get { return this._mpPool != null; }
      set { if (value == (this._mpPool== null)) this._mpPool = value ? this.mpPool : (int?)null; }
    }
    private bool ShouldSerializempPool() { return mpPoolSpecified; }
    private void ResetmpPool() { mpPoolSpecified = false; }
    
    private int? _firstAid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"firstAid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int firstAid
    {
      get { return _firstAid?? default(int); }
      set { _firstAid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool firstAidSpecified
    {
      get { return this._firstAid != null; }
      set { if (value == (this._firstAid== null)) this._firstAid = value ? this.firstAid : (int?)null; }
    }
    private bool ShouldSerializefirstAid() { return firstAidSpecified; }
    private void ResetfirstAid() { firstAidSpecified = false; }
    
    private int? _hpPer;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"hpPer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hpPer
    {
      get { return _hpPer?? default(int); }
      set { _hpPer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hpPerSpecified
    {
      get { return this._hpPer != null; }
      set { if (value == (this._hpPer== null)) this._hpPer = value ? this.hpPer : (int?)null; }
    }
    private bool ShouldSerializehpPer() { return hpPerSpecified; }
    private void ResethpPer() { hpPerSpecified = false; }
    
    private int? _mpPer;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"mpPer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mpPer
    {
      get { return _mpPer?? default(int); }
      set { _mpPer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mpPerSpecified
    {
      get { return this._mpPer != null; }
      set { if (value == (this._mpPer== null)) this._mpPer = value ? this.mpPer : (int?)null; }
    }
    private bool ShouldSerializempPer() { return mpPerSpecified; }
    private void ResetmpPer() { mpPerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMedicineFirstAidReq")]
  public partial class CmdMedicineFirstAidReq : global::ProtoBuf.IExtensible
  {
    public CmdMedicineFirstAidReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMedicineFirstAidRes")]
  public partial class CmdMedicineFirstAidRes : global::ProtoBuf.IExtensible
  {
    public CmdMedicineFirstAidRes() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMedicineSetPerReq")]
  public partial class CmdMedicineSetPerReq : global::ProtoBuf.IExtensible
  {
    public CmdMedicineSetPerReq() {}
    
    private int? _hpPer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hpPer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hpPer
    {
      get { return _hpPer?? default(int); }
      set { _hpPer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hpPerSpecified
    {
      get { return this._hpPer != null; }
      set { if (value == (this._hpPer== null)) this._hpPer = value ? this.hpPer : (int?)null; }
    }
    private bool ShouldSerializehpPer() { return hpPerSpecified; }
    private void ResethpPer() { hpPerSpecified = false; }
    
    private int? _mpPer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mpPer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mpPer
    {
      get { return _mpPer?? default(int); }
      set { _mpPer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mpPerSpecified
    {
      get { return this._mpPer != null; }
      set { if (value == (this._mpPer== null)) this._mpPer = value ? this.mpPer : (int?)null; }
    }
    private bool ShouldSerializempPer() { return mpPerSpecified; }
    private void ResetmpPer() { mpPerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMedicineSetPerRes")]
  public partial class CmdMedicineSetPerRes : global::ProtoBuf.IExtensible
  {
    public CmdMedicineSetPerRes() {}
    
    private int? _hpPer;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hpPer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hpPer
    {
      get { return _hpPer?? default(int); }
      set { _hpPer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hpPerSpecified
    {
      get { return this._hpPer != null; }
      set { if (value == (this._hpPer== null)) this._hpPer = value ? this.hpPer : (int?)null; }
    }
    private bool ShouldSerializehpPer() { return hpPerSpecified; }
    private void ResethpPer() { hpPerSpecified = false; }
    
    private int? _mpPer;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mpPer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mpPer
    {
      get { return _mpPer?? default(int); }
      set { _mpPer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mpPerSpecified
    {
      get { return this._mpPer != null; }
      set { if (value == (this._mpPer== null)) this._mpPer = value ? this.mpPer : (int?)null; }
    }
    private bool ShouldSerializempPer() { return mpPerSpecified; }
    private void ResetmpPer() { mpPerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMedicineFillNtf")]
  public partial class CmdMedicineFillNtf : global::ProtoBuf.IExtensible
  {
    public CmdMedicineFillNtf() {}
    
    private int? _hpPoolAdd;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hpPoolAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int hpPoolAdd
    {
      get { return _hpPoolAdd?? default(int); }
      set { _hpPoolAdd = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hpPoolAddSpecified
    {
      get { return this._hpPoolAdd != null; }
      set { if (value == (this._hpPoolAdd== null)) this._hpPoolAdd = value ? this.hpPoolAdd : (int?)null; }
    }
    private bool ShouldSerializehpPoolAdd() { return hpPoolAddSpecified; }
    private void ResethpPoolAdd() { hpPoolAddSpecified = false; }
    
    private int? _mpPoolAdd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"mpPoolAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mpPoolAdd
    {
      get { return _mpPoolAdd?? default(int); }
      set { _mpPoolAdd = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mpPoolAddSpecified
    {
      get { return this._mpPoolAdd != null; }
      set { if (value == (this._mpPoolAdd== null)) this._mpPoolAdd = value ? this.mpPoolAdd : (int?)null; }
    }
    private bool ShouldSerializempPoolAdd() { return mpPoolAddSpecified; }
    private void ResetmpPoolAdd() { mpPoolAddSpecified = false; }
    
    private int? _firstAidAdd;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"firstAidAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int firstAidAdd
    {
      get { return _firstAidAdd?? default(int); }
      set { _firstAidAdd = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool firstAidAddSpecified
    {
      get { return this._firstAidAdd != null; }
      set { if (value == (this._firstAidAdd== null)) this._firstAidAdd = value ? this.firstAidAdd : (int?)null; }
    }
    private bool ShouldSerializefirstAidAdd() { return firstAidAddSpecified; }
    private void ResetfirstAidAdd() { firstAidAddSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMedicinePoolBuyReq")]
  public partial class CmdMedicinePoolBuyReq : global::ProtoBuf.IExtensible
  {
    public CmdMedicinePoolBuyReq() {}
    
    private bool? _hpPoolBuy;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"hpPoolBuy", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool hpPoolBuy
    {
      get { return _hpPoolBuy?? default(bool); }
      set { _hpPoolBuy = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hpPoolBuySpecified
    {
      get { return this._hpPoolBuy != null; }
      set { if (value == (this._hpPoolBuy== null)) this._hpPoolBuy = value ? this.hpPoolBuy : (bool?)null; }
    }
    private bool ShouldSerializehpPoolBuy() { return hpPoolBuySpecified; }
    private void ResethpPoolBuy() { hpPoolBuySpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdMedicine")]
    public enum CmdMedicine
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMedicine_DataNtf", Value=2401)]
      CmdMedicine_DataNtf = 2401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMedicine_FirstAidReq", Value=2402)]
      CmdMedicine_FirstAidReq = 2402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMedicine_FirstAidRes", Value=2403)]
      CmdMedicine_FirstAidRes = 2403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMedicine_SetPerReq", Value=2404)]
      CmdMedicine_SetPerReq = 2404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMedicine_SetPerRes", Value=2405)]
      CmdMedicine_SetPerRes = 2405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMedicine_FillNtf", Value=2406)]
      CmdMedicine_FillNtf = 2406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMedicine_PoolBuyReq", Value=2407)]
      CmdMedicine_PoolBuyReq = 2407
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorMedicine")]
    public enum ErrorMedicine
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMedicine_LevelInfoNotFound", Value=2401)]
      ErrorMedicine_LevelInfoNotFound = 2401,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMedicine_ConstInfoNotFound", Value=2402)]
      ErrorMedicine_ConstInfoNotFound = 2402,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMedicine_FristAidCDFailed", Value=2403)]
      ErrorMedicine_FristAidCDFailed = 2403,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMedicine_RoleHpFailed", Value=2404)]
      ErrorMedicine_RoleHpFailed = 2404,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMedicine_HpPoolIsFull", Value=2405)]
      ErrorMedicine_HpPoolIsFull = 2405,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMedicine_MpPoolIsFull", Value=2406)]
      ErrorMedicine_MpPoolIsFull = 2406,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMedicine_FirstAidIsFull", Value=2407)]
      ErrorMedicine_FirstAidIsFull = 2407,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMedicine_FirstAidHpFailed", Value=2408)]
      ErrorMedicine_FirstAidHpFailed = 2408,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMedicine_FirstAidDisableInThisMap", Value=2409)]
      ErrorMedicine_FirstAidDisableInThisMap = 2409,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMedicine_PoolBuyConfError", Value=2410)]
      ErrorMedicine_PoolBuyConfError = 2410
    }
  
}