//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: meleeInstance.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MeleeRewardItem")]
  public partial class MeleeRewardItem : global::ProtoBuf.IExtensible
  {
    public MeleeRewardItem() {}
    
    private int? _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId?? default(int); }
      set { _itemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIdSpecified
    {
      get { return this._itemId != null; }
      set { if (value == (this._itemId== null)) this._itemId = value ? this.itemId : (int?)null; }
    }
    private bool ShouldSerializeitemId() { return itemIdSpecified; }
    private void ResetitemId() { itemIdSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMeleeInstanceDataNtf")]
  public partial class CmdMeleeInstanceDataNtf : global::ProtoBuf.IExtensible
  {
    public CmdMeleeInstanceDataNtf() {}
    
    private uint? _lastJoinTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"lastJoinTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastJoinTime
    {
      get { return _lastJoinTime?? default(uint); }
      set { _lastJoinTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastJoinTimeSpecified
    {
      get { return this._lastJoinTime != null; }
      set { if (value == (this._lastJoinTime== null)) this._lastJoinTime = value ? this.lastJoinTime : (uint?)null; }
    }
    private bool ShouldSerializelastJoinTime() { return lastJoinTimeSpecified; }
    private void ResetlastJoinTime() { lastJoinTimeSpecified = false; }
    
    private Proto.MeleeRewardItem _killReward = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"killReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.MeleeRewardItem killReward
    {
      get { return _killReward; }
      set { _killReward = value; }
    }
    private Proto.MeleeRewardItem _surviveReward = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"surviveReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.MeleeRewardItem surviveReward
    {
      get { return _surviveReward; }
      set { _surviveReward = value; }
    }
    private Proto.MeleeRewardItem _successReward = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"successReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.MeleeRewardItem successReward
    {
      get { return _successReward; }
      set { _successReward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMeleeInstanceEnterNtf")]
  public partial class CmdMeleeInstanceEnterNtf : global::ProtoBuf.IExtensible
  {
    public CmdMeleeInstanceEnterNtf() {}
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMeleeInstanceKillNtf")]
  public partial class CmdMeleeInstanceKillNtf : global::ProtoBuf.IExtensible
  {
    public CmdMeleeInstanceKillNtf() {}
    
    private ulong? _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId?? default(ulong); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return this._roleId != null; }
      set { if (value == (this._roleId== null)) this._roleId = value ? this.roleId : (ulong?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private int? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int num
    {
      get { return _num?? default(int); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (int?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private int? _occupation;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"occupation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occupation
    {
      get { return _occupation?? default(int); }
      set { _occupation = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupationSpecified
    {
      get { return this._occupation != null; }
      set { if (value == (this._occupation== null)) this._occupation = value ? this.occupation : (int?)null; }
    }
    private bool ShouldSerializeoccupation() { return occupationSpecified; }
    private void Resetoccupation() { occupationSpecified = false; }
    
    private byte[] _roleName;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] roleName
    {
      get { return _roleName?? null; }
      set { _roleName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleNameSpecified
    {
      get { return this._roleName != null; }
      set { if (value == (this._roleName== null)) this._roleName = value ? this.roleName : (byte[])null; }
    }
    private bool ShouldSerializeroleName() { return roleNameSpecified; }
    private void ResetroleName() { roleNameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMeleeInstanceEndNtf")]
  public partial class CmdMeleeInstanceEndNtf : global::ProtoBuf.IExtensible
  {
    public CmdMeleeInstanceEndNtf() {}
    
    private Proto.MeleeRewardItem _killReward = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"killReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.MeleeRewardItem killReward
    {
      get { return _killReward; }
      set { _killReward = value; }
    }
    private Proto.MeleeRewardItem _surviveReward = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"surviveReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.MeleeRewardItem surviveReward
    {
      get { return _surviveReward; }
      set { _surviveReward = value; }
    }
    private Proto.MeleeRewardItem _successReward = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"successReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.MeleeRewardItem successReward
    {
      get { return _successReward; }
      set { _successReward = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMeleeInstanceRewardGetReq")]
  public partial class CmdMeleeInstanceRewardGetReq : global::ProtoBuf.IExtensible
  {
    public CmdMeleeInstanceRewardGetReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdMeleeInstanceRewardGetRes")]
  public partial class CmdMeleeInstanceRewardGetRes : global::ProtoBuf.IExtensible
  {
    public CmdMeleeInstanceRewardGetRes() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdMeleeInstance")]
    public enum CmdMeleeInstance
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMeleeInstance_DataNtf", Value=5901)]
      CmdMeleeInstance_DataNtf = 5901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMeleeInstance_EnterNtf", Value=5902)]
      CmdMeleeInstance_EnterNtf = 5902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMeleeInstance_KillNtf", Value=5903)]
      CmdMeleeInstance_KillNtf = 5903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMeleeInstance_EndNtf", Value=5904)]
      CmdMeleeInstance_EndNtf = 5904,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMeleeInstance_RewardGetReq", Value=5905)]
      CmdMeleeInstance_RewardGetReq = 5905,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdMeleeInstance_RewardGetRes", Value=5906)]
      CmdMeleeInstance_RewardGetRes = 5906
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorMeleeInstance")]
    public enum ErrorMeleeInstance
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMeleeInstance_LevelFail", Value=5901)]
      ErrorMeleeInstance_LevelFail = 5901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMeleeInstance_NotInActiveTime", Value=5902)]
      ErrorMeleeInstance_NotInActiveTime = 5902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMeleeInstance_InfoNotFound", Value=5903)]
      ErrorMeleeInstance_InfoNotFound = 5903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMeleeInstance_DayTimesFail", Value=5904)]
      ErrorMeleeInstance_DayTimesFail = 5904,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorMeleeInstance_RewardFail", Value=5905)]
      ErrorMeleeInstance_RewardFail = 5905
    }
  
}