
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: nextDayReward.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdNextDayRewardDataNtf")]
  public partial class CmdNextDayRewardDataNtf : global::ProtoBuf.IExtensible
  {
    public CmdNextDayRewardDataNtf() {}
    
    private uint? _openTime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"openTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint openTime
    {
      get { return _openTime?? default(uint); }
      set { _openTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool openTimeSpecified
    {
      get { return this._openTime != null; }
      set { if (value == (this._openTime== null)) this._openTime = value ? this.openTime : (uint?)null; }
    }
    private bool ShouldSerializeopenTime() { return openTimeSpecified; }
    private void ResetopenTime() { openTimeSpecified = false; }
    
    private bool? _hasGotReward;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"hasGotReward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool hasGotReward
    {
      get { return _hasGotReward?? default(bool); }
      set { _hasGotReward = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool hasGotRewardSpecified
    {
      get { return this._hasGotReward != null; }
      set { if (value == (this._hasGotReward== null)) this._hasGotReward = value ? this.hasGotReward : (bool?)null; }
    }
    private bool ShouldSerializehasGotReward() { return hasGotRewardSpecified; }
    private void ResethasGotReward() { hasGotRewardSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdNextDayRewardGetReq")]
  public partial class CmdNextDayRewardGetReq : global::ProtoBuf.IExtensible
  {
    public CmdNextDayRewardGetReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdNextDayReward")]
    public enum CmdNextDayReward
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdNextDayReward_DataNtf", Value=6001)]
      CmdNextDayReward_DataNtf = 6001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdNextDayReward_GetReq", Value=6002)]
      CmdNextDayReward_GetReq = 6002
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorNextDayReward")]
    public enum ErrorNextDayReward
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorNextDayReward_NotOpen", Value=6001)]
      ErrorNextDayReward_NotOpen = 6001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorNextDayReward_HasGotReward", Value=6002)]
      ErrorNextDayReward_HasGotReward = 6002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorNextDayReward_NotGotTime", Value=6003)]
      ErrorNextDayReward_NotGotTime = 6003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorNextDayReward_ConfInvalid", Value=6004)]
      ErrorNextDayReward_ConfInvalid = 6004
    }
  
}