//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pandora.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraNormalUseReq")]
  public partial class CmdPandoraNormalUseReq : global::ProtoBuf.IExtensible
  {
    public CmdPandoraNormalUseReq() {}
    
    private uint? _bagPos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bagPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bagPos
    {
      get { return _bagPos?? default(uint); }
      set { _bagPos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bagPosSpecified
    {
      get { return this._bagPos != null; }
      set { if (value == (this._bagPos== null)) this._bagPos = value ? this.bagPos : (uint?)null; }
    }
    private bool ShouldSerializebagPos() { return bagPosSpecified; }
    private void ResetbagPos() { bagPosSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraNormalUseRes")]
  public partial class CmdPandoraNormalUseRes : global::ProtoBuf.IExtensible
  {
    public CmdPandoraNormalUseRes() {}
    
    private uint? _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId?? default(uint); }
      set { _mapId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mapIdSpecified
    {
      get { return this._mapId != null; }
      set { if (value == (this._mapId== null)) this._mapId = value ? this.mapId : (uint?)null; }
    }
    private bool ShouldSerializemapId() { return mapIdSpecified; }
    private void ResetmapId() { mapIdSpecified = false; }
    
    private uint? _posX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint posX
    {
      get { return _posX?? default(uint); }
      set { _posX = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posXSpecified
    {
      get { return this._posX != null; }
      set { if (value == (this._posX== null)) this._posX = value ? this.posX : (uint?)null; }
    }
    private bool ShouldSerializeposX() { return posXSpecified; }
    private void ResetposX() { posXSpecified = false; }
    
    private uint? _posY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint posY
    {
      get { return _posY?? default(uint); }
      set { _posY = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posYSpecified
    {
      get { return this._posY != null; }
      set { if (value == (this._posY== null)) this._posY = value ? this.posY : (uint?)null; }
    }
    private bool ShouldSerializeposY() { return posYSpecified; }
    private void ResetposY() { posYSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraNormalStartReq")]
  public partial class CmdPandoraNormalStartReq : global::ProtoBuf.IExtensible
  {
    public CmdPandoraNormalStartReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraNormalStartRes")]
  public partial class CmdPandoraNormalStartRes : global::ProtoBuf.IExtensible
  {
    public CmdPandoraNormalStartRes() {}
    
    private uint? _eventId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"eventId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint eventId
    {
      get { return _eventId?? default(uint); }
      set { _eventId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool eventIdSpecified
    {
      get { return this._eventId != null; }
      set { if (value == (this._eventId== null)) this._eventId = value ? this.eventId : (uint?)null; }
    }
    private bool ShouldSerializeeventId() { return eventIdSpecified; }
    private void ReseteventId() { eventIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraSpecialUseReq")]
  public partial class CmdPandoraSpecialUseReq : global::ProtoBuf.IExtensible
  {
    public CmdPandoraSpecialUseReq() {}
    
    private uint? _bagPos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bagPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bagPos
    {
      get { return _bagPos?? default(uint); }
      set { _bagPos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bagPosSpecified
    {
      get { return this._bagPos != null; }
      set { if (value == (this._bagPos== null)) this._bagPos = value ? this.bagPos : (uint?)null; }
    }
    private bool ShouldSerializebagPos() { return bagPosSpecified; }
    private void ResetbagPos() { bagPosSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraSpecialUseRes")]
  public partial class CmdPandoraSpecialUseRes : global::ProtoBuf.IExtensible
  {
    public CmdPandoraSpecialUseRes() {}
    
    private uint? _mapId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mapId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint mapId
    {
      get { return _mapId?? default(uint); }
      set { _mapId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool mapIdSpecified
    {
      get { return this._mapId != null; }
      set { if (value == (this._mapId== null)) this._mapId = value ? this.mapId : (uint?)null; }
    }
    private bool ShouldSerializemapId() { return mapIdSpecified; }
    private void ResetmapId() { mapIdSpecified = false; }
    
    private uint? _posX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint posX
    {
      get { return _posX?? default(uint); }
      set { _posX = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posXSpecified
    {
      get { return this._posX != null; }
      set { if (value == (this._posX== null)) this._posX = value ? this.posX : (uint?)null; }
    }
    private bool ShouldSerializeposX() { return posXSpecified; }
    private void ResetposX() { posXSpecified = false; }
    
    private uint? _posY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint posY
    {
      get { return _posY?? default(uint); }
      set { _posY = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posYSpecified
    {
      get { return this._posY != null; }
      set { if (value == (this._posY== null)) this._posY = value ? this.posY : (uint?)null; }
    }
    private bool ShouldSerializeposY() { return posYSpecified; }
    private void ResetposY() { posYSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraSpecialStartReq")]
  public partial class CmdPandoraSpecialStartReq : global::ProtoBuf.IExtensible
  {
    public CmdPandoraSpecialStartReq() {}
    
    private uint? _bagPos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"bagPos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint bagPos
    {
      get { return _bagPos?? default(uint); }
      set { _bagPos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bagPosSpecified
    {
      get { return this._bagPos != null; }
      set { if (value == (this._bagPos== null)) this._bagPos = value ? this.bagPos : (uint?)null; }
    }
    private bool ShouldSerializebagPos() { return bagPosSpecified; }
    private void ResetbagPos() { bagPosSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PandoraSpecialItems")]
  public partial class PandoraSpecialItems : global::ProtoBuf.IExtensible
  {
    public PandoraSpecialItems() {}
    
    private uint? _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type?? default(uint); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (uint?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private uint? _itemId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemId
    {
      get { return _itemId?? default(uint); }
      set { _itemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIdSpecified
    {
      get { return this._itemId != null; }
      set { if (value == (this._itemId== null)) this._itemId = value ? this.itemId : (uint?)null; }
    }
    private bool ShouldSerializeitemId() { return itemIdSpecified; }
    private void ResetitemId() { itemIdSpecified = false; }
    
    private uint? _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint count
    {
      get { return _count?? default(uint); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (uint?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraSpecialStartRes")]
  public partial class CmdPandoraSpecialStartRes : global::ProtoBuf.IExtensible
  {
    public CmdPandoraSpecialStartRes() {}
    
    private readonly global::System.Collections.Generic.List<Proto.PandoraSpecialItems> _items = new global::System.Collections.Generic.List<Proto.PandoraSpecialItems>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.PandoraSpecialItems> items
    {
      get { return _items; }
    }
  
    private uint? _randRet;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"randRet", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint randRet
    {
      get { return _randRet?? default(uint); }
      set { _randRet = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool randRetSpecified
    {
      get { return this._randRet != null; }
      set { if (value == (this._randRet== null)) this._randRet = value ? this.randRet : (uint?)null; }
    }
    private bool ShouldSerializerandRet() { return randRetSpecified; }
    private void ResetrandRet() { randRetSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraTakeAwardReq")]
  public partial class CmdPandoraTakeAwardReq : global::ProtoBuf.IExtensible
  {
    public CmdPandoraTakeAwardReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraInstanceInviteReq")]
  public partial class CmdPandoraInstanceInviteReq : global::ProtoBuf.IExtensible
  {
    public CmdPandoraInstanceInviteReq() {}
    
    private uint? _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint type
    {
      get { return _type?? default(uint); }
      set { _type = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool typeSpecified
    {
      get { return this._type != null; }
      set { if (value == (this._type== null)) this._type = value ? this.type : (uint?)null; }
    }
    private bool ShouldSerializetype() { return typeSpecified; }
    private void Resettype() { typeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraInstanceInviteNtf")]
  public partial class CmdPandoraInstanceInviteNtf : global::ProtoBuf.IExtensible
  {
    public CmdPandoraInstanceInviteNtf() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name?? null; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (byte[])null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private uint? _instanceId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"instanceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint instanceId
    {
      get { return _instanceId?? default(uint); }
      set { _instanceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool instanceIdSpecified
    {
      get { return this._instanceId != null; }
      set { if (value == (this._instanceId== null)) this._instanceId = value ? this.instanceId : (uint?)null; }
    }
    private bool ShouldSerializeinstanceId() { return instanceIdSpecified; }
    private void ResetinstanceId() { instanceIdSpecified = false; }
    
    private ulong? _roleId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId?? default(ulong); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return this._roleId != null; }
      set { if (value == (this._roleId== null)) this._roleId = value ? this.roleId : (ulong?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraResponseInviteReq")]
  public partial class CmdPandoraResponseInviteReq : global::ProtoBuf.IExtensible
  {
    public CmdPandoraResponseInviteReq() {}
    
    private uint? _res;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"res", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint res
    {
      get { return _res?? default(uint); }
      set { _res = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resSpecified
    {
      get { return this._res != null; }
      set { if (value == (this._res== null)) this._res = value ? this.res : (uint?)null; }
    }
    private bool ShouldSerializeres() { return resSpecified; }
    private void Resetres() { resSpecified = false; }
    
    private ulong? _roleId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId?? default(ulong); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return this._roleId != null; }
      set { if (value == (this._roleId== null)) this._roleId = value ? this.roleId : (ulong?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraTriggerNpcReq")]
  public partial class CmdPandoraTriggerNpcReq : global::ProtoBuf.IExtensible
  {
    public CmdPandoraTriggerNpcReq() {}
    
    private uint? _npcId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"npcId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint npcId
    {
      get { return _npcId?? default(uint); }
      set { _npcId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool npcIdSpecified
    {
      get { return this._npcId != null; }
      set { if (value == (this._npcId== null)) this._npcId = value ? this.npcId : (uint?)null; }
    }
    private bool ShouldSerializenpcId() { return npcIdSpecified; }
    private void ResetnpcId() { npcIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraInstanceEnterNtf")]
  public partial class CmdPandoraInstanceEnterNtf : global::ProtoBuf.IExtensible
  {
    public CmdPandoraInstanceEnterNtf() {}
    
    private uint? _instanceId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"instanceId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint instanceId
    {
      get { return _instanceId?? default(uint); }
      set { _instanceId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool instanceIdSpecified
    {
      get { return this._instanceId != null; }
      set { if (value == (this._instanceId== null)) this._instanceId = value ? this.instanceId : (uint?)null; }
    }
    private bool ShouldSerializeinstanceId() { return instanceIdSpecified; }
    private void ResetinstanceId() { instanceIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraGuestEnterNtf")]
  public partial class CmdPandoraGuestEnterNtf : global::ProtoBuf.IExtensible
  {
    public CmdPandoraGuestEnterNtf() {}
    
    private uint? _index;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"index", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint index
    {
      get { return _index?? default(uint); }
      set { _index = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool indexSpecified
    {
      get { return this._index != null; }
      set { if (value == (this._index== null)) this._index = value ? this.index : (uint?)null; }
    }
    private bool ShouldSerializeindex() { return indexSpecified; }
    private void Resetindex() { indexSpecified = false; }
    
    private uint? _occ;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"occ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint occ
    {
      get { return _occ?? default(uint); }
      set { _occ = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occSpecified
    {
      get { return this._occ != null; }
      set { if (value == (this._occ== null)) this._occ = value ? this.occ : (uint?)null; }
    }
    private bool ShouldSerializeocc() { return occSpecified; }
    private void Resetocc() { occSpecified = false; }
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name?? null; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (byte[])null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private uint? _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level?? default(uint); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (uint?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraInstantStartInstance")]
  public partial class CmdPandoraInstantStartInstance : global::ProtoBuf.IExtensible
  {
    public CmdPandoraInstantStartInstance() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraResponseInviteRes")]
  public partial class CmdPandoraResponseInviteRes : global::ProtoBuf.IExtensible
  {
    public CmdPandoraResponseInviteRes() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraLastTimeRewardNtf")]
  public partial class CmdPandoraLastTimeRewardNtf : global::ProtoBuf.IExtensible
  {
    public CmdPandoraLastTimeRewardNtf() {}
    
    private uint? _coin;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint coin
    {
      get { return _coin?? default(uint); }
      set { _coin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool coinSpecified
    {
      get { return this._coin != null; }
      set { if (value == (this._coin== null)) this._coin = value ? this.coin : (uint?)null; }
    }
    private bool ShouldSerializecoin() { return coinSpecified; }
    private void Resetcoin() { coinSpecified = false; }
    
    private uint? _exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp
    {
      get { return _exp?? default(uint); }
      set { _exp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool expSpecified
    {
      get { return this._exp != null; }
      set { if (value == (this._exp== null)) this._exp = value ? this.exp : (uint?)null; }
    }
    private bool ShouldSerializeexp() { return expSpecified; }
    private void Resetexp() { expSpecified = false; }
    
    private uint? _itemId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemId
    {
      get { return _itemId?? default(uint); }
      set { _itemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIdSpecified
    {
      get { return this._itemId != null; }
      set { if (value == (this._itemId== null)) this._itemId = value ? this.itemId : (uint?)null; }
    }
    private bool ShouldSerializeitemId() { return itemIdSpecified; }
    private void ResetitemId() { itemIdSpecified = false; }
    
    private uint? _itemNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"itemNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint itemNum
    {
      get { return _itemNum?? default(uint); }
      set { _itemNum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemNumSpecified
    {
      get { return this._itemNum != null; }
      set { if (value == (this._itemNum== null)) this._itemNum = value ? this.itemNum : (uint?)null; }
    }
    private bool ShouldSerializeitemNum() { return itemNumSpecified; }
    private void ResetitemNum() { itemNumSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPandoraRoleExitNtf")]
  public partial class CmdPandoraRoleExitNtf : global::ProtoBuf.IExtensible
  {
    public CmdPandoraRoleExitNtf() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name?? null; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (byte[])null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdPandora")]
    public enum CmdPandora
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_NormalUseReq", Value=4801)]
      CmdPandora_NormalUseReq = 4801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_NormalUseRes", Value=4802)]
      CmdPandora_NormalUseRes = 4802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_NormalStartReq", Value=4803)]
      CmdPandora_NormalStartReq = 4803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_NormalStartRes", Value=4804)]
      CmdPandora_NormalStartRes = 4804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_SpecialUseReq", Value=4810)]
      CmdPandora_SpecialUseReq = 4810,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_SpecialUseRes", Value=4811)]
      CmdPandora_SpecialUseRes = 4811,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_SpecialStartReq", Value=4812)]
      CmdPandora_SpecialStartReq = 4812,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_SpecialStartRes", Value=4813)]
      CmdPandora_SpecialStartRes = 4813,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_TakeAwardReq", Value=4814)]
      CmdPandora_TakeAwardReq = 4814,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_InstanceInviteReq", Value=4820)]
      CmdPandora_InstanceInviteReq = 4820,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_InstanceInviteNtf", Value=4821)]
      CmdPandora_InstanceInviteNtf = 4821,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_ResponseInviteReq", Value=4822)]
      CmdPandora_ResponseInviteReq = 4822,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_TriggerNpcReq", Value=4823)]
      CmdPandora_TriggerNpcReq = 4823,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_InstanceEnterNtf", Value=4824)]
      CmdPandora_InstanceEnterNtf = 4824,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_GuestEnterNtf", Value=4825)]
      CmdPandora_GuestEnterNtf = 4825,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_InstantStartInstance", Value=4826)]
      CmdPandora_InstantStartInstance = 4826,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_ResponseInviteRes", Value=4827)]
      CmdPandora_ResponseInviteRes = 4827,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_LastTimeRewardNtf", Value=4828)]
      CmdPandora_LastTimeRewardNtf = 4828,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPandora_RoleExitNtf", Value=4829)]
      CmdPandora_RoleExitNtf = 4829
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorPandora")]
    public enum ErrorPandora
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_ItemNull", Value=4801)]
      ErrorPandora_ItemNull = 4801,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_EventInfoNone", Value=4802)]
      ErrorPandora_EventInfoNone = 4802,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_InstanceRoleFull", Value=4803)]
      ErrorPandora_InstanceRoleFull = 4803,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_InstanceBeInvitedFull", Value=4804)]
      ErrorPandora_InstanceBeInvitedFull = 4804,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_InstanceInfoNotFound", Value=4805)]
      ErrorPandora_InstanceInfoNotFound = 4805,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_NotInInstance", Value=4806)]
      ErrorPandora_NotInInstance = 4806,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_NpcEscape", Value=4807)]
      ErrorPandora_NpcEscape = 4807,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_InstanceIsNull", Value=4808)]
      ErrorPandora_InstanceIsNull = 4808,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_HostRoleOffLine", Value=4809)]
      ErrorPandora_HostRoleOffLine = 4809,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_InstanceHasEnd", Value=4810)]
      ErrorPandora_InstanceHasEnd = 4810,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_MapNotFound", Value=4811)]
      ErrorPandora_MapNotFound = 4811,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_InviteTimeLimit", Value=4812)]
      ErrorPandora_InviteTimeLimit = 4812,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPandora_NotGoToDes", Value=4813)]
      ErrorPandora_NotGoToDes = 4813
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PandoraInvieType")]
    public enum PandoraInvieType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"PandoraInvieType_Friend", Value=1)]
      PandoraInvieType_Friend = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PandoraInvieType_Guild", Value=2)]
      PandoraInvieType_Guild = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PandoraInvieType_World", Value=3)]
      PandoraInvieType_World = 3
    }
  
}