//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: pvpInstance.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVPInstance")]
  public partial class PVPInstance : global::ProtoBuf.IExtensible
  {
    public PVPInstance() {}
    
    private int? _insInfoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"insInfoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int insInfoId
    {
      get { return _insInfoId?? default(int); }
      set { _insInfoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool insInfoIdSpecified
    {
      get { return this._insInfoId != null; }
      set { if (value == (this._insInfoId== null)) this._insInfoId = value ? this.insInfoId : (int?)null; }
    }
    private bool ShouldSerializeinsInfoId() { return insInfoIdSpecified; }
    private void ResetinsInfoId() { insInfoIdSpecified = false; }
    
    private uint? _lastJoinTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lastJoinTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastJoinTime
    {
      get { return _lastJoinTime?? default(uint); }
      set { _lastJoinTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastJoinTimeSpecified
    {
      get { return this._lastJoinTime != null; }
      set { if (value == (this._lastJoinTime== null)) this._lastJoinTime = value ? this.lastJoinTime : (uint?)null; }
    }
    private bool ShouldSerializelastJoinTime() { return lastJoinTimeSpecified; }
    private void ResetlastJoinTime() { lastJoinTimeSpecified = false; }
    
    private uint? _joinTimes;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"joinTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint joinTimes
    {
      get { return _joinTimes?? default(uint); }
      set { _joinTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool joinTimesSpecified
    {
      get { return this._joinTimes != null; }
      set { if (value == (this._joinTimes== null)) this._joinTimes = value ? this.joinTimes : (uint?)null; }
    }
    private bool ShouldSerializejoinTimes() { return joinTimesSpecified; }
    private void ResetjoinTimes() { joinTimesSpecified = false; }
    
    private uint? _lastUseItemTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"lastUseItemTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastUseItemTime
    {
      get { return _lastUseItemTime?? default(uint); }
      set { _lastUseItemTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastUseItemTimeSpecified
    {
      get { return this._lastUseItemTime != null; }
      set { if (value == (this._lastUseItemTime== null)) this._lastUseItemTime = value ? this.lastUseItemTime : (uint?)null; }
    }
    private bool ShouldSerializelastUseItemTime() { return lastUseItemTimeSpecified; }
    private void ResetlastUseItemTime() { lastUseItemTimeSpecified = false; }
    
    private uint? _useItemCount;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"useItemCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint useItemCount
    {
      get { return _useItemCount?? default(uint); }
      set { _useItemCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool useItemCountSpecified
    {
      get { return this._useItemCount != null; }
      set { if (value == (this._useItemCount== null)) this._useItemCount = value ? this.useItemCount : (uint?)null; }
    }
    private bool ShouldSerializeuseItemCount() { return useItemCountSpecified; }
    private void ResetuseItemCount() { useItemCountSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstanceDataNtf")]
  public partial class CmdPVPInstanceDataNtf : global::ProtoBuf.IExtensible
  {
    public CmdPVPInstanceDataNtf() {}
    
    private readonly global::System.Collections.Generic.List<Proto.PVPInstance> _pvpInsList = new global::System.Collections.Generic.List<Proto.PVPInstance>();
    [global::ProtoBuf.ProtoMember(1, Name=@"pvpInsList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.PVPInstance> pvpInsList
    {
      get { return _pvpInsList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVPRoleInfo")]
  public partial class PVPRoleInfo : global::ProtoBuf.IExtensible
  {
    public PVPRoleInfo() {}
    
    private ulong? _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId?? default(ulong); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return this._roleId != null; }
      set { if (value == (this._roleId== null)) this._roleId = value ? this.roleId : (ulong?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private uint? _occupation;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"occupation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint occupation
    {
      get { return _occupation?? default(uint); }
      set { _occupation = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupationSpecified
    {
      get { return this._occupation != null; }
      set { if (value == (this._occupation== null)) this._occupation = value ? this.occupation : (uint?)null; }
    }
    private bool ShouldSerializeoccupation() { return occupationSpecified; }
    private void Resetoccupation() { occupationSpecified = false; }
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name?? null; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (byte[])null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private int? _camp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp
    {
      get { return _camp?? default(int); }
      set { _camp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool campSpecified
    {
      get { return this._camp != null; }
      set { if (value == (this._camp== null)) this._camp = value ? this.camp : (int?)null; }
    }
    private bool ShouldSerializecamp() { return campSpecified; }
    private void Resetcamp() { campSpecified = false; }
    
    private int? _score;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int score
    {
      get { return _score?? default(int); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (int?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private int? _killCount;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"killCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int killCount
    {
      get { return _killCount?? default(int); }
      set { _killCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool killCountSpecified
    {
      get { return this._killCount != null; }
      set { if (value == (this._killCount== null)) this._killCount = value ? this.killCount : (int?)null; }
    }
    private bool ShouldSerializekillCount() { return killCountSpecified; }
    private void ResetkillCount() { killCountSpecified = false; }
    
    private int? _comKillCount;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"comKillCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int comKillCount
    {
      get { return _comKillCount?? default(int); }
      set { _comKillCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool comKillCountSpecified
    {
      get { return this._comKillCount != null; }
      set { if (value == (this._comKillCount== null)) this._comKillCount = value ? this.comKillCount : (int?)null; }
    }
    private bool ShouldSerializecomKillCount() { return comKillCountSpecified; }
    private void ResetcomKillCount() { comKillCountSpecified = false; }
    
    private int? _maxComKillCount;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"maxComKillCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxComKillCount
    {
      get { return _maxComKillCount?? default(int); }
      set { _maxComKillCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool maxComKillCountSpecified
    {
      get { return this._maxComKillCount != null; }
      set { if (value == (this._maxComKillCount== null)) this._maxComKillCount = value ? this.maxComKillCount : (int?)null; }
    }
    private bool ShouldSerializemaxComKillCount() { return maxComKillCountSpecified; }
    private void ResetmaxComKillCount() { maxComKillCountSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVPItemInfo")]
  public partial class PVPItemInfo : global::ProtoBuf.IExtensible
  {
    public PVPItemInfo() {}
    
    private uint? _infoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint infoId
    {
      get { return _infoId?? default(uint); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (uint?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private uint? _num;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"num", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint num
    {
      get { return _num?? default(uint); }
      set { _num = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numSpecified
    {
      get { return this._num != null; }
      set { if (value == (this._num== null)) this._num = value ? this.num : (uint?)null; }
    }
    private bool ShouldSerializenum() { return numSpecified; }
    private void Resetnum() { numSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstanceEnterNtf")]
  public partial class CmdPVPInstanceEnterNtf : global::ProtoBuf.IExtensible
  {
    public CmdPVPInstanceEnterNtf() {}
    
    private Proto.PVPInstance _pvpIns = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pvpIns", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.PVPInstance pvpIns
    {
      get { return _pvpIns; }
      set { _pvpIns = value; }
    }
    private uint? _createTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"createTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint createTime
    {
      get { return _createTime?? default(uint); }
      set { _createTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool createTimeSpecified
    {
      get { return this._createTime != null; }
      set { if (value == (this._createTime== null)) this._createTime = value ? this.createTime : (uint?)null; }
    }
    private bool ShouldSerializecreateTime() { return createTimeSpecified; }
    private void ResetcreateTime() { createTimeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.PVPRoleInfo> _roleInfos = new global::System.Collections.Generic.List<Proto.PVPRoleInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"roleInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.PVPRoleInfo> roleInfos
    {
      get { return _roleInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstanceEndNtf")]
  public partial class CmdPVPInstanceEndNtf : global::ProtoBuf.IExtensible
  {
    public CmdPVPInstanceEndNtf() {}
    
    private int? _insInfoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"insInfoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int insInfoId
    {
      get { return _insInfoId?? default(int); }
      set { _insInfoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool insInfoIdSpecified
    {
      get { return this._insInfoId != null; }
      set { if (value == (this._insInfoId== null)) this._insInfoId = value ? this.insInfoId : (int?)null; }
    }
    private bool ShouldSerializeinsInfoId() { return insInfoIdSpecified; }
    private void ResetinsInfoId() { insInfoIdSpecified = false; }
    
    private int? _result;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int result
    {
      get { return _result?? default(int); }
      set { _result = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resultSpecified
    {
      get { return this._result != null; }
      set { if (value == (this._result== null)) this._result = value ? this.result : (int?)null; }
    }
    private bool ShouldSerializeresult() { return resultSpecified; }
    private void Resetresult() { resultSpecified = false; }
    
    private uint? _money;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint money
    {
      get { return _money?? default(uint); }
      set { _money = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool moneySpecified
    {
      get { return this._money != null; }
      set { if (value == (this._money== null)) this._money = value ? this.money : (uint?)null; }
    }
    private bool ShouldSerializemoney() { return moneySpecified; }
    private void Resetmoney() { moneySpecified = false; }
    
    private uint? _exp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp
    {
      get { return _exp?? default(uint); }
      set { _exp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool expSpecified
    {
      get { return this._exp != null; }
      set { if (value == (this._exp== null)) this._exp = value ? this.exp : (uint?)null; }
    }
    private bool ShouldSerializeexp() { return expSpecified; }
    private void Resetexp() { expSpecified = false; }
    
    private uint? _scorePrizeId;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"scorePrizeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint scorePrizeId
    {
      get { return _scorePrizeId?? default(uint); }
      set { _scorePrizeId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scorePrizeIdSpecified
    {
      get { return this._scorePrizeId != null; }
      set { if (value == (this._scorePrizeId== null)) this._scorePrizeId = value ? this.scorePrizeId : (uint?)null; }
    }
    private bool ShouldSerializescorePrizeId() { return scorePrizeIdSpecified; }
    private void ResetscorePrizeId() { scorePrizeIdSpecified = false; }
    
    private uint? _succPrizeId;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"succPrizeId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint succPrizeId
    {
      get { return _succPrizeId?? default(uint); }
      set { _succPrizeId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool succPrizeIdSpecified
    {
      get { return this._succPrizeId != null; }
      set { if (value == (this._succPrizeId== null)) this._succPrizeId = value ? this.succPrizeId : (uint?)null; }
    }
    private bool ShouldSerializesuccPrizeId() { return succPrizeIdSpecified; }
    private void ResetsuccPrizeId() { succPrizeIdSpecified = false; }
    
    private uint? _star;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star?? default(uint); }
      set { _star = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool starSpecified
    {
      get { return this._star != null; }
      set { if (value == (this._star== null)) this._star = value ? this.star : (uint?)null; }
    }
    private bool ShouldSerializestar() { return starSpecified; }
    private void Resetstar() { starSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.PVPItemInfo> _items = new global::System.Collections.Generic.List<Proto.PVPItemInfo>();
    [global::ProtoBuf.ProtoMember(8, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.PVPItemInfo> items
    {
      get { return _items; }
    }
  
    private readonly global::System.Collections.Generic.List<Proto.PVPItemInfo> _rankItems = new global::System.Collections.Generic.List<Proto.PVPItemInfo>();
    [global::ProtoBuf.ProtoMember(9, Name=@"rankItems", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.PVPItemInfo> rankItems
    {
      get { return _rankItems; }
    }
  
    private int? _oldEloValue;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"oldEloValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int oldEloValue
    {
      get { return _oldEloValue?? default(int); }
      set { _oldEloValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool oldEloValueSpecified
    {
      get { return this._oldEloValue != null; }
      set { if (value == (this._oldEloValue== null)) this._oldEloValue = value ? this.oldEloValue : (int?)null; }
    }
    private bool ShouldSerializeoldEloValue() { return oldEloValueSpecified; }
    private void ResetoldEloValue() { oldEloValueSpecified = false; }
    
    private int? _changeElo;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"changeElo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int changeElo
    {
      get { return _changeElo?? default(int); }
      set { _changeElo = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool changeEloSpecified
    {
      get { return this._changeElo != null; }
      set { if (value == (this._changeElo== null)) this._changeElo = value ? this.changeElo : (int?)null; }
    }
    private bool ShouldSerializechangeElo() { return changeEloSpecified; }
    private void ResetchangeElo() { changeEloSpecified = false; }
    
    private bool? _bgrading;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"bgrading", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool bgrading
    {
      get { return _bgrading?? default(bool); }
      set { _bgrading = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool bgradingSpecified
    {
      get { return this._bgrading != null; }
      set { if (value == (this._bgrading== null)) this._bgrading = value ? this.bgrading : (bool?)null; }
    }
    private bool ShouldSerializebgrading() { return bgradingSpecified; }
    private void Resetbgrading() { bgradingSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstanceUpdateRoleInfoNtf")]
  public partial class CmdPVPInstanceUpdateRoleInfoNtf : global::ProtoBuf.IExtensible
  {
    public CmdPVPInstanceUpdateRoleInfoNtf() {}
    
    private readonly global::System.Collections.Generic.List<Proto.PVPRoleInfo> _roles = new global::System.Collections.Generic.List<Proto.PVPRoleInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roles", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.PVPRoleInfo> roles
    {
      get { return _roles; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstanceUpdateTargetNtf")]
  public partial class CmdPVPInstanceUpdateTargetNtf : global::ProtoBuf.IExtensible
  {
    public CmdPVPInstanceUpdateTargetNtf() {}
    
    private readonly global::System.Collections.Generic.List<uint> _infos = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"infos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> infos
    {
      get { return _infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstanceGainPrizeReq")]
  public partial class CmdPVPInstanceGainPrizeReq : global::ProtoBuf.IExtensible
  {
    public CmdPVPInstanceGainPrizeReq() {}
    
    private int? _insInfoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"insInfoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int insInfoId
    {
      get { return _insInfoId?? default(int); }
      set { _insInfoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool insInfoIdSpecified
    {
      get { return this._insInfoId != null; }
      set { if (value == (this._insInfoId== null)) this._insInfoId = value ? this.insInfoId : (int?)null; }
    }
    private bool ShouldSerializeinsInfoId() { return insInfoIdSpecified; }
    private void ResetinsInfoId() { insInfoIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstanceGainPrizeRes")]
  public partial class CmdPVPInstanceGainPrizeRes : global::ProtoBuf.IExtensible
  {
    public CmdPVPInstanceGainPrizeRes() {}
    
    private uint? _money;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"money", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint money
    {
      get { return _money?? default(uint); }
      set { _money = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool moneySpecified
    {
      get { return this._money != null; }
      set { if (value == (this._money== null)) this._money = value ? this.money : (uint?)null; }
    }
    private bool ShouldSerializemoney() { return moneySpecified; }
    private void Resetmoney() { moneySpecified = false; }
    
    private uint? _exp;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"exp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint exp
    {
      get { return _exp?? default(uint); }
      set { _exp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool expSpecified
    {
      get { return this._exp != null; }
      set { if (value == (this._exp== null)) this._exp = value ? this.exp : (uint?)null; }
    }
    private bool ShouldSerializeexp() { return expSpecified; }
    private void Resetexp() { expSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.PVPItemInfo> _items = new global::System.Collections.Generic.List<Proto.PVPItemInfo>();
    [global::ProtoBuf.ProtoMember(3, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.PVPItemInfo> items
    {
      get { return _items; }
    }
  
    private uint? _star;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star?? default(uint); }
      set { _star = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool starSpecified
    {
      get { return this._star != null; }
      set { if (value == (this._star== null)) this._star = value ? this.star : (uint?)null; }
    }
    private bool ShouldSerializestar() { return starSpecified; }
    private void Resetstar() { starSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstanceBossInfoReq")]
  public partial class CmdPVPInstanceBossInfoReq : global::ProtoBuf.IExtensible
  {
    public CmdPVPInstanceBossInfoReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVPInsBossInfo")]
  public partial class PVPInsBossInfo : global::ProtoBuf.IExtensible
  {
    public PVPInsBossInfo() {}
    
    private uint? _monId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"monId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint monId
    {
      get { return _monId?? default(uint); }
      set { _monId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool monIdSpecified
    {
      get { return this._monId != null; }
      set { if (value == (this._monId== null)) this._monId = value ? this.monId : (uint?)null; }
    }
    private bool ShouldSerializemonId() { return monIdSpecified; }
    private void ResetmonId() { monIdSpecified = false; }
    
    private int? _monInfoId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"monInfoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int monInfoId
    {
      get { return _monInfoId?? default(int); }
      set { _monInfoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool monInfoIdSpecified
    {
      get { return this._monInfoId != null; }
      set { if (value == (this._monInfoId== null)) this._monInfoId = value ? this.monInfoId : (int?)null; }
    }
    private bool ShouldSerializemonInfoId() { return monInfoIdSpecified; }
    private void ResetmonInfoId() { monInfoIdSpecified = false; }
    
    private int? _curHp;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"curHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curHp
    {
      get { return _curHp?? default(int); }
      set { _curHp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curHpSpecified
    {
      get { return this._curHp != null; }
      set { if (value == (this._curHp== null)) this._curHp = value ? this.curHp : (int?)null; }
    }
    private bool ShouldSerializecurHp() { return curHpSpecified; }
    private void ResetcurHp() { curHpSpecified = false; }
    
    private int? _maxHp;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"maxHp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int maxHp
    {
      get { return _maxHp?? default(int); }
      set { _maxHp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool maxHpSpecified
    {
      get { return this._maxHp != null; }
      set { if (value == (this._maxHp== null)) this._maxHp = value ? this.maxHp : (int?)null; }
    }
    private bool ShouldSerializemaxHp() { return maxHpSpecified; }
    private void ResetmaxHp() { maxHpSpecified = false; }
    
    private uint? _posX;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint posX
    {
      get { return _posX?? default(uint); }
      set { _posX = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posXSpecified
    {
      get { return this._posX != null; }
      set { if (value == (this._posX== null)) this._posX = value ? this.posX : (uint?)null; }
    }
    private bool ShouldSerializeposX() { return posXSpecified; }
    private void ResetposX() { posXSpecified = false; }
    
    private uint? _posY;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint posY
    {
      get { return _posY?? default(uint); }
      set { _posY = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posYSpecified
    {
      get { return this._posY != null; }
      set { if (value == (this._posY== null)) this._posY = value ? this.posY : (uint?)null; }
    }
    private bool ShouldSerializeposY() { return posYSpecified; }
    private void ResetposY() { posYSpecified = false; }
    
    private int? _camp;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"camp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int camp
    {
      get { return _camp?? default(int); }
      set { _camp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool campSpecified
    {
      get { return this._camp != null; }
      set { if (value == (this._camp== null)) this._camp = value ? this.camp : (int?)null; }
    }
    private bool ShouldSerializecamp() { return campSpecified; }
    private void Resetcamp() { campSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstanceBossInfoRes")]
  public partial class CmdPVPInstanceBossInfoRes : global::ProtoBuf.IExtensible
  {
    public CmdPVPInstanceBossInfoRes() {}
    
    private readonly global::System.Collections.Generic.List<Proto.PVPInsBossInfo> _monInfos = new global::System.Collections.Generic.List<Proto.PVPInsBossInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"monInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.PVPInsBossInfo> monInfos
    {
      get { return _monInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PVPInsResAreaInfo")]
  public partial class PVPInsResAreaInfo : global::ProtoBuf.IExtensible
  {
    public PVPInsResAreaInfo() {}
    
    private int? _resAreaId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"resAreaId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int resAreaId
    {
      get { return _resAreaId?? default(int); }
      set { _resAreaId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resAreaIdSpecified
    {
      get { return this._resAreaId != null; }
      set { if (value == (this._resAreaId== null)) this._resAreaId = value ? this.resAreaId : (int?)null; }
    }
    private bool ShouldSerializeresAreaId() { return resAreaIdSpecified; }
    private void ResetresAreaId() { resAreaIdSpecified = false; }
    
    private float? _posX;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"posX", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posX
    {
      get { return _posX?? default(float); }
      set { _posX = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posXSpecified
    {
      get { return this._posX != null; }
      set { if (value == (this._posX== null)) this._posX = value ? this.posX : (float?)null; }
    }
    private bool ShouldSerializeposX() { return posXSpecified; }
    private void ResetposX() { posXSpecified = false; }
    
    private float? _posY;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"posY", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float posY
    {
      get { return _posY?? default(float); }
      set { _posY = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posYSpecified
    {
      get { return this._posY != null; }
      set { if (value == (this._posY== null)) this._posY = value ? this.posY : (float?)null; }
    }
    private bool ShouldSerializeposY() { return posYSpecified; }
    private void ResetposY() { posYSpecified = false; }
    
    private float? _radius;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"radius", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public float radius
    {
      get { return _radius?? default(float); }
      set { _radius = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool radiusSpecified
    {
      get { return this._radius != null; }
      set { if (value == (this._radius== null)) this._radius = value ? this.radius : (float?)null; }
    }
    private bool ShouldSerializeradius() { return radiusSpecified; }
    private void Resetradius() { radiusSpecified = false; }
    
    private int? _belongCamp;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"belongCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int belongCamp
    {
      get { return _belongCamp?? default(int); }
      set { _belongCamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool belongCampSpecified
    {
      get { return this._belongCamp != null; }
      set { if (value == (this._belongCamp== null)) this._belongCamp = value ? this.belongCamp : (int?)null; }
    }
    private bool ShouldSerializebelongCamp() { return belongCampSpecified; }
    private void ResetbelongCamp() { belongCampSpecified = false; }
    
    private int? _processCamp;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"processCamp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int processCamp
    {
      get { return _processCamp?? default(int); }
      set { _processCamp = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool processCampSpecified
    {
      get { return this._processCamp != null; }
      set { if (value == (this._processCamp== null)) this._processCamp = value ? this.processCamp : (int?)null; }
    }
    private bool ShouldSerializeprocessCamp() { return processCampSpecified; }
    private void ResetprocessCamp() { processCampSpecified = false; }
    
    private int? _curProcess;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"curProcess", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int curProcess
    {
      get { return _curProcess?? default(int); }
      set { _curProcess = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curProcessSpecified
    {
      get { return this._curProcess != null; }
      set { if (value == (this._curProcess== null)) this._curProcess = value ? this.curProcess : (int?)null; }
    }
    private bool ShouldSerializecurProcess() { return curProcessSpecified; }
    private void ResetcurProcess() { curProcessSpecified = false; }
    
    private int? _totalProcess;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"totalProcess", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int totalProcess
    {
      get { return _totalProcess?? default(int); }
      set { _totalProcess = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool totalProcessSpecified
    {
      get { return this._totalProcess != null; }
      set { if (value == (this._totalProcess== null)) this._totalProcess = value ? this.totalProcess : (int?)null; }
    }
    private bool ShouldSerializetotalProcess() { return totalProcessSpecified; }
    private void ResettotalProcess() { totalProcessSpecified = false; }
    
    private bool? _isBreak;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isBreak", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isBreak
    {
      get { return _isBreak?? default(bool); }
      set { _isBreak = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool isBreakSpecified
    {
      get { return this._isBreak != null; }
      set { if (value == (this._isBreak== null)) this._isBreak = value ? this.isBreak : (bool?)null; }
    }
    private bool ShouldSerializeisBreak() { return isBreakSpecified; }
    private void ResetisBreak() { isBreakSpecified = false; }
    
    private uint? _areaMonsterId;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"areaMonsterId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint areaMonsterId
    {
      get { return _areaMonsterId?? default(uint); }
      set { _areaMonsterId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool areaMonsterIdSpecified
    {
      get { return this._areaMonsterId != null; }
      set { if (value == (this._areaMonsterId== null)) this._areaMonsterId = value ? this.areaMonsterId : (uint?)null; }
    }
    private bool ShouldSerializeareaMonsterId() { return areaMonsterIdSpecified; }
    private void ResetareaMonsterId() { areaMonsterIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstanceResAreaInfoNtf")]
  public partial class CmdPVPInstanceResAreaInfoNtf : global::ProtoBuf.IExtensible
  {
    public CmdPVPInstanceResAreaInfoNtf() {}
    
    private readonly global::System.Collections.Generic.List<Proto.PVPInsResAreaInfo> _infos = new global::System.Collections.Generic.List<Proto.PVPInsResAreaInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.PVPInsResAreaInfo> infos
    {
      get { return _infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdPVPInstance")]
    public enum CmdPVPInstance
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPVPInstance_EnterNtf", Value=4501)]
      CmdPVPInstance_EnterNtf = 4501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPVPInstance_EndNtf", Value=4502)]
      CmdPVPInstance_EndNtf = 4502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPVPInstance_UpdateRoleInfoNtf", Value=4503)]
      CmdPVPInstance_UpdateRoleInfoNtf = 4503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPVPInstance_UpdateTargetNtf", Value=4504)]
      CmdPVPInstance_UpdateTargetNtf = 4504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPVPInstance_GainPrizeReq", Value=4505)]
      CmdPVPInstance_GainPrizeReq = 4505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPVPInstance_GainPrizeRes", Value=4506)]
      CmdPVPInstance_GainPrizeRes = 4506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPVPInstance_DataNtf", Value=4507)]
      CmdPVPInstance_DataNtf = 4507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPVPInstance_BossInfoReq", Value=4508)]
      CmdPVPInstance_BossInfoReq = 4508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPVPInstance_BossInfoRes", Value=4509)]
      CmdPVPInstance_BossInfoRes = 4509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdPVPInstance_ResAreaInfoNtf", Value=4510)]
      CmdPVPInstance_ResAreaInfoNtf = 4510
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorPVPInstance")]
    public enum ErrorPVPInstance
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_InfoNotFound", Value=4501)]
      ErrorPVPInstance_InfoNotFound = 4501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_MemNumLimit", Value=4502)]
      ErrorPVPInstance_MemNumLimit = 4502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_CampCountTooLess", Value=4503)]
      ErrorPVPInstance_CampCountTooLess = 4503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_CampCountTooLarge", Value=4504)]
      ErrorPVPInstance_CampCountTooLarge = 4504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_RoleIsNotExist", Value=4505)]
      ErrorPVPInstance_RoleIsNotExist = 4505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_RoleNotInTargetIns", Value=4506)]
      ErrorPVPInstance_RoleNotInTargetIns = 4506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_RolePVPDataNotFound", Value=4507)]
      ErrorPVPInstance_RolePVPDataNotFound = 4507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_InstanceNotFound", Value=4508)]
      ErrorPVPInstance_InstanceNotFound = 4508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_InsPVPDataNotFound", Value=4509)]
      ErrorPVPInstance_InsPVPDataNotFound = 4509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_InsTypeWrong", Value=4510)]
      ErrorPVPInstance_InsTypeWrong = 4510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_InsAlreadyEnded", Value=4511)]
      ErrorPVPInstance_InsAlreadyEnded = 4511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_RolePVPInsDataEmpty", Value=4512)]
      ErrorPVPInstance_RolePVPInsDataEmpty = 4512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_RoleEnterLevelLimit", Value=4513)]
      ErrorPVPInstance_RoleEnterLevelLimit = 4513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_CheckDayTimesFailed", Value=4514)]
      ErrorPVPInstance_CheckDayTimesFailed = 4514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_MapNotFound", Value=4515)]
      ErrorPVPInstance_MapNotFound = 4515,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_BossInfoReqTooFast", Value=4516)]
      ErrorPVPInstance_BossInfoReqTooFast = 4516,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_MonterNotFound", Value=4517)]
      ErrorPVPInstance_MonterNotFound = 4517,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_MonterNotInMap", Value=4518)]
      ErrorPVPInstance_MonterNotInMap = 4518,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_BossInfoArrayFull", Value=4519)]
      ErrorPVPInstance_BossInfoArrayFull = 4519,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_QiujinUseItemCountLimit", Value=4520)]
      ErrorPVPInstance_QiujinUseItemCountLimit = 4520,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_CanJoinTimesNotZero", Value=4521)]
      ErrorPVPInstance_CanJoinTimesNotZero = 4521,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_WeekDayLimit", Value=4522)]
      ErrorPVPInstance_WeekDayLimit = 4522,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_ResAreaNotFound", Value=4523)]
      ErrorPVPInstance_ResAreaNotFound = 4523,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_HuanYingUseItemCountLimit", Value=4524)]
      ErrorPVPInstance_HuanYingUseItemCountLimit = 4524,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_JueDouChangUseItemCountLimit", Value=4525)]
      ErrorPVPInstance_JueDouChangUseItemCountLimit = 4525,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_TeamNotFound", Value=4526)]
      ErrorPVPInstance_TeamNotFound = 4526,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_RoleInTeam", Value=4527)]
      ErrorPVPInstance_RoleInTeam = 4527,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorPVPInstance_TeamMemberOverLimit", Value=4528)]
      ErrorPVPInstance_TeamMemberOverLimit = 4528
    }
  
}