//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: relive.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdReliveDataNtf")]
  public partial class CmdReliveDataNtf : global::ProtoBuf.IExtensible
  {
    public CmdReliveDataNtf() {}
    
    private uint? _reliveTimes;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reliveTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reliveTimes
    {
      get { return _reliveTimes?? default(uint); }
      set { _reliveTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reliveTimesSpecified
    {
      get { return this._reliveTimes != null; }
      set { if (value == (this._reliveTimes== null)) this._reliveTimes = value ? this.reliveTimes : (uint?)null; }
    }
    private bool ShouldSerializereliveTimes() { return reliveTimesSpecified; }
    private void ResetreliveTimes() { reliveTimesSpecified = false; }
    
    private uint? _freeReliveTimes;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"freeReliveTimes", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint freeReliveTimes
    {
      get { return _freeReliveTimes?? default(uint); }
      set { _freeReliveTimes = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool freeReliveTimesSpecified
    {
      get { return this._freeReliveTimes != null; }
      set { if (value == (this._freeReliveTimes== null)) this._freeReliveTimes = value ? this.freeReliveTimes : (uint?)null; }
    }
    private bool ShouldSerializefreeReliveTimes() { return freeReliveTimesSpecified; }
    private void ResetfreeReliveTimes() { freeReliveTimesSpecified = false; }
    
    private uint? _freeReliveTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"freeReliveTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint freeReliveTime
    {
      get { return _freeReliveTime?? default(uint); }
      set { _freeReliveTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool freeReliveTimeSpecified
    {
      get { return this._freeReliveTime != null; }
      set { if (value == (this._freeReliveTime== null)) this._freeReliveTime = value ? this.freeReliveTime : (uint?)null; }
    }
    private bool ShouldSerializefreeReliveTime() { return freeReliveTimeSpecified; }
    private void ResetfreeReliveTime() { freeReliveTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdReliveReq")]
  public partial class CmdReliveReq : global::ProtoBuf.IExtensible
  {
    public CmdReliveReq() {}
    
    private uint? _reliveType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reliveType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint reliveType
    {
      get { return _reliveType?? default(uint); }
      set { _reliveType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reliveTypeSpecified
    {
      get { return this._reliveType != null; }
      set { if (value == (this._reliveType== null)) this._reliveType = value ? this.reliveType : (uint?)null; }
    }
    private bool ShouldSerializereliveType() { return reliveTypeSpecified; }
    private void ResetreliveType() { reliveTypeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdReliveRes")]
  public partial class CmdReliveRes : global::ProtoBuf.IExtensible
  {
    public CmdReliveRes() {}
    
    private ulong? _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId?? default(ulong); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return this._roleId != null; }
      set { if (value == (this._roleId== null)) this._roleId = value ? this.roleId : (ulong?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private uint? _useTicketNum;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"useTicketNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint useTicketNum
    {
      get { return _useTicketNum?? default(uint); }
      set { _useTicketNum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool useTicketNumSpecified
    {
      get { return this._useTicketNum != null; }
      set { if (value == (this._useTicketNum== null)) this._useTicketNum = value ? this.useTicketNum : (uint?)null; }
    }
    private bool ShouldSerializeuseTicketNum() { return useTicketNumSpecified; }
    private void ResetuseTicketNum() { useTicketNumSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdReliveMurder")]
  public partial class CmdReliveMurder : global::ProtoBuf.IExtensible
  {
    public CmdReliveMurder() {}
    
    private int? _monsterInfoId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"monsterInfoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int monsterInfoId
    {
      get { return _monsterInfoId?? default(int); }
      set { _monsterInfoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool monsterInfoIdSpecified
    {
      get { return this._monsterInfoId != null; }
      set { if (value == (this._monsterInfoId== null)) this._monsterInfoId = value ? this.monsterInfoId : (int?)null; }
    }
    private bool ShouldSerializemonsterInfoId() { return monsterInfoIdSpecified; }
    private void ResetmonsterInfoId() { monsterInfoIdSpecified = false; }
    
    private byte[] _roleName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] roleName
    {
      get { return _roleName?? null; }
      set { _roleName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleNameSpecified
    {
      get { return this._roleName != null; }
      set { if (value == (this._roleName== null)) this._roleName = value ? this.roleName : (byte[])null; }
    }
    private bool ShouldSerializeroleName() { return roleNameSpecified; }
    private void ResetroleName() { roleNameSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdReliveDeadNtf")]
  public partial class CmdReliveDeadNtf : global::ProtoBuf.IExtensible
  {
    public CmdReliveDeadNtf() {}
    
    private ulong? _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId?? default(ulong); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return this._roleId != null; }
      set { if (value == (this._roleId== null)) this._roleId = value ? this.roleId : (ulong?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private int? _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int skillId
    {
      get { return _skillId?? default(int); }
      set { _skillId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skillIdSpecified
    {
      get { return this._skillId != null; }
      set { if (value == (this._skillId== null)) this._skillId = value ? this.skillId : (int?)null; }
    }
    private bool ShouldSerializeskillId() { return skillIdSpecified; }
    private void ResetskillId() { skillIdSpecified = false; }
    
    private int? _petSkillId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"petSkillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int petSkillId
    {
      get { return _petSkillId?? default(int); }
      set { _petSkillId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool petSkillIdSpecified
    {
      get { return this._petSkillId != null; }
      set { if (value == (this._petSkillId== null)) this._petSkillId = value ? this.petSkillId : (int?)null; }
    }
    private bool ShouldSerializepetSkillId() { return petSkillIdSpecified; }
    private void ResetpetSkillId() { petSkillIdSpecified = false; }
    
    private int? _deadType;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"deadType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int deadType
    {
      get { return _deadType?? default(int); }
      set { _deadType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool deadTypeSpecified
    {
      get { return this._deadType != null; }
      set { if (value == (this._deadType== null)) this._deadType = value ? this.deadType : (int?)null; }
    }
    private bool ShouldSerializedeadType() { return deadTypeSpecified; }
    private void ResetdeadType() { deadTypeSpecified = false; }
    
    private Proto.CmdReliveMurder _murder = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"murder", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.CmdReliveMurder murder
    {
      get { return _murder; }
      set { _murder = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdRelive")]
    public enum CmdRelive
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdRelive_ReliveReq", Value=901)]
      CmdRelive_ReliveReq = 901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdRelive_ReliveRes", Value=902)]
      CmdRelive_ReliveRes = 902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdRelive_DeadNtf", Value=903)]
      CmdRelive_DeadNtf = 903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdRelive_DataNtf", Value=904)]
      CmdRelive_DataNtf = 904
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorRelive")]
    public enum ErrorRelive
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorRelive_RoleNotDead", Value=901)]
      ErrorRelive_RoleNotDead = 901,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorRelive_ReliveScrollNotEnough", Value=902)]
      ErrorRelive_ReliveScrollNotEnough = 902,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorRelive_CannotReliveAtCurPos", Value=903)]
      ErrorRelive_CannotReliveAtCurPos = 903,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorRelive_UnsupportedReliveType", Value=904)]
      ErrorRelive_UnsupportedReliveType = 904,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorRelive_CheckReliveCDFailed", Value=905)]
      ErrorRelive_CheckReliveCDFailed = 905,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorRelive_CheckFreeReliveTimesFailed", Value=906)]
      ErrorRelive_CheckFreeReliveTimesFailed = 906
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ReliveType")]
    public enum ReliveType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReliveType_CurPosByItem", Value=1)]
      ReliveType_CurPosByItem = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReliveType_MapPos", Value=2)]
      ReliveType_MapPos = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReliveType_CurPosByTicket", Value=3)]
      ReliveType_CurPosByTicket = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReliveType_CurPosByTime", Value=4)]
      ReliveType_CurPosByTime = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReliveType_Battle", Value=5)]
      ReliveType_Battle = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReliveType_Free", Value=6)]
      ReliveType_Free = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReliveType_InsPos", Value=7)]
      ReliveType_InsPos = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReliveType_LuoLanPos", Value=8)]
      ReliveType_LuoLanPos = 8
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"DeadType")]
    public enum DeadType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeadType_Normal", Value=1)]
      DeadType_Normal = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeadType_CaveIn", Value=2)]
      DeadType_CaveIn = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeadType_HitOutMap", Value=3)]
      DeadType_HitOutMap = 3
    }
  
}