//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: shop.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NormalShopItem")]
  public partial class NormalShopItem : global::ProtoBuf.IExtensible
  {
    public NormalShopItem() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopNormalRecordReq")]
  public partial class CmdShopNormalRecordReq : global::ProtoBuf.IExtensible
  {
    public CmdShopNormalRecordReq() {}
    
    private int? _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId?? default(int); }
      set { _shopId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool shopIdSpecified
    {
      get { return this._shopId != null; }
      set { if (value == (this._shopId== null)) this._shopId = value ? this.shopId : (int?)null; }
    }
    private bool ShouldSerializeshopId() { return shopIdSpecified; }
    private void ResetshopId() { shopIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopNormalRecordRes")]
  public partial class CmdShopNormalRecordRes : global::ProtoBuf.IExtensible
  {
    public CmdShopNormalRecordRes() {}
    
    private int? _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId?? default(int); }
      set { _shopId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool shopIdSpecified
    {
      get { return this._shopId != null; }
      set { if (value == (this._shopId== null)) this._shopId = value ? this.shopId : (int?)null; }
    }
    private bool ShouldSerializeshopId() { return shopIdSpecified; }
    private void ResetshopId() { shopIdSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.NormalShopItem> _item = new global::System.Collections.Generic.List<Proto.NormalShopItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.NormalShopItem> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopBuyNormalItemReq")]
  public partial class CmdShopBuyNormalItemReq : global::ProtoBuf.IExtensible
  {
    public CmdShopBuyNormalItemReq() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopBuyNormalItemSucRes")]
  public partial class CmdShopBuyNormalItemSucRes : global::ProtoBuf.IExtensible
  {
    public CmdShopBuyNormalItemSucRes() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"BlackShopItem")]
  public partial class BlackShopItem : global::ProtoBuf.IExtensible
  {
    public BlackShopItem() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _price;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int price
    {
      get { return _price?? default(int); }
      set { _price = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool priceSpecified
    {
      get { return this._price != null; }
      set { if (value == (this._price== null)) this._price = value ? this.price : (int?)null; }
    }
    private bool ShouldSerializeprice() { return priceSpecified; }
    private void Resetprice() { priceSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopBlackListReq")]
  public partial class CmdShopBlackListReq : global::ProtoBuf.IExtensible
  {
    public CmdShopBlackListReq() {}
    
    private int? _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId?? default(int); }
      set { _shopId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool shopIdSpecified
    {
      get { return this._shopId != null; }
      set { if (value == (this._shopId== null)) this._shopId = value ? this.shopId : (int?)null; }
    }
    private bool ShouldSerializeshopId() { return shopIdSpecified; }
    private void ResetshopId() { shopIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopBlackListRes")]
  public partial class CmdShopBlackListRes : global::ProtoBuf.IExtensible
  {
    public CmdShopBlackListRes() {}
    
    private int? _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId?? default(int); }
      set { _shopId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool shopIdSpecified
    {
      get { return this._shopId != null; }
      set { if (value == (this._shopId== null)) this._shopId = value ? this.shopId : (int?)null; }
    }
    private bool ShouldSerializeshopId() { return shopIdSpecified; }
    private void ResetshopId() { shopIdSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.BlackShopItem> _item = new global::System.Collections.Generic.List<Proto.BlackShopItem>();
    [global::ProtoBuf.ProtoMember(2, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.BlackShopItem> item
    {
      get { return _item; }
    }
  
    private uint? _vipRefreshCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"vipRefreshCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint vipRefreshCount
    {
      get { return _vipRefreshCount?? default(uint); }
      set { _vipRefreshCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool vipRefreshCountSpecified
    {
      get { return this._vipRefreshCount != null; }
      set { if (value == (this._vipRefreshCount== null)) this._vipRefreshCount = value ? this.vipRefreshCount : (uint?)null; }
    }
    private bool ShouldSerializevipRefreshCount() { return vipRefreshCountSpecified; }
    private void ResetvipRefreshCount() { vipRefreshCountSpecified = false; }
    
    private uint? _vipCountRefreshTime;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"vipCountRefreshTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint vipCountRefreshTime
    {
      get { return _vipCountRefreshTime?? default(uint); }
      set { _vipCountRefreshTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool vipCountRefreshTimeSpecified
    {
      get { return this._vipCountRefreshTime != null; }
      set { if (value == (this._vipCountRefreshTime== null)) this._vipCountRefreshTime = value ? this.vipCountRefreshTime : (uint?)null; }
    }
    private bool ShouldSerializevipCountRefreshTime() { return vipCountRefreshTimeSpecified; }
    private void ResetvipCountRefreshTime() { vipCountRefreshTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopBlackBuyReq")]
  public partial class CmdShopBlackBuyReq : global::ProtoBuf.IExtensible
  {
    public CmdShopBlackBuyReq() {}
    
    private int? _itemId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId?? default(int); }
      set { _itemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIdSpecified
    {
      get { return this._itemId != null; }
      set { if (value == (this._itemId== null)) this._itemId = value ? this.itemId : (int?)null; }
    }
    private bool ShouldSerializeitemId() { return itemIdSpecified; }
    private void ResetitemId() { itemIdSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopBlackBuyRes")]
  public partial class CmdShopBlackBuyRes : global::ProtoBuf.IExtensible
  {
    public CmdShopBlackBuyRes() {}
    
    private int? _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId?? default(int); }
      set { _shopId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool shopIdSpecified
    {
      get { return this._shopId != null; }
      set { if (value == (this._shopId== null)) this._shopId = value ? this.shopId : (int?)null; }
    }
    private bool ShouldSerializeshopId() { return shopIdSpecified; }
    private void ResetshopId() { shopIdSpecified = false; }
    
    private int? _itemId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId?? default(int); }
      set { _itemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIdSpecified
    {
      get { return this._itemId != null; }
      set { if (value == (this._itemId== null)) this._itemId = value ? this.itemId : (int?)null; }
    }
    private bool ShouldSerializeitemId() { return itemIdSpecified; }
    private void ResetitemId() { itemIdSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopBlackRefreshReq")]
  public partial class CmdShopBlackRefreshReq : global::ProtoBuf.IExtensible
  {
    public CmdShopBlackRefreshReq() {}
    
    private int? _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId?? default(int); }
      set { _shopId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool shopIdSpecified
    {
      get { return this._shopId != null; }
      set { if (value == (this._shopId== null)) this._shopId = value ? this.shopId : (int?)null; }
    }
    private bool ShouldSerializeshopId() { return shopIdSpecified; }
    private void ResetshopId() { shopIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GuildShopItem")]
  public partial class GuildShopItem : global::ProtoBuf.IExtensible
  {
    public GuildShopItem() {}
    
    private int? _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int id
    {
      get { return _id?? default(int); }
      set { _id = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool idSpecified
    {
      get { return this._id != null; }
      set { if (value == (this._id== null)) this._id = value ? this.id : (int?)null; }
    }
    private bool ShouldSerializeid() { return idSpecified; }
    private void Resetid() { idSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopGuildRecordReq")]
  public partial class CmdShopGuildRecordReq : global::ProtoBuf.IExtensible
  {
    public CmdShopGuildRecordReq() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopGuildRecordRes")]
  public partial class CmdShopGuildRecordRes : global::ProtoBuf.IExtensible
  {
    public CmdShopGuildRecordRes() {}
    
    private readonly global::System.Collections.Generic.List<Proto.GuildShopItem> _item = new global::System.Collections.Generic.List<Proto.GuildShopItem>();
    [global::ProtoBuf.ProtoMember(1, Name=@"item", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.GuildShopItem> item
    {
      get { return _item; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopGuildBuyReq")]
  public partial class CmdShopGuildBuyReq : global::ProtoBuf.IExtensible
  {
    public CmdShopGuildBuyReq() {}
    
    private int? _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId?? default(int); }
      set { _itemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIdSpecified
    {
      get { return this._itemId != null; }
      set { if (value == (this._itemId== null)) this._itemId = value ? this.itemId : (int?)null; }
    }
    private bool ShouldSerializeitemId() { return itemIdSpecified; }
    private void ResetitemId() { itemIdSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopGuildBuyRes")]
  public partial class CmdShopGuildBuyRes : global::ProtoBuf.IExtensible
  {
    public CmdShopGuildBuyRes() {}
    
    private int? _itemId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"itemId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int itemId
    {
      get { return _itemId?? default(int); }
      set { _itemId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool itemIdSpecified
    {
      get { return this._itemId != null; }
      set { if (value == (this._itemId== null)) this._itemId = value ? this.itemId : (int?)null; }
    }
    private bool ShouldSerializeitemId() { return itemIdSpecified; }
    private void ResetitemId() { itemIdSpecified = false; }
    
    private int? _count;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count?? default(int); }
      set { _count = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool countSpecified
    {
      get { return this._count != null; }
      set { if (value == (this._count== null)) this._count = value ? this.count : (int?)null; }
    }
    private bool ShouldSerializecount() { return countSpecified; }
    private void Resetcount() { countSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ShopRefreshTimeInfo")]
  public partial class ShopRefreshTimeInfo : global::ProtoBuf.IExtensible
  {
    public ShopRefreshTimeInfo() {}
    
    private int? _shopId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"shopId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int shopId
    {
      get { return _shopId?? default(int); }
      set { _shopId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool shopIdSpecified
    {
      get { return this._shopId != null; }
      set { if (value == (this._shopId== null)) this._shopId = value ? this.shopId : (int?)null; }
    }
    private bool ShouldSerializeshopId() { return shopIdSpecified; }
    private void ResetshopId() { shopIdSpecified = false; }
    
    private uint? _lastRefreshTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lastRefreshTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastRefreshTime
    {
      get { return _lastRefreshTime?? default(uint); }
      set { _lastRefreshTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastRefreshTimeSpecified
    {
      get { return this._lastRefreshTime != null; }
      set { if (value == (this._lastRefreshTime== null)) this._lastRefreshTime = value ? this.lastRefreshTime : (uint?)null; }
    }
    private bool ShouldSerializelastRefreshTime() { return lastRefreshTimeSpecified; }
    private void ResetlastRefreshTime() { lastRefreshTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdShopRefreshTimeInfoNtf")]
  public partial class CmdShopRefreshTimeInfoNtf : global::ProtoBuf.IExtensible
  {
    public CmdShopRefreshTimeInfoNtf() {}
    
    private readonly global::System.Collections.Generic.List<Proto.ShopRefreshTimeInfo> _blackInfos = new global::System.Collections.Generic.List<Proto.ShopRefreshTimeInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"blackInfos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.ShopRefreshTimeInfo> blackInfos
    {
      get { return _blackInfos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdShop")]
    public enum CmdShop
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_NormalRecordReq", Value=1501)]
      CmdShop_NormalRecordReq = 1501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_NormalRecordRes", Value=1502)]
      CmdShop_NormalRecordRes = 1502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_BuyNormalItemReq", Value=1503)]
      CmdShop_BuyNormalItemReq = 1503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_BuyNormalItemSucRes", Value=1504)]
      CmdShop_BuyNormalItemSucRes = 1504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_BlackListReq", Value=1505)]
      CmdShop_BlackListReq = 1505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_BlackListRes", Value=1506)]
      CmdShop_BlackListRes = 1506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_BlackBuyReq", Value=1507)]
      CmdShop_BlackBuyReq = 1507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_BlackBuyRes", Value=1508)]
      CmdShop_BlackBuyRes = 1508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_BlackRefreshReq", Value=1509)]
      CmdShop_BlackRefreshReq = 1509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_GuildRecordReq", Value=1510)]
      CmdShop_GuildRecordReq = 1510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_GuildRecordRes", Value=1511)]
      CmdShop_GuildRecordRes = 1511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_GuildBuyReq", Value=1512)]
      CmdShop_GuildBuyReq = 1512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_GuildBuySucRes", Value=1513)]
      CmdShop_GuildBuySucRes = 1513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdShop_RefreshInfoTimeNtf", Value=1514)]
      CmdShop_RefreshInfoTimeNtf = 1514
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorShop")]
    public enum ErrorShop
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_No_Such_Item", Value=1501)]
      Error_Shop_No_Such_Item = 1501,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_Currency_Not_Enough", Value=1502)]
      Error_Shop_Currency_Not_Enough = 1502,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_Level_Not_Match", Value=1503)]
      Error_Shop_Level_Not_Match = 1503,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_No_Such_Currency", Value=1504)]
      Error_Shop_No_Such_Currency = 1504,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_Cannot_AddItem", Value=1505)]
      Error_Shop_Cannot_AddItem = 1505,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_Type_Dismatch", Value=1506)]
      Error_Shop_Type_Dismatch = 1506,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_RoleOccupationError", Value=1507)]
      Error_Shop_RoleOccupationError = 1507,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_OccupationGroupFail", Value=1508)]
      Error_Shop_OccupationGroupFail = 1508,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_CountLimitFail", Value=1509)]
      Error_Shop_CountLimitFail = 1509,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_ShopInfoNotFound", Value=1510)]
      Error_Shop_ShopInfoNotFound = 1510,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_BlackAddFailed", Value=1511)]
      Error_Shop_BlackAddFailed = 1511,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_BlackItemNotFound", Value=1512)]
      Error_Shop_BlackItemNotFound = 1512,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_BlackShopNotFound", Value=1513)]
      Error_Shop_BlackShopNotFound = 1513,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_BlackItemInfoNotFound", Value=1514)]
      Error_Shop_BlackItemInfoNotFound = 1514,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_BlackItemCountFail", Value=1515)]
      Error_Shop_BlackItemCountFail = 1515,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_RefreshBlackTicketFailed", Value=1516)]
      Error_Shop_RefreshBlackTicketFailed = 1516,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_ItemInfoNotFound", Value=1517)]
      Error_Shop_ItemInfoNotFound = 1517,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_RefreshTimesNotEnoughtError", Value=1518)]
      Error_Shop_RefreshTimesNotEnoughtError = 1518,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_BuyCountTooLarge", Value=1519)]
      Error_Shop_BuyCountTooLarge = 1519,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_Shop_EloValueError", Value=1520)]
      Error_Shop_EloValueError = 1520
    }
  
}