//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: transformers.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Transformersskin")]
  public partial class Transformersskin : global::ProtoBuf.IExtensible
  {
    public Transformersskin() {}
    
    private uint? _skinId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skinId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skinId
    {
      get { return _skinId?? default(uint); }
      set { _skinId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skinIdSpecified
    {
      get { return this._skinId != null; }
      set { if (value == (this._skinId== null)) this._skinId = value ? this.skinId : (uint?)null; }
    }
    private bool ShouldSerializeskinId() { return skinIdSpecified; }
    private void ResetskinId() { skinIdSpecified = false; }
    
    private long? _endTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"endTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endTime
    {
      get { return _endTime?? default(long); }
      set { _endTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endTimeSpecified
    {
      get { return this._endTime != null; }
      set { if (value == (this._endTime== null)) this._endTime = value ? this.endTime : (long?)null; }
    }
    private bool ShouldSerializeendTime() { return endTimeSpecified; }
    private void ResetendTime() { endTimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Transformersskill")]
  public partial class Transformersskill : global::ProtoBuf.IExtensible
  {
    public Transformersskill() {}
    
    private uint? _skillid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"skillid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillid
    {
      get { return _skillid?? default(uint); }
      set { _skillid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skillidSpecified
    {
      get { return this._skillid != null; }
      set { if (value == (this._skillid== null)) this._skillid = value ? this.skillid : (uint?)null; }
    }
    private bool ShouldSerializeskillid() { return skillidSpecified; }
    private void Resetskillid() { skillidSpecified = false; }
    
    private uint? _skilllvl;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skilllvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skilllvl
    {
      get { return _skilllvl?? default(uint); }
      set { _skilllvl = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skilllvlSpecified
    {
      get { return this._skilllvl != null; }
      set { if (value == (this._skilllvl== null)) this._skilllvl = value ? this.skilllvl : (uint?)null; }
    }
    private bool ShouldSerializeskilllvl() { return skilllvlSpecified; }
    private void Resetskilllvl() { skilllvlSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"TransformersRing")]
  public partial class TransformersRing : global::ProtoBuf.IExtensible
  {
    public TransformersRing() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _ringlvl;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ringlvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringlvl
    {
      get { return _ringlvl?? default(uint); }
      set { _ringlvl = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringlvlSpecified
    {
      get { return this._ringlvl != null; }
      set { if (value == (this._ringlvl== null)) this._ringlvl = value ? this.ringlvl : (uint?)null; }
    }
    private bool ShouldSerializeringlvl() { return ringlvlSpecified; }
    private void Resetringlvl() { ringlvlSpecified = false; }
    
    private uint? _ringstar;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ringstar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringstar
    {
      get { return _ringstar?? default(uint); }
      set { _ringstar = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringstarSpecified
    {
      get { return this._ringstar != null; }
      set { if (value == (this._ringstar== null)) this._ringstar = value ? this.ringstar : (uint?)null; }
    }
    private bool ShouldSerializeringstar() { return ringstarSpecified; }
    private void Resetringstar() { ringstarSpecified = false; }
    
    private uint? _curskin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"curskin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint curskin
    {
      get { return _curskin?? default(uint); }
      set { _curskin = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curskinSpecified
    {
      get { return this._curskin != null; }
      set { if (value == (this._curskin== null)) this._curskin = value ? this.curskin : (uint?)null; }
    }
    private bool ShouldSerializecurskin() { return curskinSpecified; }
    private void Resetcurskin() { curskinSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.Transformersskin> _skin = new global::System.Collections.Generic.List<Proto.Transformersskin>();
    [global::ProtoBuf.ProtoMember(5, Name=@"skin", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.Transformersskin> skin
    {
      get { return _skin; }
    }
  
    private readonly global::System.Collections.Generic.List<Proto.Transformersskill> _activeskill = new global::System.Collections.Generic.List<Proto.Transformersskill>();
    [global::ProtoBuf.ProtoMember(6, Name=@"activeskill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.Transformersskill> activeskill
    {
      get { return _activeskill; }
    }
  
    private readonly global::System.Collections.Generic.List<Proto.Transformersskill> _passiveskill = new global::System.Collections.Generic.List<Proto.Transformersskill>();
    [global::ProtoBuf.ProtoMember(7, Name=@"passiveskill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.Transformersskill> passiveskill
    {
      get { return _passiveskill; }
    }
  
    private uint? _blessvalue;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"blessvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint blessvalue
    {
      get { return _blessvalue?? default(uint); }
      set { _blessvalue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool blessvalueSpecified
    {
      get { return this._blessvalue != null; }
      set { if (value == (this._blessvalue== null)) this._blessvalue = value ? this.blessvalue : (uint?)null; }
    }
    private bool ShouldSerializeblessvalue() { return blessvalueSpecified; }
    private void Resetblessvalue() { blessvalueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersDataInfoNtf")]
  public partial class CmdTransformersDataInfoNtf : global::ProtoBuf.IExtensible
  {
    public CmdTransformersDataInfoNtf() {}
    
    private uint? _curringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"curringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint curringid
    {
      get { return _curringid?? default(uint); }
      set { _curringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool curringidSpecified
    {
      get { return this._curringid != null; }
      set { if (value == (this._curringid== null)) this._curringid = value ? this.curringid : (uint?)null; }
    }
    private bool ShouldSerializecurringid() { return curringidSpecified; }
    private void Resetcurringid() { curringidSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.TransformersRing> _ring = new global::System.Collections.Generic.List<Proto.TransformersRing>();
    [global::ProtoBuf.ProtoMember(2, Name=@"ring", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.TransformersRing> ring
    {
      get { return _ring; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersEnchanceReq")]
  public partial class CmdTransformersEnchanceReq : global::ProtoBuf.IExtensible
  {
    public CmdTransformersEnchanceReq() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersEnchanceRes")]
  public partial class CmdTransformersEnchanceRes : global::ProtoBuf.IExtensible
  {
    public CmdTransformersEnchanceRes() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _lvl;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lvl
    {
      get { return _lvl?? default(uint); }
      set { _lvl = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lvlSpecified
    {
      get { return this._lvl != null; }
      set { if (value == (this._lvl== null)) this._lvl = value ? this.lvl : (uint?)null; }
    }
    private bool ShouldSerializelvl() { return lvlSpecified; }
    private void Resetlvl() { lvlSpecified = false; }
    
    private uint? _blessvalue;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"blessvalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint blessvalue
    {
      get { return _blessvalue?? default(uint); }
      set { _blessvalue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool blessvalueSpecified
    {
      get { return this._blessvalue != null; }
      set { if (value == (this._blessvalue== null)) this._blessvalue = value ? this.blessvalue : (uint?)null; }
    }
    private bool ShouldSerializeblessvalue() { return blessvalueSpecified; }
    private void Resetblessvalue() { blessvalueSpecified = false; }
    
    private uint? _result;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint result
    {
      get { return _result?? default(uint); }
      set { _result = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool resultSpecified
    {
      get { return this._result != null; }
      set { if (value == (this._result== null)) this._result = value ? this.result : (uint?)null; }
    }
    private bool ShouldSerializeresult() { return resultSpecified; }
    private void Resetresult() { resultSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersRingStarReq")]
  public partial class CmdTransformersRingStarReq : global::ProtoBuf.IExtensible
  {
    public CmdTransformersRingStarReq() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersRingStarRes")]
  public partial class CmdTransformersRingStarRes : global::ProtoBuf.IExtensible
  {
    public CmdTransformersRingStarRes() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _ringstar;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ringstar", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringstar
    {
      get { return _ringstar?? default(uint); }
      set { _ringstar = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringstarSpecified
    {
      get { return this._ringstar != null; }
      set { if (value == (this._ringstar== null)) this._ringstar = value ? this.ringstar : (uint?)null; }
    }
    private bool ShouldSerializeringstar() { return ringstarSpecified; }
    private void Resetringstar() { ringstarSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.Transformersskill> _passiveskill = new global::System.Collections.Generic.List<Proto.Transformersskill>();
    [global::ProtoBuf.ProtoMember(3, Name=@"passiveskill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.Transformersskill> passiveskill
    {
      get { return _passiveskill; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersRingChangeReq")]
  public partial class CmdTransformersRingChangeReq : global::ProtoBuf.IExtensible
  {
    public CmdTransformersRingChangeReq() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersRingChangeRes")]
  public partial class CmdTransformersRingChangeRes : global::ProtoBuf.IExtensible
  {
    public CmdTransformersRingChangeRes() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _skinid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skinid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skinid
    {
      get { return _skinid?? default(uint); }
      set { _skinid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skinidSpecified
    {
      get { return this._skinid != null; }
      set { if (value == (this._skinid== null)) this._skinid = value ? this.skinid : (uint?)null; }
    }
    private bool ShouldSerializeskinid() { return skinidSpecified; }
    private void Resetskinid() { skinidSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersSkinChangeReq")]
  public partial class CmdTransformersSkinChangeReq : global::ProtoBuf.IExtensible
  {
    public CmdTransformersSkinChangeReq() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _skinid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skinid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skinid
    {
      get { return _skinid?? default(uint); }
      set { _skinid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skinidSpecified
    {
      get { return this._skinid != null; }
      set { if (value == (this._skinid== null)) this._skinid = value ? this.skinid : (uint?)null; }
    }
    private bool ShouldSerializeskinid() { return skinidSpecified; }
    private void Resetskinid() { skinidSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersSkinChangeRes")]
  public partial class CmdTransformersSkinChangeRes : global::ProtoBuf.IExtensible
  {
    public CmdTransformersSkinChangeRes() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _skinid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skinid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skinid
    {
      get { return _skinid?? default(uint); }
      set { _skinid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skinidSpecified
    {
      get { return this._skinid != null; }
      set { if (value == (this._skinid== null)) this._skinid = value ? this.skinid : (uint?)null; }
    }
    private bool ShouldSerializeskinid() { return skinidSpecified; }
    private void Resetskinid() { skinidSpecified = false; }
    
    private long? _endtime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"endtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endtime
    {
      get { return _endtime?? default(long); }
      set { _endtime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endtimeSpecified
    {
      get { return this._endtime != null; }
      set { if (value == (this._endtime== null)) this._endtime = value ? this.endtime : (long?)null; }
    }
    private bool ShouldSerializeendtime() { return endtimeSpecified; }
    private void Resetendtime() { endtimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersRingActivationReq")]
  public partial class CmdTransformersRingActivationReq : global::ProtoBuf.IExtensible
  {
    public CmdTransformersRingActivationReq() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersRingActivationRes")]
  public partial class CmdTransformersRingActivationRes : global::ProtoBuf.IExtensible
  {
    public CmdTransformersRingActivationRes() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _skiinid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skiinid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skiinid
    {
      get { return _skiinid?? default(uint); }
      set { _skiinid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skiinidSpecified
    {
      get { return this._skiinid != null; }
      set { if (value == (this._skiinid== null)) this._skiinid = value ? this.skiinid : (uint?)null; }
    }
    private bool ShouldSerializeskiinid() { return skiinidSpecified; }
    private void Resetskiinid() { skiinidSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.Transformersskill> _activeskill = new global::System.Collections.Generic.List<Proto.Transformersskill>();
    [global::ProtoBuf.ProtoMember(3, Name=@"activeskill", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.Transformersskill> activeskill
    {
      get { return _activeskill; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersSkillLevelUpReq")]
  public partial class CmdTransformersSkillLevelUpReq : global::ProtoBuf.IExtensible
  {
    public CmdTransformersSkillLevelUpReq() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillId
    {
      get { return _skillId?? default(uint); }
      set { _skillId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skillIdSpecified
    {
      get { return this._skillId != null; }
      set { if (value == (this._skillId== null)) this._skillId = value ? this.skillId : (uint?)null; }
    }
    private bool ShouldSerializeskillId() { return skillIdSpecified; }
    private void ResetskillId() { skillIdSpecified = false; }
    
    private uint? _passive;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"passive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint passive
    {
      get { return _passive?? default(uint); }
      set { _passive = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool passiveSpecified
    {
      get { return this._passive != null; }
      set { if (value == (this._passive== null)) this._passive = value ? this.passive : (uint?)null; }
    }
    private bool ShouldSerializepassive() { return passiveSpecified; }
    private void Resetpassive() { passiveSpecified = false; }
    
    private uint? _targetLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"targetLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint targetLevel
    {
      get { return _targetLevel?? default(uint); }
      set { _targetLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool targetLevelSpecified
    {
      get { return this._targetLevel != null; }
      set { if (value == (this._targetLevel== null)) this._targetLevel = value ? this.targetLevel : (uint?)null; }
    }
    private bool ShouldSerializetargetLevel() { return targetLevelSpecified; }
    private void ResettargetLevel() { targetLevelSpecified = false; }
    
    private uint? _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level?? default(uint); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (uint?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersSkillLevelUpRes")]
  public partial class CmdTransformersSkillLevelUpRes : global::ProtoBuf.IExtensible
  {
    public CmdTransformersSkillLevelUpRes() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _skillId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skillId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillId
    {
      get { return _skillId?? default(uint); }
      set { _skillId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skillIdSpecified
    {
      get { return this._skillId != null; }
      set { if (value == (this._skillId== null)) this._skillId = value ? this.skillId : (uint?)null; }
    }
    private bool ShouldSerializeskillId() { return skillIdSpecified; }
    private void ResetskillId() { skillIdSpecified = false; }
    
    private uint? _skillLvl;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"skillLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skillLvl
    {
      get { return _skillLvl?? default(uint); }
      set { _skillLvl = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skillLvlSpecified
    {
      get { return this._skillLvl != null; }
      set { if (value == (this._skillLvl== null)) this._skillLvl = value ? this.skillLvl : (uint?)null; }
    }
    private bool ShouldSerializeskillLvl() { return skillLvlSpecified; }
    private void ResetskillLvl() { skillLvlSpecified = false; }
    
    private uint? _passive;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"passive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint passive
    {
      get { return _passive?? default(uint); }
      set { _passive = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool passiveSpecified
    {
      get { return this._passive != null; }
      set { if (value == (this._passive== null)) this._passive = value ? this.passive : (uint?)null; }
    }
    private bool ShouldSerializepassive() { return passiveSpecified; }
    private void Resetpassive() { passiveSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersSkinActivationReq")]
  public partial class CmdTransformersSkinActivationReq : global::ProtoBuf.IExtensible
  {
    public CmdTransformersSkinActivationReq() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _skinid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skinid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skinid
    {
      get { return _skinid?? default(uint); }
      set { _skinid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skinidSpecified
    {
      get { return this._skinid != null; }
      set { if (value == (this._skinid== null)) this._skinid = value ? this.skinid : (uint?)null; }
    }
    private bool ShouldSerializeskinid() { return skinidSpecified; }
    private void Resetskinid() { skinidSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdTransformersSkinActivationRes")]
  public partial class CmdTransformersSkinActivationRes : global::ProtoBuf.IExtensible
  {
    public CmdTransformersSkinActivationRes() {}
    
    private uint? _ringid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"ringid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint ringid
    {
      get { return _ringid?? default(uint); }
      set { _ringid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool ringidSpecified
    {
      get { return this._ringid != null; }
      set { if (value == (this._ringid== null)) this._ringid = value ? this.ringid : (uint?)null; }
    }
    private bool ShouldSerializeringid() { return ringidSpecified; }
    private void Resetringid() { ringidSpecified = false; }
    
    private uint? _skinid;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"skinid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint skinid
    {
      get { return _skinid?? default(uint); }
      set { _skinid = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool skinidSpecified
    {
      get { return this._skinid != null; }
      set { if (value == (this._skinid== null)) this._skinid = value ? this.skinid : (uint?)null; }
    }
    private bool ShouldSerializeskinid() { return skinidSpecified; }
    private void Resetskinid() { skinidSpecified = false; }
    
    private long? _endtime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"endtime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long endtime
    {
      get { return _endtime?? default(long); }
      set { _endtime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool endtimeSpecified
    {
      get { return this._endtime != null; }
      set { if (value == (this._endtime== null)) this._endtime = value ? this.endtime : (long?)null; }
    }
    private bool ShouldSerializeendtime() { return endtimeSpecified; }
    private void Resetendtime() { endtimeSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdTransformers")]
    public enum CmdTransformers
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_DataInfoNtf", Value=9100)]
      CmdTransformers_DataInfoNtf = 9100,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_EnchanceReq", Value=9101)]
      CmdTransformers_EnchanceReq = 9101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_EnchanceRes", Value=9102)]
      CmdTransformers_EnchanceRes = 9102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_RingStarReq", Value=9103)]
      CmdTransformers_RingStarReq = 9103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_RingStarRes", Value=9104)]
      CmdTransformers_RingStarRes = 9104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_RingChangeReq", Value=9105)]
      CmdTransformers_RingChangeReq = 9105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_RingChangeRes", Value=9106)]
      CmdTransformers_RingChangeRes = 9106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_SkinChangeReq", Value=9107)]
      CmdTransformers_SkinChangeReq = 9107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_SkinChangeRes", Value=9108)]
      CmdTransformers_SkinChangeRes = 9108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_RingActivationReq", Value=9109)]
      CmdTransformers_RingActivationReq = 9109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_RingActivationRes", Value=9110)]
      CmdTransformers_RingActivationRes = 9110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_SkillLevelUpReq", Value=9112)]
      CmdTransformers_SkillLevelUpReq = 9112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_SkillLevelUpRes", Value=9113)]
      CmdTransformers_SkillLevelUpRes = 9113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_SkinActivationReq", Value=9114)]
      CmdTransformers_SkinActivationReq = 9114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdTransformers_SkinActivationRes", Value=9115)]
      CmdTransformers_SkinActivationRes = 9115
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorTransformers")]
    public enum ErrorTransformers
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_RingIdError", Value=9101)]
      ErrorTransformers_RingIdError = 9101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_RingHasActivation", Value=9102)]
      ErrorTransformers_RingHasActivation = 9102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_RingNumMaxError", Value=9103)]
      ErrorTransformers_RingNumMaxError = 9103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_RingInfoError", Value=9104)]
      ErrorTransformers_RingInfoError = 9104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_RingNotActivation", Value=9105)]
      ErrorTransformers_RingNotActivation = 9105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_RoleLevelNotEnough", Value=9106)]
      ErrorTransformers_RoleLevelNotEnough = 9106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_EnchanceItemNotEnough", Value=9107)]
      ErrorTransformers_EnchanceItemNotEnough = 9107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_StarItemNotEnough", Value=9108)]
      ErrorTransformers_StarItemNotEnough = 9108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_SkinItemNotEnough", Value=9109)]
      ErrorTransformers_SkinItemNotEnough = 9109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_SkinHasNotActivation", Value=9110)]
      ErrorTransformers_SkinHasNotActivation = 9110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_SkinIdError", Value=9111)]
      ErrorTransformers_SkinIdError = 9111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_SkinActivationItemNotEnouth", Value=9112)]
      ErrorTransformers_SkinActivationItemNotEnouth = 9112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_FreeSkinHasActivationError", Value=9113)]
      ErrorTransformers_FreeSkinHasActivationError = 9113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_SkinHasTimeOutError", Value=9114)]
      ErrorTransformers_SkinHasTimeOutError = 9114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_RingStarConfigError", Value=9115)]
      ErrorTransformers_RingStarConfigError = 9115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_RingStarItemNotEnough", Value=9116)]
      ErrorTransformers_RingStarItemNotEnough = 9116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_SkillHasNotActivation", Value=9117)]
      ErrorTransformers_SkillHasNotActivation = 9117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_SkillIdError", Value=9118)]
      ErrorTransformers_SkillIdError = 9118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_SkillLevelError", Value=9119)]
      ErrorTransformers_SkillLevelError = 9119,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_LevelUpLevelFailed", Value=9120)]
      ErrorTransformers_LevelUpLevelFailed = 9120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_EquipRingError", Value=9121)]
      ErrorTransformers_EquipRingError = 9121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_RingRageValueNotEnough", Value=9122)]
      ErrorTransformers_RingRageValueNotEnough = 9122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_MapNotTransformersError", Value=9123)]
      ErrorTransformers_MapNotTransformersError = 9123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_HasTransformers", Value=9124)]
      ErrorTransformers_HasTransformers = 9124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ErrorTransformers_TransformersNotOperate", Value=9125)]
      ErrorTransformers_TransformersNotOperate = 9125
    }
  
}