//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Option: missing-value detection (*Specified/ShouldSerialize*/Reset*) enabled
    
// Generated from: worldRank.proto
namespace Proto
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankRoleBody")]
  public partial class RankRoleBody : global::ProtoBuf.IExtensible
  {
    public RankRoleBody() {}
    
    private uint? _pos;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint pos
    {
      get { return _pos?? default(uint); }
      set { _pos = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool posSpecified
    {
      get { return this._pos != null; }
      set { if (value == (this._pos== null)) this._pos = value ? this.pos : (uint?)null; }
    }
    private bool ShouldSerializepos() { return posSpecified; }
    private void Resetpos() { posSpecified = false; }
    
    private int? _infoId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int infoId
    {
      get { return _infoId?? default(int); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (int?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private uint? _enhancelvl;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"enhancelvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint enhancelvl
    {
      get { return _enhancelvl?? default(uint); }
      set { _enhancelvl = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool enhancelvlSpecified
    {
      get { return this._enhancelvl != null; }
      set { if (value == (this._enhancelvl== null)) this._enhancelvl = value ? this.enhancelvl : (uint?)null; }
    }
    private bool ShouldSerializeenhancelvl() { return enhancelvlSpecified; }
    private void Resetenhancelvl() { enhancelvlSpecified = false; }
    
    private uint? _powerOnlvl;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"powerOnlvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint powerOnlvl
    {
      get { return _powerOnlvl?? default(uint); }
      set { _powerOnlvl = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool powerOnlvlSpecified
    {
      get { return this._powerOnlvl != null; }
      set { if (value == (this._powerOnlvl== null)) this._powerOnlvl = value ? this.powerOnlvl : (uint?)null; }
    }
    private bool ShouldSerializepowerOnlvl() { return powerOnlvlSpecified; }
    private void ResetpowerOnlvl() { powerOnlvlSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankWingData")]
  public partial class RankWingData : global::ProtoBuf.IExtensible
  {
    public RankWingData() {}
    
    private int? _wingId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"wingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wingId
    {
      get { return _wingId?? default(int); }
      set { _wingId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool wingIdSpecified
    {
      get { return this._wingId != null; }
      set { if (value == (this._wingId== null)) this._wingId = value ? this.wingId : (int?)null; }
    }
    private bool ShouldSerializewingId() { return wingIdSpecified; }
    private void ResetwingId() { wingIdSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankRoleInfo")]
  public partial class RankRoleInfo : global::ProtoBuf.IExtensible
  {
    public RankRoleInfo() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name?? null; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (byte[])null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private byte[] _guildName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"guildName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] guildName
    {
      get { return _guildName?? null; }
      set { _guildName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool guildNameSpecified
    {
      get { return this._guildName != null; }
      set { if (value == (this._guildName== null)) this._guildName = value ? this.guildName : (byte[])null; }
    }
    private bool ShouldSerializeguildName() { return guildNameSpecified; }
    private void ResetguildName() { guildNameSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private int? _power;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int power
    {
      get { return _power?? default(int); }
      set { _power = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool powerSpecified
    {
      get { return this._power != null; }
      set { if (value == (this._power== null)) this._power = value ? this.power : (int?)null; }
    }
    private bool ShouldSerializepower() { return powerSpecified; }
    private void Resetpower() { powerSpecified = false; }
    
    private int? _occupation;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"occupation", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int occupation
    {
      get { return _occupation?? default(int); }
      set { _occupation = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool occupationSpecified
    {
      get { return this._occupation != null; }
      set { if (value == (this._occupation== null)) this._occupation = value ? this.occupation : (int?)null; }
    }
    private bool ShouldSerializeoccupation() { return occupationSpecified; }
    private void Resetoccupation() { occupationSpecified = false; }
    
    private int? _worshipCount;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"worshipCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int worshipCount
    {
      get { return _worshipCount?? default(int); }
      set { _worshipCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool worshipCountSpecified
    {
      get { return this._worshipCount != null; }
      set { if (value == (this._worshipCount== null)) this._worshipCount = value ? this.worshipCount : (int?)null; }
    }
    private bool ShouldSerializeworshipCount() { return worshipCountSpecified; }
    private void ResetworshipCount() { worshipCountSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.RankRoleBody> _body = new global::System.Collections.Generic.List<Proto.RankRoleBody>();
    [global::ProtoBuf.ProtoMember(7, Name=@"body", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.RankRoleBody> body
    {
      get { return _body; }
    }
  
    private Proto.RankWingData _wing = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"wing", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.RankWingData wing
    {
      get { return _wing; }
      set { _wing = value; }
    }
    private bool? _isOnline;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"isOnline", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool isOnline
    {
      get { return _isOnline?? default(bool); }
      set { _isOnline = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool isOnlineSpecified
    {
      get { return this._isOnline != null; }
      set { if (value == (this._isOnline== null)) this._isOnline = value ? this.isOnline : (bool?)null; }
    }
    private bool ShouldSerializeisOnline() { return isOnlineSpecified; }
    private void ResetisOnline() { isOnlineSpecified = false; }
    
    private int? _honor;
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"honor", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int honor
    {
      get { return _honor?? default(int); }
      set { _honor = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool honorSpecified
    {
      get { return this._honor != null; }
      set { if (value == (this._honor== null)) this._honor = value ? this.honor : (int?)null; }
    }
    private bool ShouldSerializehonor() { return honorSpecified; }
    private void Resethonor() { honorSpecified = false; }
    
    private uint? _achievePoint;
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"achievePoint", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint achievePoint
    {
      get { return _achievePoint?? default(uint); }
      set { _achievePoint = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool achievePointSpecified
    {
      get { return this._achievePoint != null; }
      set { if (value == (this._achievePoint== null)) this._achievePoint = value ? this.achievePoint : (uint?)null; }
    }
    private bool ShouldSerializeachievePoint() { return achievePointSpecified; }
    private void ResetachievePoint() { achievePointSpecified = false; }
    
    private uint? _climbTowerMode;
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"climbTowerMode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint climbTowerMode
    {
      get { return _climbTowerMode?? default(uint); }
      set { _climbTowerMode = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool climbTowerModeSpecified
    {
      get { return this._climbTowerMode != null; }
      set { if (value == (this._climbTowerMode== null)) this._climbTowerMode = value ? this.climbTowerMode : (uint?)null; }
    }
    private bool ShouldSerializeclimbTowerMode() { return climbTowerModeSpecified; }
    private void ResetclimbTowerMode() { climbTowerModeSpecified = false; }
    
    private uint? _climbTowerTollGate;
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"climbTowerTollGate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint climbTowerTollGate
    {
      get { return _climbTowerTollGate?? default(uint); }
      set { _climbTowerTollGate = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool climbTowerTollGateSpecified
    {
      get { return this._climbTowerTollGate != null; }
      set { if (value == (this._climbTowerTollGate== null)) this._climbTowerTollGate = value ? this.climbTowerTollGate : (uint?)null; }
    }
    private bool ShouldSerializeclimbTowerTollGate() { return climbTowerTollGateSpecified; }
    private void ResetclimbTowerTollGate() { climbTowerTollGateSpecified = false; }
    
    private uint? _elovalue;
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"elovalue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint elovalue
    {
      get { return _elovalue?? default(uint); }
      set { _elovalue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool elovalueSpecified
    {
      get { return this._elovalue != null; }
      set { if (value == (this._elovalue== null)) this._elovalue = value ? this.elovalue : (uint?)null; }
    }
    private bool ShouldSerializeelovalue() { return elovalueSpecified; }
    private void Resetelovalue() { elovalueSpecified = false; }
    
    private int? _holyVesselLevel;
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"holyVesselLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int holyVesselLevel
    {
      get { return _holyVesselLevel?? default(int); }
      set { _holyVesselLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool holyVesselLevelSpecified
    {
      get { return this._holyVesselLevel != null; }
      set { if (value == (this._holyVesselLevel== null)) this._holyVesselLevel = value ? this.holyVesselLevel : (int?)null; }
    }
    private bool ShouldSerializeholyVesselLevel() { return holyVesselLevelSpecified; }
    private void ResetholyVesselLevel() { holyVesselLevelSpecified = false; }
    
    private uint? _fashionId;
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"fashionId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint fashionId
    {
      get { return _fashionId?? default(uint); }
      set { _fashionId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool fashionIdSpecified
    {
      get { return this._fashionId != null; }
      set { if (value == (this._fashionId== null)) this._fashionId = value ? this.fashionId : (uint?)null; }
    }
    private bool ShouldSerializefashionId() { return fashionIdSpecified; }
    private void ResetfashionId() { fashionIdSpecified = false; }
    
    private uint? _charmId;
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"charmId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint charmId
    {
      get { return _charmId?? default(uint); }
      set { _charmId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool charmIdSpecified
    {
      get { return this._charmId != null; }
      set { if (value == (this._charmId== null)) this._charmId = value ? this.charmId : (uint?)null; }
    }
    private bool ShouldSerializecharmId() { return charmIdSpecified; }
    private void ResetcharmId() { charmIdSpecified = false; }
    
    private uint? _layer;
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"layer", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint layer
    {
      get { return _layer?? default(uint); }
      set { _layer = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool layerSpecified
    {
      get { return this._layer != null; }
      set { if (value == (this._layer== null)) this._layer = value ? this.layer : (uint?)null; }
    }
    private bool ShouldSerializelayer() { return layerSpecified; }
    private void Resetlayer() { layerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankPetInfo")]
  public partial class RankPetInfo : global::ProtoBuf.IExtensible
  {
    public RankPetInfo() {}
    
    private byte[] _roleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] roleName
    {
      get { return _roleName?? null; }
      set { _roleName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleNameSpecified
    {
      get { return this._roleName != null; }
      set { if (value == (this._roleName== null)) this._roleName = value ? this.roleName : (byte[])null; }
    }
    private bool ShouldSerializeroleName() { return roleNameSpecified; }
    private void ResetroleName() { roleNameSpecified = false; }
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name?? null; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (byte[])null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private uint? _infoId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint infoId
    {
      get { return _infoId?? default(uint); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (uint?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private uint? _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level?? default(uint); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (uint?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private uint? _power;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint power
    {
      get { return _power?? default(uint); }
      set { _power = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool powerSpecified
    {
      get { return this._power != null; }
      set { if (value == (this._power== null)) this._power = value ? this.power : (uint?)null; }
    }
    private bool ShouldSerializepower() { return powerSpecified; }
    private void Resetpower() { powerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankWingInfo")]
  public partial class RankWingInfo : global::ProtoBuf.IExtensible
  {
    public RankWingInfo() {}
    
    private byte[] _roleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] roleName
    {
      get { return _roleName?? null; }
      set { _roleName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleNameSpecified
    {
      get { return this._roleName != null; }
      set { if (value == (this._roleName== null)) this._roleName = value ? this.roleName : (byte[])null; }
    }
    private bool ShouldSerializeroleName() { return roleNameSpecified; }
    private void ResetroleName() { roleNameSpecified = false; }
    
    private int? _wingId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"wingId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wingId
    {
      get { return _wingId?? default(int); }
      set { _wingId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool wingIdSpecified
    {
      get { return this._wingId != null; }
      set { if (value == (this._wingId== null)) this._wingId = value ? this.wingId : (int?)null; }
    }
    private bool ShouldSerializewingId() { return wingIdSpecified; }
    private void ResetwingId() { wingIdSpecified = false; }
    
    private int? _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level?? default(int); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (int?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private int? _godWingLevel;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"godWingLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int godWingLevel
    {
      get { return _godWingLevel?? default(int); }
      set { _godWingLevel = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool godWingLevelSpecified
    {
      get { return this._godWingLevel != null; }
      set { if (value == (this._godWingLevel== null)) this._godWingLevel = value ? this.godWingLevel : (int?)null; }
    }
    private bool ShouldSerializegodWingLevel() { return godWingLevelSpecified; }
    private void ResetgodWingLevel() { godWingLevelSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankGuildInfo")]
  public partial class RankGuildInfo : global::ProtoBuf.IExtensible
  {
    public RankGuildInfo() {}
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name?? null; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (byte[])null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private byte[] _leader;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"leader", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] leader
    {
      get { return _leader?? null; }
      set { _leader = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool leaderSpecified
    {
      get { return this._leader != null; }
      set { if (value == (this._leader== null)) this._leader = value ? this.leader : (byte[])null; }
    }
    private bool ShouldSerializeleader() { return leaderSpecified; }
    private void Resetleader() { leaderSpecified = false; }
    
    private ulong? _leaderId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"leaderId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong leaderId
    {
      get { return _leaderId?? default(ulong); }
      set { _leaderId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool leaderIdSpecified
    {
      get { return this._leaderId != null; }
      set { if (value == (this._leaderId== null)) this._leaderId = value ? this.leaderId : (ulong?)null; }
    }
    private bool ShouldSerializeleaderId() { return leaderIdSpecified; }
    private void ResetleaderId() { leaderIdSpecified = false; }
    
    private uint? _guildId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"guildId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint guildId
    {
      get { return _guildId?? default(uint); }
      set { _guildId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool guildIdSpecified
    {
      get { return this._guildId != null; }
      set { if (value == (this._guildId== null)) this._guildId = value ? this.guildId : (uint?)null; }
    }
    private bool ShouldSerializeguildId() { return guildIdSpecified; }
    private void ResetguildId() { guildIdSpecified = false; }
    
    private uint? _level;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level?? default(uint); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (uint?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private uint? _power;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint power
    {
      get { return _power?? default(uint); }
      set { _power = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool powerSpecified
    {
      get { return this._power != null; }
      set { if (value == (this._power== null)) this._power = value ? this.power : (uint?)null; }
    }
    private bool ShouldSerializepower() { return powerSpecified; }
    private void Resetpower() { powerSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankHorseStone")]
  public partial class RankHorseStone : global::ProtoBuf.IExtensible
  {
    public RankHorseStone() {}
    
    private uint? _StoneType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"StoneType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StoneType
    {
      get { return _StoneType?? default(uint); }
      set { _StoneType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool StoneTypeSpecified
    {
      get { return this._StoneType != null; }
      set { if (value == (this._StoneType== null)) this._StoneType = value ? this.StoneType : (uint?)null; }
    }
    private bool ShouldSerializeStoneType() { return StoneTypeSpecified; }
    private void ResetStoneType() { StoneTypeSpecified = false; }
    
    private uint? _StoneLvl;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"StoneLvl", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint StoneLvl
    {
      get { return _StoneLvl?? default(uint); }
      set { _StoneLvl = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool StoneLvlSpecified
    {
      get { return this._StoneLvl != null; }
      set { if (value == (this._StoneLvl== null)) this._StoneLvl = value ? this.StoneLvl : (uint?)null; }
    }
    private bool ShouldSerializeStoneLvl() { return StoneLvlSpecified; }
    private void ResetStoneLvl() { StoneLvlSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RankHorseInfo")]
  public partial class RankHorseInfo : global::ProtoBuf.IExtensible
  {
    public RankHorseInfo() {}
    
    private byte[] _roleName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] roleName
    {
      get { return _roleName?? null; }
      set { _roleName = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleNameSpecified
    {
      get { return this._roleName != null; }
      set { if (value == (this._roleName== null)) this._roleName = value ? this.roleName : (byte[])null; }
    }
    private bool ShouldSerializeroleName() { return roleNameSpecified; }
    private void ResetroleName() { roleNameSpecified = false; }
    
    private uint? _infoId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"infoId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint infoId
    {
      get { return _infoId?? default(uint); }
      set { _infoId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool infoIdSpecified
    {
      get { return this._infoId != null; }
      set { if (value == (this._infoId== null)) this._infoId = value ? this.infoId : (uint?)null; }
    }
    private bool ShouldSerializeinfoId() { return infoIdSpecified; }
    private void ResetinfoId() { infoIdSpecified = false; }
    
    private uint? _level;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint level
    {
      get { return _level?? default(uint); }
      set { _level = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool levelSpecified
    {
      get { return this._level != null; }
      set { if (value == (this._level== null)) this._level = value ? this.level : (uint?)null; }
    }
    private bool ShouldSerializelevel() { return levelSpecified; }
    private void Resetlevel() { levelSpecified = false; }
    
    private uint? _star;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"star", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint star
    {
      get { return _star?? default(uint); }
      set { _star = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool starSpecified
    {
      get { return this._star != null; }
      set { if (value == (this._star== null)) this._star = value ? this.star : (uint?)null; }
    }
    private bool ShouldSerializestar() { return starSpecified; }
    private void Resetstar() { starSpecified = false; }
    
    private uint? _score;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint score
    {
      get { return _score?? default(uint); }
      set { _score = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool scoreSpecified
    {
      get { return this._score != null; }
      set { if (value == (this._score== null)) this._score = value ? this.score : (uint?)null; }
    }
    private bool ShouldSerializescore() { return scoreSpecified; }
    private void Resetscore() { scoreSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.RankHorseStone> _stone = new global::System.Collections.Generic.List<Proto.RankHorseStone>();
    [global::ProtoBuf.ProtoMember(6, Name=@"stone", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.RankHorseStone> stone
    {
      get { return _stone; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorldRankData")]
  public partial class WorldRankData : global::ProtoBuf.IExtensible
  {
    public WorldRankData() {}
    
    private uint? _number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint number
    {
      get { return _number?? default(uint); }
      set { _number = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool numberSpecified
    {
      get { return this._number != null; }
      set { if (value == (this._number== null)) this._number = value ? this.number : (uint?)null; }
    }
    private bool ShouldSerializenumber() { return numberSpecified; }
    private void Resetnumber() { numberSpecified = false; }
    
    private ulong? _rankKey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"rankKey", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong rankKey
    {
      get { return _rankKey?? default(ulong); }
      set { _rankKey = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankKeySpecified
    {
      get { return this._rankKey != null; }
      set { if (value == (this._rankKey== null)) this._rankKey = value ? this.rankKey : (ulong?)null; }
    }
    private bool ShouldSerializerankKey() { return rankKeySpecified; }
    private void ResetrankKey() { rankKeySpecified = false; }
    
    private ulong? _subKey;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"subKey", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong subKey
    {
      get { return _subKey?? default(ulong); }
      set { _subKey = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool subKeySpecified
    {
      get { return this._subKey != null; }
      set { if (value == (this._subKey== null)) this._subKey = value ? this.subKey : (ulong?)null; }
    }
    private bool ShouldSerializesubKey() { return subKeySpecified; }
    private void ResetsubKey() { subKeySpecified = false; }
    
    private uint? _rankValue;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rankValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankValue
    {
      get { return _rankValue?? default(uint); }
      set { _rankValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankValueSpecified
    {
      get { return this._rankValue != null; }
      set { if (value == (this._rankValue== null)) this._rankValue = value ? this.rankValue : (uint?)null; }
    }
    private bool ShouldSerializerankValue() { return rankValueSpecified; }
    private void ResetrankValue() { rankValueSpecified = false; }
    
    private Proto.RankRoleInfo _roleInfo = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"roleInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.RankRoleInfo roleInfo
    {
      get { return _roleInfo; }
      set { _roleInfo = value; }
    }
    private Proto.RankPetInfo _petInfo = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"petInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.RankPetInfo petInfo
    {
      get { return _petInfo; }
      set { _petInfo = value; }
    }
    private Proto.RankGuildInfo _guildInfo = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"guildInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.RankGuildInfo guildInfo
    {
      get { return _guildInfo; }
      set { _guildInfo = value; }
    }
    private Proto.RankWingInfo _wingInfo = null;
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"wingInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.RankWingInfo wingInfo
    {
      get { return _wingInfo; }
      set { _wingInfo = value; }
    }
    private Proto.RankHorseInfo _horseInfo = null;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"horseInfo", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public Proto.RankHorseInfo horseInfo
    {
      get { return _horseInfo; }
      set { _horseInfo = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdWorldRankRankListReq")]
  public partial class CmdWorldRankRankListReq : global::ProtoBuf.IExtensible
  {
    public CmdWorldRankRankListReq() {}
    
    private uint? _rankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankType
    {
      get { return _rankType?? default(uint); }
      set { _rankType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankTypeSpecified
    {
      get { return this._rankType != null; }
      set { if (value == (this._rankType== null)) this._rankType = value ? this.rankType : (uint?)null; }
    }
    private bool ShouldSerializerankType() { return rankTypeSpecified; }
    private void ResetrankType() { rankTypeSpecified = false; }
    
    private int? _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reason
    {
      get { return _reason?? default(int); }
      set { _reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reasonSpecified
    {
      get { return this._reason != null; }
      set { if (value == (this._reason== null)) this._reason = value ? this.reason : (int?)null; }
    }
    private bool ShouldSerializereason() { return reasonSpecified; }
    private void Resetreason() { reasonSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdWorldRankRankListRes")]
  public partial class CmdWorldRankRankListRes : global::ProtoBuf.IExtensible
  {
    public CmdWorldRankRankListRes() {}
    
    private uint? _rankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankType
    {
      get { return _rankType?? default(uint); }
      set { _rankType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankTypeSpecified
    {
      get { return this._rankType != null; }
      set { if (value == (this._rankType== null)) this._rankType = value ? this.rankType : (uint?)null; }
    }
    private bool ShouldSerializerankType() { return rankTypeSpecified; }
    private void ResetrankType() { rankTypeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.WorldRankData> _rankList = new global::System.Collections.Generic.List<Proto.WorldRankData>();
    [global::ProtoBuf.ProtoMember(2, Name=@"rankList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.WorldRankData> rankList
    {
      get { return _rankList; }
    }
  
    private uint? _myWorshipCount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"myWorshipCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint myWorshipCount
    {
      get { return _myWorshipCount?? default(uint); }
      set { _myWorshipCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool myWorshipCountSpecified
    {
      get { return this._myWorshipCount != null; }
      set { if (value == (this._myWorshipCount== null)) this._myWorshipCount = value ? this.myWorshipCount : (uint?)null; }
    }
    private bool ShouldSerializemyWorshipCount() { return myWorshipCountSpecified; }
    private void ResetmyWorshipCount() { myWorshipCountSpecified = false; }
    
    private int? _reason;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reason
    {
      get { return _reason?? default(int); }
      set { _reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reasonSpecified
    {
      get { return this._reason != null; }
      set { if (value == (this._reason== null)) this._reason = value ? this.reason : (int?)null; }
    }
    private bool ShouldSerializereason() { return reasonSpecified; }
    private void Resetreason() { reasonSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdWorldRankWorshipNtf")]
  public partial class CmdWorldRankWorshipNtf : global::ProtoBuf.IExtensible
  {
    public CmdWorldRankWorshipNtf() {}
    
    private uint? _myWorshipCount;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"myWorshipCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint myWorshipCount
    {
      get { return _myWorshipCount?? default(uint); }
      set { _myWorshipCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool myWorshipCountSpecified
    {
      get { return this._myWorshipCount != null; }
      set { if (value == (this._myWorshipCount== null)) this._myWorshipCount = value ? this.myWorshipCount : (uint?)null; }
    }
    private bool ShouldSerializemyWorshipCount() { return myWorshipCountSpecified; }
    private void ResetmyWorshipCount() { myWorshipCountSpecified = false; }
    
    private uint? _worshipCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"worshipCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint worshipCount
    {
      get { return _worshipCount?? default(uint); }
      set { _worshipCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool worshipCountSpecified
    {
      get { return this._worshipCount != null; }
      set { if (value == (this._worshipCount== null)) this._worshipCount = value ? this.worshipCount : (uint?)null; }
    }
    private bool ShouldSerializeworshipCount() { return worshipCountSpecified; }
    private void ResetworshipCount() { worshipCountSpecified = false; }
    
    private uint? _lastRefreshTime;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"lastRefreshTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint lastRefreshTime
    {
      get { return _lastRefreshTime?? default(uint); }
      set { _lastRefreshTime = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool lastRefreshTimeSpecified
    {
      get { return this._lastRefreshTime != null; }
      set { if (value == (this._lastRefreshTime== null)) this._lastRefreshTime = value ? this.lastRefreshTime : (uint?)null; }
    }
    private bool ShouldSerializelastRefreshTime() { return lastRefreshTimeSpecified; }
    private void ResetlastRefreshTime() { lastRefreshTimeSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<ulong> _worshipTargets = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(4, Name=@"worshipTargets", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> worshipTargets
    {
      get { return _worshipTargets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdWorldRankWorshipReq")]
  public partial class CmdWorldRankWorshipReq : global::ProtoBuf.IExtensible
  {
    public CmdWorldRankWorshipReq() {}
    
    private ulong? _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId?? default(ulong); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return this._roleId != null; }
      set { if (value == (this._roleId== null)) this._roleId = value ? this.roleId : (ulong?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdWorldRankWorshipSucRes")]
  public partial class CmdWorldRankWorshipSucRes : global::ProtoBuf.IExtensible
  {
    public CmdWorldRankWorshipSucRes() {}
    
    private ulong? _roleId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roleId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong roleId
    {
      get { return _roleId?? default(ulong); }
      set { _roleId = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool roleIdSpecified
    {
      get { return this._roleId != null; }
      set { if (value == (this._roleId== null)) this._roleId = value ? this.roleId : (ulong?)null; }
    }
    private bool ShouldSerializeroleId() { return roleIdSpecified; }
    private void ResetroleId() { roleIdSpecified = false; }
    
    private uint? _newWorshipCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"newWorshipCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint newWorshipCount
    {
      get { return _newWorshipCount?? default(uint); }
      set { _newWorshipCount = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool newWorshipCountSpecified
    {
      get { return this._newWorshipCount != null; }
      set { if (value == (this._newWorshipCount== null)) this._newWorshipCount = value ? this.newWorshipCount : (uint?)null; }
    }
    private bool ShouldSerializenewWorshipCount() { return newWorshipCountSpecified; }
    private void ResetnewWorshipCount() { newWorshipCountSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdWorldRankNumReq")]
  public partial class CmdWorldRankNumReq : global::ProtoBuf.IExtensible
  {
    public CmdWorldRankNumReq() {}
    
    private uint? _rankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankType
    {
      get { return _rankType?? default(uint); }
      set { _rankType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankTypeSpecified
    {
      get { return this._rankType != null; }
      set { if (value == (this._rankType== null)) this._rankType = value ? this.rankType : (uint?)null; }
    }
    private bool ShouldSerializerankType() { return rankTypeSpecified; }
    private void ResetrankType() { rankTypeSpecified = false; }
    
    private ulong? _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong key
    {
      get { return _key?? default(ulong); }
      set { _key = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool keySpecified
    {
      get { return this._key != null; }
      set { if (value == (this._key== null)) this._key = value ? this.key : (ulong?)null; }
    }
    private bool ShouldSerializekey() { return keySpecified; }
    private void Resetkey() { keySpecified = false; }
    
    private int? _reason;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reason
    {
      get { return _reason?? default(int); }
      set { _reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reasonSpecified
    {
      get { return this._reason != null; }
      set { if (value == (this._reason== null)) this._reason = value ? this.reason : (int?)null; }
    }
    private bool ShouldSerializereason() { return reasonSpecified; }
    private void Resetreason() { reasonSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CmdWorldRankNumRes")]
  public partial class CmdWorldRankNumRes : global::ProtoBuf.IExtensible
  {
    public CmdWorldRankNumRes() {}
    
    private uint? _rankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankType
    {
      get { return _rankType?? default(uint); }
      set { _rankType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankTypeSpecified
    {
      get { return this._rankType != null; }
      set { if (value == (this._rankType== null)) this._rankType = value ? this.rankType : (uint?)null; }
    }
    private bool ShouldSerializerankType() { return rankTypeSpecified; }
    private void ResetrankType() { rankTypeSpecified = false; }
    
    private ulong? _key;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong key
    {
      get { return _key?? default(ulong); }
      set { _key = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool keySpecified
    {
      get { return this._key != null; }
      set { if (value == (this._key== null)) this._key = value ? this.key : (ulong?)null; }
    }
    private bool ShouldSerializekey() { return keySpecified; }
    private void Resetkey() { keySpecified = false; }
    
    private int? _reason;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reason
    {
      get { return _reason?? default(int); }
      set { _reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reasonSpecified
    {
      get { return this._reason != null; }
      set { if (value == (this._reason== null)) this._reason = value ? this.reason : (int?)null; }
    }
    private bool ShouldSerializereason() { return reasonSpecified; }
    private void Resetreason() { reasonSpecified = false; }
    
    private uint? _rankNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"rankNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankNum
    {
      get { return _rankNum?? default(uint); }
      set { _rankNum = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankNumSpecified
    {
      get { return this._rankNum != null; }
      set { if (value == (this._rankNum== null)) this._rankNum = value ? this.rankNum : (uint?)null; }
    }
    private bool ShouldSerializerankNum() { return rankNumSpecified; }
    private void ResetrankNum() { rankNumSpecified = false; }
    
    private uint? _myValue;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"myValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint myValue
    {
      get { return _myValue?? default(uint); }
      set { _myValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool myValueSpecified
    {
      get { return this._myValue != null; }
      set { if (value == (this._myValue== null)) this._myValue = value ? this.myValue : (uint?)null; }
    }
    private bool ShouldSerializemyValue() { return myValueSpecified; }
    private void ResetmyValue() { myValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SmpRankEntry")]
  public partial class SmpRankEntry : global::ProtoBuf.IExtensible
  {
    public SmpRankEntry() {}
    
    private uint? _rankKey;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rankKey", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankKey
    {
      get { return _rankKey?? default(uint); }
      set { _rankKey = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankKeySpecified
    {
      get { return this._rankKey != null; }
      set { if (value == (this._rankKey== null)) this._rankKey = value ? this.rankKey : (uint?)null; }
    }
    private bool ShouldSerializerankKey() { return rankKeySpecified; }
    private void ResetrankKey() { rankKeySpecified = false; }
    
    private uint? _subKey;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"subKey", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint subKey
    {
      get { return _subKey?? default(uint); }
      set { _subKey = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool subKeySpecified
    {
      get { return this._subKey != null; }
      set { if (value == (this._subKey== null)) this._subKey = value ? this.subKey : (uint?)null; }
    }
    private bool ShouldSerializesubKey() { return subKeySpecified; }
    private void ResetsubKey() { subKeySpecified = false; }
    
    private byte[] _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] name
    {
      get { return _name?? null; }
      set { _name = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool nameSpecified
    {
      get { return this._name != null; }
      set { if (value == (this._name== null)) this._name = value ? this.name : (byte[])null; }
    }
    private bool ShouldSerializename() { return nameSpecified; }
    private void Resetname() { nameSpecified = false; }
    
    private uint? _value;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint value
    {
      get { return _value?? default(uint); }
      set { _value = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool valueSpecified
    {
      get { return this._value != null; }
      set { if (value == (this._value== null)) this._value = value ? this.value : (uint?)null; }
    }
    private bool ShouldSerializevalue() { return valueSpecified; }
    private void Resetvalue() { valueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SmpRankListReq")]
  public partial class SmpRankListReq : global::ProtoBuf.IExtensible
  {
    public SmpRankListReq() {}
    
    private uint? _rankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankType
    {
      get { return _rankType?? default(uint); }
      set { _rankType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankTypeSpecified
    {
      get { return this._rankType != null; }
      set { if (value == (this._rankType== null)) this._rankType = value ? this.rankType : (uint?)null; }
    }
    private bool ShouldSerializerankType() { return rankTypeSpecified; }
    private void ResetrankType() { rankTypeSpecified = false; }
    
    private int? _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reason
    {
      get { return _reason?? default(int); }
      set { _reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reasonSpecified
    {
      get { return this._reason != null; }
      set { if (value == (this._reason== null)) this._reason = value ? this.reason : (int?)null; }
    }
    private bool ShouldSerializereason() { return reasonSpecified; }
    private void Resetreason() { reasonSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SmpRankListRes")]
  public partial class SmpRankListRes : global::ProtoBuf.IExtensible
  {
    public SmpRankListRes() {}
    
    private uint? _rankType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"rankType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint rankType
    {
      get { return _rankType?? default(uint); }
      set { _rankType = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool rankTypeSpecified
    {
      get { return this._rankType != null; }
      set { if (value == (this._rankType== null)) this._rankType = value ? this.rankType : (uint?)null; }
    }
    private bool ShouldSerializerankType() { return rankTypeSpecified; }
    private void ResetrankType() { rankTypeSpecified = false; }
    
    private int? _reason;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int reason
    {
      get { return _reason?? default(int); }
      set { _reason = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool reasonSpecified
    {
      get { return this._reason != null; }
      set { if (value == (this._reason== null)) this._reason = value ? this.reason : (int?)null; }
    }
    private bool ShouldSerializereason() { return reasonSpecified; }
    private void Resetreason() { reasonSpecified = false; }
    
    private readonly global::System.Collections.Generic.List<Proto.SmpRankEntry> _rankList = new global::System.Collections.Generic.List<Proto.SmpRankEntry>();
    [global::ProtoBuf.ProtoMember(3, Name=@"rankList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<Proto.SmpRankEntry> rankList
    {
      get { return _rankList; }
    }
  
    private uint? _myValue;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"myValue", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint myValue
    {
      get { return _myValue?? default(uint); }
      set { _myValue = value; }
    }
    [global::System.Xml.Serialization.XmlIgnore]
    [global::System.ComponentModel.Browsable(false)]
    public bool myValueSpecified
    {
      get { return this._myValue != null; }
      set { if (value == (this._myValue== null)) this._myValue = value ? this.myValue : (uint?)null; }
    }
    private bool ShouldSerializemyValue() { return myValueSpecified; }
    private void ResetmyValue() { myValueSpecified = false; }
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"CmdWorldRank")]
    public enum CmdWorldRank
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdWorldRank_RankListReq", Value=4101)]
      CmdWorldRank_RankListReq = 4101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdWorldRank_RankListRes", Value=4102)]
      CmdWorldRank_RankListRes = 4102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdWorldRank_WorshipNtf", Value=4103)]
      CmdWorldRank_WorshipNtf = 4103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdWorldRank_WorshipReq", Value=4104)]
      CmdWorldRank_WorshipReq = 4104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdWorldRank_WorshipSucRes", Value=4105)]
      CmdWorldRank_WorshipSucRes = 4105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdWorldRank_NumReq", Value=4106)]
      CmdWorldRank_NumReq = 4106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdWorldRank_NumRes", Value=4107)]
      CmdWorldRank_NumRes = 4107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdWorldRank_SmpRankListReq", Value=4108)]
      CmdWorldRank_SmpRankListReq = 4108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CmdWorldRank_SmpRankListRes", Value=4109)]
      CmdWorldRank_SmpRankListRes = 4109
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"ErrorWorldRank")]
    public enum ErrorWorldRank
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_InfoNotFound", Value=4101)]
      Error_WorldRank_InfoNotFound = 4101,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_RankNotFound", Value=4102)]
      Error_WorldRank_RankNotFound = 4102,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_WorshipFull", Value=4103)]
      Error_WorldRank_WorshipFull = 4103,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_WorshipTargetNotExit", Value=4104)]
      Error_WorldRank_WorshipTargetNotExit = 4104,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_RoleNotOnline", Value=4105)]
      Error_WorldRank_RoleNotOnline = 4105,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_RoleNotExist", Value=4106)]
      Error_WorldRank_RoleNotExist = 4106,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_WingNotExist", Value=4107)]
      Error_WorldRank_WingNotExist = 4107,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_PetNotExist", Value=4108)]
      Error_WorldRank_PetNotExist = 4108,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_AlreadyInRoleStatList", Value=4109)]
      Error_WorldRank_AlreadyInRoleStatList = 4109,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_RoleStatListFull", Value=4110)]
      Error_WorldRank_RoleStatListFull = 4110,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_NotInRoleStatList", Value=4111)]
      Error_WorldRank_NotInRoleStatList = 4111,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_GetWorshipDailyCountFailed", Value=4112)]
      Error_WorldRank_GetWorshipDailyCountFailed = 4112,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_CantWorshipSelf", Value=4113)]
      Error_WorldRank_CantWorshipSelf = 4113,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_GetLevelInfoFailed", Value=4114)]
      Error_WorldRank_GetLevelInfoFailed = 4114,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_AlreadyMaxWorshipCount", Value=4115)]
      Error_WorldRank_AlreadyMaxWorshipCount = 4115,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_GetWorshipMaxCountFailed", Value=4116)]
      Error_WorldRank_GetWorshipMaxCountFailed = 4116,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_GetWorshipRoleStatFailed", Value=4117)]
      Error_WorldRank_GetWorshipRoleStatFailed = 4117,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_AlreadyInWoshipTargetList", Value=4118)]
      Error_WorldRank_AlreadyInWoshipTargetList = 4118,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_WoshipTargetListFull", Value=4119)]
      Error_WorldRank_WoshipTargetListFull = 4119,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_NotInWoshipTargetList", Value=4120)]
      Error_WorldRank_NotInWoshipTargetList = 4120,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_CantWorshipSame", Value=4121)]
      Error_WorldRank_CantWorshipSame = 4121,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_RoleNotExit", Value=4122)]
      Error_WorldRank_RoleNotExit = 4122,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_GuildNotExit", Value=4123)]
      Error_WorldRank_GuildNotExit = 4123,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_RankClassNotExit", Value=4124)]
      Error_WorldRank_RankClassNotExit = 4124,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_AlreadyInRankRunTimeInfoList", Value=4125)]
      Error_WorldRank_AlreadyInRankRunTimeInfoList = 4125,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_RankRunTimeInfoListFull", Value=4126)]
      Error_WorldRank_RankRunTimeInfoListFull = 4126,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_NotInRankRunTimeInfoList", Value=4127)]
      Error_WorldRank_NotInRankRunTimeInfoList = 4127,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_GetRankRunTimeInfoFailed", Value=4128)]
      Error_WorldRank_GetRankRunTimeInfoFailed = 4128,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_GetRankWorshipExpMulInfoFailed", Value=4129)]
      Error_WorldRank_GetRankWorshipExpMulInfoFailed = 4129,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Error_WorldRank_HorseNotExist", Value=4130)]
      Error_WorldRank_HorseNotExist = 4130
    }
  
}